### ISSUE TITLE
how to add drawing manager in the map and perform operations on polygons?

### ISSUE THREAD

**Issue by subhamagr** [istarkov/google-map-react#102]
I have been working google maps for a while. your marker stuff works very well. Now i need to work with polygons. I want to add polygons via drawing manager of google maps and performs operations like add, delete, change shape or position.. How do i do that? help me

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/issues/62

**Comment by subhamagr** [comment]
i have readt thay. but any way to add drawing manager and use it?

**Comment by istarkov** [comment]
what is drawing manager?

**Comment by subhamagr** [comment]
https://developers.google.com/maps/documentation/javascript/examples/drawing-tools
its gives a tool bar for drawing various shapes on the map

**Comment by istarkov** [comment]
```
const bootstrapURLKeys={
  key: YOUR_API_KEY,
  libraries: ['drawing'],
}
```

Add propery to `GoogleMap`

```
<GoogleMap bootstrapURLKeys={bootstrapURLKeys}
```

Search in docs `yesIWantToUseGoogleMapApiInternals`

That's all.

**Comment by subhamagr** [comment]
how do i access google.maps. object?

**Comment by istarkov** [comment]
Search in docs `yesIWantToUseGoogleMapApiInternals`

**Comment by tonyspiro** [comment]
In case anyone else is trying to do this.  This worked for me:
```javascript
...
handleGoogleMapApi(google) {
    const map = google.map
    const drawingManager = new google.maps.drawing.DrawingManager({
      drawingMode: google.maps.drawing.OverlayType.MARKER,
      drawingControl: true,
      drawingControlOptions: {
        position: google.maps.ControlPosition.TOP_CENTER,
        drawingModes: [
          google.maps.drawing.OverlayType.MARKER,
          google.maps.drawing.OverlayType.CIRCLE,
          google.maps.drawing.OverlayType.POLYGON,
          google.maps.drawing.OverlayType.POLYLINE,
          google.maps.drawing.OverlayType.RECTANGLE
        ]
      },
      markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
      circleOptions: {
        fillColor: '#ffff00',
        fillOpacity: 1,
        strokeWeight: 5,
        clickable: false,
        editable: true,
        zIndex: 1
      }
    });
    drawingManager.setMap(map);
  }
...
<GoogleMap
  bootstrapURLKeys={ bootstrap_url_keys }
  center={ your_center }
  zoom={ your_zoom }
  yesIWantToUseGoogleMapApiInternals
  onGoogleApiLoaded={ this.handleGoogleMapApi.bind(this) }
>
  { markers }
</GoogleMap>
...
```

**Comment by bhavikji** [comment]
> In case anyone else is trying to do this. This worked for me:
> 
> ```js
> ...
> handleGoogleMapApi(google) {
>     const map = google.map
>     const drawingManager = new google.maps.drawing.DrawingManager({
>       drawingMode: google.maps.drawing.OverlayType.MARKER,
>       drawingControl: true,
>       drawingControlOptions: {
>         position: google.maps.ControlPosition.TOP_CENTER,
>         drawingModes: [
>           google.maps.drawing.OverlayType.MARKER,
>           google.maps.drawing.OverlayType.CIRCLE,
>           google.maps.drawing.OverlayType.POLYGON,
>           google.maps.drawing.OverlayType.POLYLINE,
>           google.maps.drawing.OverlayType.RECTANGLE
>         ]
>       },
>       markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
>       circleOptions: {
>         fillColor: '#ffff00',
>         fillOpacity: 1,
>         strokeWeight: 5,
>         clickable: false,
>         editable: true,
>         zIndex: 1
>       }
>     });
>     drawingManager.setMap(map);
>   }
> ...
> <GoogleMap
>   bootstrapURLKeys={ bootstrap_url_keys }
>   center={ your_center }
>   zoom={ your_zoom }
>   yesIWantToUseGoogleMapApiInternals
>   onGoogleApiLoaded={ this.handleGoogleMapApi.bind(this) }
> >
>   { markers }
> </GoogleMap>
> ...
> ```

this solution is not working now. plus, it's outdated.

**Comment by balanza** [comment]
@bhavikji did you sort out another solution?

> > In case anyone else is trying to do this. This worked for me:
> > ```js
> > ...
> > handleGoogleMapApi(google) {
> >     const map = google.map
> >     const drawingManager = new google.maps.drawing.DrawingManager({
> >       drawingMode: google.maps.drawing.OverlayType.MARKER,
> >       drawingControl: true,
> >       drawingControlOptions: {
> >         position: google.maps.ControlPosition.TOP_CENTER,
> >         drawingModes: [
> >           google.maps.drawing.OverlayType.MARKER,
> >           google.maps.drawing.OverlayType.CIRCLE,
> >           google.maps.drawing.OverlayType.POLYGON,
> >           google.maps.drawing.OverlayType.POLYLINE,
> >           google.maps.drawing.OverlayType.RECTANGLE
> >         ]
> >       },
> >       markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
> >       circleOptions: {
> >         fillColor: '#ffff00',
> >         fillOpacity: 1,
> >         strokeWeight: 5,
> >         clickable: false,
> >         editable: true,
> >         zIndex: 1
> >       }
> >     });
> >     drawingManager.setMap(map);
> >   }
> > ...
> > <GoogleMap
> >   bootstrapURLKeys={ bootstrap_url_keys }
> >   center={ your_center }
> >   zoom={ your_zoom }
> >   yesIWantToUseGoogleMapApiInternals
> >   onGoogleApiLoaded={ this.handleGoogleMapApi.bind(this) }
> > >
> >   { markers }
> > </GoogleMap>
> > ...
> > ```
> 
> this solution is not working now. plus, it's outdated.

**Comment by hongdung6992** [comment]
> In case anyone else is trying to do this. This worked for me:
> 
> ```js
> ...
> handleGoogleMapApi(google) {
>     const map = google.map
>     const drawingManager = new google.maps.drawing.DrawingManager({
>       drawingMode: google.maps.drawing.OverlayType.MARKER,
>       drawingControl: true,
>       drawingControlOptions: {
>         position: google.maps.ControlPosition.TOP_CENTER,
>         drawingModes: [
>           google.maps.drawing.OverlayType.MARKER,
>           google.maps.drawing.OverlayType.CIRCLE,
>           google.maps.drawing.OverlayType.POLYGON,
>           google.maps.drawing.OverlayType.POLYLINE,
>           google.maps.drawing.OverlayType.RECTANGLE
>         ]
>       },
>       markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
>       circleOptions: {
>         fillColor: '#ffff00',
>         fillOpacity: 1,
>         strokeWeight: 5,
>         clickable: false,
>         editable: true,
>         zIndex: 1
>       }
>     });
>     drawingManager.setMap(map);
>   }
> ...
> <GoogleMap
>   bootstrapURLKeys={ bootstrap_url_keys }
>   center={ your_center }
>   zoom={ your_zoom }
>   yesIWantToUseGoogleMapApiInternals
>   onGoogleApiLoaded={ this.handleGoogleMapApi.bind(this) }
> >
>   { markers }
> </GoogleMap>
> ...
> ```

google-map-react doesn't include drawing library so it shows error TypeError: Cannot read property 'DrawingManager' of undefined
How to fix it?

**Comment by Yaneeks** [comment]
A little update to fix the problem above

`
const handleGoogleMapApi = (map, google) => {

    const drawingManager =  new google.drawing.DrawingManager({
      drawingMode: google.drawing.OverlayType.MARKER,
      drawingControl: true,
      drawingControlOptions: {
        position: google.ControlPosition.TOP_CENTER,
        drawingModes: [
          google.drawing.OverlayType.MARKER,
          google.drawing.OverlayType.CIRCLE,
          google.drawing.OverlayType.POLYGON,
          google.drawing.OverlayType.POLYLINE,
          google.drawing.OverlayType.RECTANGLE,
        ],
      },
      markerOptions: {
        icon:
          "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
      },
      circleOptions: {
        fillColor: "#ffff00",
        fillOpacity: 1,
        strokeWeight: 5,
        clickable: false,
        editable: true,
        zIndex: 1,
      },
    });

    drawingManager.setMap(map);
  };
...
<GoogleMap
  bootstrapURLKeys={ bootstrap_url_keys }
  center={ your_center }
  zoom={ your_zoom }
  yesIWantToUseGoogleMapApiInternals={true}
  onGoogleApiLoaded={({ map, maps }) => handleGoogleMapApi(map, maps)}
>
`

**Comment by andyzeli** [comment]
is yesIWantToUseGoogleMapApiInternals deprecated? all i see when searching is the console warning message.
