### ISSUE TITLE
marker centering on click

### ISSUE THREAD

**Issue by geritol** [istarkov/google-map-react#105]
Hi!
Is there possibility to somehow horizontally center, veritcally put on the to 20% of the map a marker after I click on it (moving the map not the marker).
Thanks a lot!

**Comment by istarkov** [comment]
Please translate

**Comment by geritol** [comment]
When i click a makrer (A) i can center it (c), but i would like to position is vertically not in the middle, but offset a little bit (like t)

![map](https://cloud.githubusercontent.com/assets/5496681/13106177/333c012a-d567-11e5-85e3-834ef0aae3d1.png)

**Comment by istarkov** [comment]
As I understand your problem that you don't know the way how to calculate `lat` offset for `center` prop.

Do you need something like this?
`center = {lat: marker.lat - 100px, lng: marker.lng}`

So you need some math to convert px to lat, it's easy:

You have in onChange event `bounds` and `size`

```
bounds = {
  nw: {
    lat: 50.01038826014866,
    lng: -118.6525866875
  },
  se: {
    lat: 32.698335045970396,
    lng: -92.0217273125
  }
};
```


So to convert `100px` to lat offset your just need  

```
latOffset = 100 * (nw.lat - se.lat) / size.height
```

Now you can  `center = {lat: marker.lat - latOffset, lng: marker.lng}`

**Comment by geritol** [comment]
thanks! how do i get the bounds?

**Comment by istarkov** [comment]
At onChange event you will get bounds and size

**Comment by geritol** [comment]
thankyou!
On change trigers initially also so this is perfect :+1:

**Comment by geritol** [comment]
just curious: is there a way to animate map centering?
