### ISSUE TITLE
Provision for google map resize event

### ISSUE THREAD

**Issue by rahulinaction** [istarkov/google-map-react#106]
Is there a  provision to use google maps resize event?

**Comment by istarkov** [comment]
What are really you want?

**Comment by rahulinaction** [comment]
I resize  my map container on marker click and subsequently reduce the container height . I need to reposition the map according to the new height ie move my map center .

**Comment by istarkov** [comment]
As I remember map resize event will not raise on layout changes (only on window resize).
There is no simple way to detect this without quering the element dimensions in some loop, and in html query dimension causes reflow. So access to `resize` event will not help you. (Internally this component uses just window resize events.

So there are hacks how to refresh (just search issues with refresh word) for example read this thread https://github.com/istarkov/google-map-react/issues/44#issuecomment-146638300

For declarative refresh we need something like `refreshSizeToken` property, and any change to this prop will cause internal `viewSize` refresh.
But I feel that a better solution exists, need to think some time.
