### ISSUE TITLE
animate centering

### ISSUE THREAD

**Issue by geritol** [istarkov/google-map-react#107]
just curious: is there a way to animate map centering?

**Comment by istarkov** [comment]
It's animated, when you change center prop, map makes pan to that position.

**Comment by geritol** [comment]
sorry, yes.
Is there a way to change the 'curve of this animation?

**Comment by istarkov** [comment]
Have you tried something like react-motion with animated center prop?

**Comment by geritol** [comment]
not yet, closing this, thanks for the help and your work on this component!
