### ISSUE TITLE
Zoom definition error (negative argument for logarithm return NaN)

### ISSUE THREAD

**Issue by americaru** [istarkov/google-map-react#109]
![screenshot 2016-03-01 18 07 32](https://cloud.githubusercontent.com/assets/17506504/13433113/21282e42-dfd9-11e5-93c8-e0af8219aa78.png)

`var dy = seWorld.y - nwWorld.y;`
- is negative

**Comment by americaru** [comment]
First, I think there is valid condition: 
`    if (dx <= 0 || dy <= 0) {
      return null;
    }`

**Comment by istarkov** [comment]
can't get, what is the problem?

**Comment by americaru** [comment]
Returned Zoom is NaN

**Comment by istarkov** [comment]
For what input?

**Comment by americaru** [comment]
For this input:
`
        var bounds = {, lng: 
          nw: {
            lat: 32.698335045970396,
            lng: -92.0217273125
          },
          se: {
            lat: 42.387176,
            lng: -88.0053115
          }
        };

        var size = {
          width: 300,
          height: 300
        };

        var _fitBounds = GoogleMapUtils.fitBounds({ nw: bounds.nw, se: bounds.se }, size);

        var center = _fitBounds.center;
        var zoom = _fitBounds.zoom;
`

**Comment by istarkov** [comment]
north latitude is always greater than south lat, 
incorrect input gives NaN result

**Comment by americaru** [comment]
Thank you!
