### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by brandonmp** [istarkov/google-map-react#110]
I've been trying to recreate the basic example for awhile now, but I can't get the map to render at all.  I'm not deviating from the given examples too much I don't think, but even w/o changing any code (besides the marker component), nothing renders.

Actually, my marker renders in the top-center of the screen for a brief second, but then disappears. 

Happy to try any ideas to figure this out.  

Here's the component code, all client-side rendering--only changes from sample in the readme is some changes to ES5 syntax & using a material-ui icon as marker: 
```
import React from 'react';
import ReactDOM from 'react-dom';
import SvgIcon from 'material-ui/lib/svg-icon';
import GoogleMap from 'google-map-react';
import Colors from 'material-ui/lib/styles/colors';
var PureRenderMixin = require('react-addons-pure-render-mixin');

const HomeIcon = (props) => (
    <SvgIcon {...props}>
        <path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/>
    </SvgIcon>
);

const ListingMap = React.createClass(
    {
        mixins: [PureRenderMixin],
        getDefaultProps: function () {
            return {

                center: {lat: 59.938043, lng: 30.337157},
                zoom: 9,
                greatPlaceCoords: {lat: 59.724465, lng: 30.080121}
            }
        },

        render: function () {
            return (
                <GoogleMap
                    defaultCenter={this.props.center}
                    defaultZoom={this.props.zoom}>
                    <HomeIcon
                        color={Colors.red500}
                        hoverColor={Colors.greenA200}
                        lat={59.955413} lng={30.337844}
                    />
                </GoogleMap>

            );
        }
    });

ReactDOM.render((
    <ListingMap />
), document.querySelector('.container'));
```

The only thing the console throws is:

````
GoogleMap: minZoom option is less than recommended minZoom option for your map sizes.
overrided to value 4
````

**Comment by istarkov** [comment]
All examples work. Because github.io examples builded from examples project. Also there is jsbin example in readme, which also work. I can't get what is your problem. Also I don't want to check or support old js code.

**Comment by brandonmp** [comment]
well, thanks, i guess.


anyway if someone else bumps into this error, apparently the problem has to do with wrapping the map in a div. I must have missed that in the docs.

please note that this was the case both in es6 syntax and es5 syntax.

works:
````
ReactDOM.render((
    <div style={{width: '100%', height: 400}}>
        <ListingMap />
    </div>
), document.querySelector('.container'));
````

does not work:
````
ReactDOM.render((
        <ListingMap />
), document.querySelector('.container'));
````

**Comment by istarkov** [comment]
there are two way to write components like this
- allow to fit parent size
- allow to set it's own via styles or classes

by default it uses first.
