### ISSUE TITLE
Is library still alive?

### ISSUE THREAD

**Issue by pavelkornev** [istarkov/google-map-react#112]
Is there any roadmap?

**Comment by istarkov** [comment]
As in readme: *It just allows you to render any React component on the Google Map.*
And this works.

What roadmap can be done for this simple idea?

**Comment by istarkov** [comment]
And as it works as expected, sometimes I add new examples like this http://istarkov.github.io/google-map-clustering-example/

**Comment by pavelkornev** [comment]
1. How about to add other maps Providers (Bing, Here, Yandex...)?
2. Clean up npm build (remove unnecessary files like webpack configs)
3. Update dependency versions
4. Try to reduce dependency list. E.g. why library needs [react-pure-render](https://github.com/gaearon/react-pure-render)? Why it's not enough just using stateless components?

**Comment by istarkov** [comment]
It is an opensource project, you can do any changes you want and propose to this library via PR or create your own library.
So I can ask u the same issues, why all of above is not inPRs of this library?

**Comment by pavelkornev** [comment]
Please calm down. This thread has been created to figure out author plans. If there aren't any, it's fine, just close this issue.

**Comment by pavelkornev** [comment]
Quote from [authors Twitter](https://twitter.com/icelabaratory/status/708705602541916160):
> Mad js world, libraries with last change just one month ago, receives "Is library still alive?" issues https://github.com/istarkov/google-map-react/issues/112

I would agree that task was named inaccurately, my apologies. But i don't think that this sarcastic message appropriate in this context. Anyway i've changed title to alleviate author pain.

**Comment by istarkov** [comment]
Author has no pain or even sarcasm. I'm sorry if I've offended you. 
I'll try to explain my position below.

All of my opensource projects is just for fun. I understand that a lot of people like some corporate software culture like plans, etc. I have all of this on my main work - plans, jira etc. 
Author don't want to make all of this in his fun projects. 
But author will like if anybody will do it, and even will add any person with good skills as repo contributor (I did this easily)
Author think that the best issue is a PR with changes you need - like - want.
Be sure that author has few children, life out of the github, work, new fun ideas, and not a lot of free time.

Have any questions don't hesitate to contact me over email (prefs), skype (cybice).

Yours, Ivan :-) .
