### ISSUE TITLE
Changes in the lodash API v4

### ISSUE THREAD

**Issue by mauriciosoares** [istarkov/google-map-react#113]
Hello, I tried to install google-map-react module in my app, but in compilation time I got the following errors:

```
ERROR in ./~/google-map-react/lib/google_map.js
Module not found: Error: Cannot resolve module 'lodash/object/assign' in /opt/loggi/retail-web-ui/node_modules/google-map-react/lib
 @ ./~/google-map-react/lib/google_map.js 73:26-57

ERROR in ./~/google-map-react/lib/google_map.js
Module not found: Error: Cannot resolve module 'lodash/lang/isNumber' in /opt/loggi/retail-web-ui/node_modules/google-map-react/lib
 @ ./~/google-map-react/lib/google_map.js 77:26-57

ERROR in ./~/google-map-react/lib/utils/loaders/google_map_loader.js
Module not found: Error: Cannot resolve module 'lodash/collection/find' in /opt/loggi/retail-web-ui/node_modules/google-map-react/lib/utils/loaders
 @ ./~/google-map-react/lib/utils/loaders/google_map_loader.js 8:28-61

ERROR in ./~/google-map-react/lib/utils/loaders/google_map_loader.js
Module not found: Error: Cannot resolve module 'lodash/collection/reduce' in /opt/loggi/retail-web-ui/node_modules/google-map-react/lib/utils/loaders
 @ ./~/google-map-react/lib/utils/loaders/google_map_loader.js 12:30-65
```

I've done some research, and apparently lodash [dropped support](https://github.com/tgriesser/knex/issues/1214) for this deep nesting requiring in version 4 and above (`lodash/lang/isNumber`, `lodash/object/assign`), and since the lodash dependency in this project is using the `^` sign, it's probably getting my v4 version of lodash.

Do you think this error is something particular to my project? or maybe you should update the lodash requires in this module?

**Comment by istarkov** [comment]
As I clearly understand `package.json` dependencies 
this `"lodash": "^3.10.1",` here https://github.com/istarkov/google-map-react/blob/master/package.json#L41means that lodash can't exceed 3.x version on `npm install`.

I have projects where I use lodash 4 and this map without any issues. 
So just try a clean npm install

```
rm -rf node_modules
npm install
```

BTW it will be good to update current lodash.

**Comment by mauriciosoares** [comment]
@istarkov you're correct... the version in your `package.json` should not conflict with the one I'm using in my prjoect.

I'll try to figure out what's happening, I'll close this issue for now.

Thanks

**Comment by istarkov** [comment]
google-map-react@0.10.6
