### ISSUE TITLE
Add support for GoogleStyledMaps

### ISSUE THREAD

**Issue by canfie1d** [istarkov/google-map-react#115]
Currently, you are only able to implement the standard google map API but Styled Maps API support would be an excellent addition to this package.

In my case, I would love to remove the "Report a map error" and make use of the white Google logo. Additionally, being able to manipulate style of the zoom controls would be great.

https://developers.google.com/maps/documentation/javascript/styling#creating_a_styledmaptype

Thanks for all of your work on this package.

**Comment by istarkov** [comment]
You are also able to create this ;-) it's easy. If you interested in, I'll write you here how to create PR with styles support.

**Comment by gabriel-laet** [comment]
Not sure if it's the same thing, but I can change map style using `options={{styles: mapStyles, disableDefaultUI: true}}`

**Comment by istarkov** [comment]
This can be done via `options` props, 
```
styles: [
        {
           stylers: [
        //     { saturation: 0 },
        //     { gamma: 0.8 },
        //     { lightness: 1 },
        //     { visibility: 'on' },
        ],
        },
        {
          featureType: 'administrative',
          stylers: [
            { visibility: 'off' },
          ],
        },
        {
```
