### ISSUE TITLE
isReact14() is not working with React 15

### ISSUE THREAD

**Issue by mtoso** [istarkov/google-map-react#116]
I was trying to update a project where I use this package with React@15.0.0-rc.1 and ReactDOM@15.0.0-rc.1 and I have this error:

```
ReactDOM.findDOMNode is not a function
```

From what I understand looking at the source code, the problem is due to the function `isReact14()` inside *src/utils/react_version.js*

Now that the major version of React is changed from 0.xx.x to 15.xx.x according to these [release note ](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html) the check for the major version is failing and React is required instead of ReactDOM.

`.findDOMNode()` form React 14 is defined inside ReactDOM

I'll file a PR shortly with the fix for discussion.

**Comment by istarkov** [comment]
Looks like it's better to deprecate `react 0.13` and remove all that checks. It will be super cool if you provide a PR. Thank you.

**Comment by mtoso** [comment]
Thanks for the replay. I was wondering if is better to write on the README that the min version of React supported by this module is React 0.14.0 or also have a warning on the console to warn the user to use a version of React >= 0.14

**Comment by istarkov** [comment]
Just peerDependency in package json will be enough 

```
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.0-rc.1"
  }
```

no need to change documentation

**Comment by mtoso** [comment]
Cool thanks. I'll do the PR.
