### ISSUE TITLE
Creating a Marker with a real world size radius

### ISSUE THREAD

**Issue by belohlavek** [istarkov/google-map-react#123]
Hello!

I'm looking for a way to achieve [this result](https://developers.google.com/maps/documentation/javascript/examples/circle-simple) using my own custom react component as a marker. I can't figure out a way to create a radius with a real world distance  (in meters). Does anyone know how the internal utils work and how/if they can be used to get to the desired result?

Thanks in advance :smile:

**Comment by istarkov** [comment]
just call this function https://github.com/istarkov/google-map-react/blob/master/src/utils/utils.js#L103 

```
import { meters2ScreenPixels } from 'google-map-react/utils';
...
// meters - length in meters
// lat lng - center coordinate
const {w, h} = meters2ScreenPixels(meters, {lat, lng}, zoom);
// w = length in pixels along lng
// h = length in pixels along lat
```

**Comment by belohlavek** [comment]
It worked as expected, thanks :smile: 
I ended up using onChange to get an updated zoom value, which I saved as the state of my component and then passed into the child marker for accurate scaling. Was there an easier way to get the updated zoom value? (I'm new to react!)

Thanks for the help!

**Comment by istarkov** [comment]
Just one idea ;-) - http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by belohlavek** [comment]
I see, it seems that my train of thought was the right one :+1: 

Closing and thanks again!
