### ISSUE TITLE
Bounds not updating when surrounding div resizes.

### ISSUE THREAD

**Issue by thunderkid** [istarkov/google-map-react#124]
I have a google-map-react component in a surrounding div. When the surrounding div resizes, the map obviously resizes too. But `getBounds` doesn't change.
I'm currently fixing this with the following hack:
```
componentDidUpdate() {
        if (this.map)
            google.maps.event.trigger(this.map, 'resize'); 
}
```
Is this necessary or is there a better way?

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/issues/106#issuecomment-187944697

When I will have a time I will play with this https://github.com/sdecima/javascript-detect-element-resize element size detection lib.

**Comment by thunderkid** [comment]
Thanks. My method actually has significant problems - although `getBounds` then gives the correct bounds, it also gives `GoogleMap bounds not eq` errors in the console, and the markers suddenly jump to the wrong position.

**Comment by thunderkid** [comment]
Ok, so I'm now trying to do this with the [`element-resize-detector`](https://www.npmjs.com/package/element-resize-detector) library on the DOM node. That part seems to work fine - it correctly detects when the map `div` changes. Whenever this occurs, I run 
`google.maps.event.trigger(this.map, 'resize')`.

But this does not seem sufficient - when the `div` changes size, the map markers jump to an incorrect place (chrome and IE11). I've even tried adding a debugging button to run `google.maps.event.trigger(this.map, 'resize')` by force. When I change the div size, the markers move to the wrong place. Clicking my debug button does not do anything. But then if I slightly resize the browser window, the markers jump back to the correct place. So the `trigger resize` function is not sufficient. Somehow resizing the browser does something else too. Any idea what this is?

**Comment by istarkov** [comment]
No simple ideas now. 
As a dirty hack call via component ref  `_onWindowResize` method before triggering resize event.
If it will be not enough also change center on a small value after trigger.

**Comment by istarkov** [comment]
I think I will add width and height props, and give an example of how to use AutoSizer control from `react-virtualized` https://github.com/bvaughn/react-virtualized/blob/b12bae6cddb3a604269a42b53a0b970f4a158ef0/source/AutoSizer/AutoSizer.js

**Comment by istarkov** [comment]
Close as in todo list https://github.com/istarkov/google-map-react/issues/147
