### ISSUE TITLE
Problems with zoom

### ISSUE THREAD

**Issue by fuelen** [istarkov/google-map-react#125]
I have two actions, userEnableFocus and userDisableFocus.
I want to focus map on the user (marker) with zooming.
For now, I click on user in my sidebar and map focuses on user. I can change map position (navigation through dng) and all is ok. But with zoom param this trick doesn't work(when I disable focus) and zoom, if I understand, converts to 0 and I can see entire world.. What value for zoom should be used to keep zoom unchanged? undefined also not works (there are no zoom in this case). Or I should use another way?
```
        <GoogleMap
          style={ googleMapStyles }
          defaultCenter={ this.props.defaultCenter }
          defaultZoom={ this.props.defaultZoom }
          center={ this.props.center }
          zoom={ this.props.zoom }
          bootstrapURLKeys={{ key: GOOGLE_API_KEY }}
        >
 ....

function select(state) {
  let center = null
  let zoom   = null
  if (state.map.focusedUser !== null) {
    center = R.props(['lat', 'lng'], state.server.users[state.map.focusedUser].position)
    zoom = 17
  }
  return { center,    zoom }
}
```

**Comment by istarkov** [comment]
Please read.
https://github.com/istarkov/google-map-react/issues/87#issuecomment-171331940

Then this http://facebook.github.io/react/docs/forms.html#controlled-components

And this again https://github.com/istarkov/google-map-react/issues/87#issuecomment-171331940

The same you will get even on simple input field without getting the idea of controllable and uncontrollable state.

Also you can write non working examples on jsbin https://jsbin.com/lepadusowo/edit?js,console,output

It will be easier for me to understand your issue.

;-) Ivan ;-)

**Comment by fuelen** [comment]
@istarkov this was my second idea :) thank you.
