### ISSUE TITLE
possibility to disable - reenable map interaction?

### ISSUE THREAD

**Issue by geritol** [istarkov/google-map-react#126]
Hi!

is there a way to disable map interactions (like zoom, hovering other markers, google maps objects).
For example: if a marker is hovered, i would like to disable zoom on mouse movements.

Thanks a lot!

**Comment by istarkov** [comment]
Yes.
There is property for disable drag - `draggable`.
It's on you to disable hover - a lot of variants how to do: 
1) Change distance to disabled makers in `distanceToMouse`
2) Just not show animations in unused markers
etc

There are no options to disable zoom as like `draggable` but it can be added easily like as done in `draggable`   https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L247. 
I'll accept such PR.

**Comment by geritol** [comment]
Thanks!
draggable is working fine!
on markers, I can handle my owns, I meant the marker that show bus/train stops for example.

for zoomable I implemented something along draggable, not sure how to bundle/test it.
[google_map.txt](https://github.com/istarkov/google-map-react/files/201285/google_map.txt)
can you take a look?

Thanks!

**Comment by istarkov** [comment]
@geritol Don't afraid to create PRs, I love PRs, everybody love PRs, 
and it's easy using PR interface to compare your version with current, 
and even if PR is not what I want, we can discuss it there and find a good solution ;-)
I'll wait your PR ;-)

**Comment by istarkov** [comment]
About test your changes - I just use a webpack alias in last project I've used this map, like 
```
const alias = {
    'google-map-react': path.join(__dirname, 'YOURPATH/google-map-react', 'src'),
}
....
   
export default {// webpack stuff
 ....
  resolve: {
    ...
    alias,
  },
}

```


And look into that project, I know this is not cool, and will fix this some time later

**Comment by geritol** [comment]
strange issue using draggable: I cannot interact with the marker content.
(like focus a div, type in a form)

![draggable](https://cloud.githubusercontent.com/assets/5496681/14254662/0c0cdd82-fa91-11e5-81a4-abf865690ac3.gif)

**Comment by istarkov** [comment]
Looks like google sets `pointer-events: none` on some of map divs or place invisible layer over your control, 
The first can be fixed just setting pointer-events: all on your control in css, the second setting `pointer-events: none` on that invisible layer. 
Try it, then read google docs if not help.

**Comment by geritol** [comment]
could not found anything added over or added css.
I simply solved it by focusing it.

**Comment by eyaleizenberg** [comment]
2024 update: `draggable` is deprecated. Instead pass `gestureHandling: "none"`.
