### ISSUE TITLE
change options (map.setOptions?)

### ISSUE THREAD

**Issue by geritol** [istarkov/google-map-react#127]
Is there a way to use: map.setOptions({ }) or something equal (tryed to set options in state, then modify it, but it has no effect.)
Thanks!

**Comment by istarkov** [comment]
No, just for options I need like draggable, but looks like this is needed feature.

**Comment by Ibrasau** [comment]
I wonder, is that feature implemented now? I mean, how can I change mapOptions if map component had already been initialized and mounted? Haven't found anything about that in documentation. Thanks in advance.

**Comment by istarkov** [comment]
implemented
https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L281
