### ISSUE TITLE
replace es6-promise with core-js es6.promise

### ISSUE THREAD

**Issue by dapi** [istarkov/google-map-react#128]
Reasons:

1. `es6-promize` size is 30 Kb. `core-js s6.promise` is 10Kb
2. You (and everybody) use `babel`. And babel requires `core-js`. It is already in dependencies tree, just use it.

**Comment by dapi** [comment]
I think `lodash` can be replaced by `core-js` too

**Comment by istarkov** [comment]
Have you seen minified and gziped diff? All that code size does not matter.

**Comment by dapi** [comment]
When you make a big app with 800 external modules and every modules requires needless dependency  gzipping does not matter ;)

The half of size of this component is not necessary.

Look dependency graph here: http://webpack.github.io/analyse/#modules
Upload this file: https://gist.githubusercontent.com/dapi/cbda23f4eaa88681c7af61f370b522b3/raw/4addad142f91f856e4e583ecb2bbd498f72bbe72/google-map-react.son

**Comment by dapi** [comment]
If you don't mind I make a request

**Comment by istarkov** [comment]
If minified build of this library becomes smaller Ill accept PR.  At my tests in the past, core-js Promise was not the winner by this criteria.

**Comment by istarkov** [comment]
By minified I mean this https://github.com/istarkov/google-map-react/blob/master/package.json#L9
