### ISSUE TITLE
How should a PlacesService object be created?

### ISSUE THREAD

**Issue by michaeleekk** [istarkov/google-map-react#129]
Hi. I just come across of this project for doing Google Maps.
It's nice for most of the parts. But got a small question.

If we wanna create a PlacesService object, it will be like,
> const service = new google.maps.places.PlacesService(map)

And for most of examples, map is the object created by,
> const map = new google.maps.Map()

So, what will you do if in this situation?

**Comment by istarkov** [comment]
Two solution;
1) Get map object in [onGoogleApiLoaded](https://github.com/istarkov/google-map-react#ongoogleapiloaded-func)

But I prefer 2
2) You need to use the same map loader as `google-map-react`

```
import { googleMapLoader } from 'google-map-react';
// and use somethere
googleMapLoader(bootstrapURLKeys)
  .then((maps) =>
```

as map uses the same method, and it's result is memoized and garanteed to be singleton,
all will be fine.

Just don't forget that `bootstrapURLKeys` must be the same for services and map.

**Comment by istarkov** [comment]
3) You could write your custom loader - if will use interface like this
https://github.com/istarkov/google-map-react/blob/master/src/utils/loaders/google_map_loader.js
and you can pass loader as `googleMapLoader` prop to map element

**Comment by michaeleekk** [comment]
These are such a good idea! Thanks for advices!
