### ISSUE TITLE
Bower version?

### ISSUE THREAD

**Issue by tgoldenberg** [istarkov/google-map-react#13]
Hi, I would like to use this in a Rails project, in which case I would have to copy the source files into my vendors folder or user a Bower version via rails-assets.org. Would it be possible to provide a Bower version? When I tried to copy the source files into my Javascripts directory, it caused a bunch of errors. Suggestions welcome :)

**Comment by MozMorris** [comment]
I've taken a first stab at this over on the `umd-build` branch: https://github.com/istarkov/google-map-react/tree/umd-build

@istarkov thoughts?

You should be able to test this by installing with `bower install git://github.com/istarkov/google-map-react#umd-build`

I also noticed @tgoldenberg, that you've created a fork at https://github.com/tgoldenberg/google-map-react. As you're probably aware, your fork now shows up in the bower registry: http://bower.io/search/?q=google%20map%20react under the name `google-map-react`. This will probably cause a conflict if/when we merge `umd-build` into master.

**Comment by MozMorris** [comment]
Just pushed another commit modifying the exports. Here's a jsfiddle showing it working: https://jsfiddle.net/cro4bb6a/

@tgoldenberg I've not used react + rails + bower so I'm not sure how you consume the component, but hopefully that fiddle makes sense to you.

**Comment by istarkov** [comment]
@MozMorris  Your work is Great!!! 
Till now i think that it's nearly impossible to run this control on JSFiddle. 

PS:
 One thing i can't understand in last commit
```
export GoogleMap from './google_map.js';
export default from './google_map.js';
```
Why we need this?

**Comment by MozMorris** [comment]
We don't need it right now. I put that in there so that in future we could easily expand the API to include other components e.g. GoogleMarker.

I've removed for now and updated the jsfiddle: http://jsfiddle.net/mozmorris/cro4bb6a/2/

**Comment by istarkov** [comment]
I think we can merge it into master?
@tgoldenberg can u say this changes is enough for you?

**Comment by MozMorris** [comment]
Agreed but I think @tgoldenberg will need to [unregister](http://bower.io/docs/creating-packages/#unregister) the bower package before we can [register](http://bower.io/docs/creating-packages/#register) it again.

See http://bower.io/search/?q=google-map-react also.

**Comment by MozMorris** [comment]
Btw, I will merge this now and hopefully we can sort out the Bower registration later.

**Comment by istarkov** [comment]
Ok, Great!!! 
I've wrote to him at facebook also.

**Comment by MozMorris** [comment]
We just we an `npm publish` please @istarkov.

**Comment by istarkov** [comment]
@MozMorris one question can i return my great eye_test removing this `--ignore "__tests__"` here https://github.com/istarkov/google-map-react/blob/master/scripts/build.sh#L8 or it can cause some bower errors?

**Comment by istarkov** [comment]
Done, published https://www.npmjs.com/package/google-map-react

**Comment by MozMorris** [comment]
👍 Sure, they won't won't get included in the build.

**Comment by tgoldenberg** [comment]
Hi guys just saw this. I will unregistered ASAP. I was just fooling around to see if I could add a bower.json & register, but this is great news!

**Comment by tgoldenberg** [comment]
removed from Bower

**Comment by MozMorris** [comment]
Thanks, @tgoldenberg.

**Comment by tgoldenberg** [comment]
Thank you! @MozMorris
