### ISSUE TITLE
Validate Latitude

### ISSUE THREAD

**Issue by lustrousgorilla** [istarkov/google-map-react#131]
I just spent a long time tracking down a bug in a React application that ultimately resulted from a latitude of -110 being passed as a prop to one of the child elements of this component. The only indicator was a deprecation warning about mutating the style object - which led me to start debugging very, very far away from the actual problem. 

Adding a validation that throws an exception for any latitude that isn't > -90 and < 90 might save someone else a lot of time and frustration.

**Comment by istarkov** [comment]
In my coding style I prefer to validate user input only in situations which can cause serious errors.
Current situation does not cause any serious error. 
Incorrect lat causes that marker placed at top left corner as I think. 
IMHO it's on user to validate his data.
