### ISSUE TITLE
Sometimes markers are draggable (in demo example)

### ISSUE THREAD

**Issue by reactor81** [istarkov/google-map-react#132]
I'm looking at this example here: http://istarkov.github.io/google-map-react/map/main/

and sometimes when i load the map, the little marker icons are actually draggable. When I drag the icon - *all* the icons move, and the map does not move. Then, when I  end drag, the map moves, so everything falls back into proper place. This looks like buggy / incorrect behavior. 

However, sometimes when i load it, the icons are not draggable (great). 

Have you seen this / any ideas what might be happening? I'm on Chrome 49.0.2~

**Comment by istarkov** [comment]
;-) never seen such behavior, I will try to reproduce.

**Comment by reactor81** [comment]
I had it happen again just now. I am also trying to repro
