### ISSUE TITLE
using center and defaultCenter

### ISSUE THREAD

**Issue by geritol** [istarkov/google-map-react#135]
I am using default center prop to set the default center, and center prop (set to undefined by default) to center markers on click event.

When I change center prop, I get
'GoogleMap: defaultCenter prop changed. You can't change default props.'
The React inspector shows defaultCenter unchanged.

Am I doing something no right?
What is the proper usage?
Thanks!

**Comment by istarkov** [comment]
`==` is not the same as `===` 
As you understand  even for empty objects `{} === {}` is false,
in current lib as in many others equality is not deep equality but reference equality.

Also it's a bad idea to have defaultValue and value (The same for center)
In react 15 `React DOM now warns if you specify both value and defaultValue for an input.`
Please read about controllable and uncontrollable React components, or search issues here about.
