### ISSUE TITLE
Add support of React v15

### ISSUE THREAD

**Issue by pavelkozhin** [istarkov/google-map-react#136]
Hi,

Please add support of latest React v15.0.1. 
React v15 drops the support of deprecated top-level React.findDOMNode, etc. Please see the change log: https://github.com/facebook/react/blob/master/CHANGELOG.md

Currently seems google-map-react falls back to the React instead of using ReactDOM due to the conditions:
```javascript
if (_utilsReact_version.isReact14(_react2['default'])) { 
try {
    ReactDOM = require('react-dom');
  } catch (e) {
    ReactDOM = _react2['default'];
  }
} else {
  ReactDOM = _react2['default'];
}
```
Thank you,
Pavel

**Comment by istarkov** [comment]
Looks like you are using an outdated this library version. This check has gone a month ago.

**Comment by pavelkozhin** [comment]
Oh, my bad. Thanks for clarification!
