### ISSUE TITLE
Update peer dependences to support react@15.0.0 onwards

### ISSUE THREAD

**Issue by vineethawal** [istarkov/google-map-react#137]

**Comment by istarkov** [comment]
May be it will be a good idea to look inside package.json before writing issue?

**Comment by vineethawal** [comment]
@istarkov thank you for your quick response.
Are you talking about this? https://github.com/istarkov/google-map-react/blob/master/package.json#L39

**Comment by istarkov** [comment]
;-) yes, it must handle react 15

**Comment by vineethawal** [comment]
![screen shot 2016-04-13 at 12 37 29 pm](https://cloud.githubusercontent.com/assets/13637484/14485425/9bd98bce-0174-11e6-929b-036ec9a3abab.png)

I am not sure the suffix `-rc.1` will handle for react 15 versions

**Comment by istarkov** [comment]
what version of npm do u use?

**Comment by vineethawal** [comment]
its `npm  v2.14.7`

**Comment by istarkov** [comment]
outdated ;-) and has known issues with peerDeps.

**Comment by vineethawal** [comment]
oh. my bad.
Nice lib btw. thanx alot :)
