### ISSUE TITLE
Uncaught TypeError: type.toUpperCase is not a function

### ISSUE THREAD

**Issue by sdemjanenko** [istarkov/google-map-react#14]
I get this when adding: `<GoogleMap center={ [59.938043, 30.337157] } zoom={ 9 } />`

**Comment by istarkov** [comment]
stack trace?

**Comment by sdemjanenko** [comment]
```
autoGenerateWrapperClass @ vendor.bundle.js?mtime=1435513512:18110getComponentClassForElement @ vendor.bundle.js?mtime=1435513512:7329validatePropTypes @ vendor.bundle.js?mtime=1435513512:6335ReactElementValidator.createElement @ vendor.bundle.js?mtime=1435513512:6382
```
Its failing on `type.toUpperCase()` of
```javascript
function autoGenerateWrapperClass(type) {
  return ReactClass.createClass({
    tagName: type.toUpperCase(),
    render: function() {
      return new ReactElement(
        type,
        null,
        null,
        null,
        null,
        this.props
      );
    }
  });
}
```

```
JSON.stringify(type)
"{"propTypes":{},"defaultProps":{"hoverDistance":30,"debounced":true}}"
```

**Comment by istarkov** [comment]
It looks like your import with an error, can you provide full source file. And your package.json

**Comment by pilgrimtech** [comment]
Im having the exact issue- 
here is my Map Control (in jsx, which Markdown doesnt enjoy)
![image](https://cloud.githubusercontent.com/assets/5833470/8412653/29b1864a-1e59-11e5-81af-1e4bc47a39a4.png)

and my package.json file...
{
  "name": "energydashboardweb",
  "version": "0.0.0",
  "dependencies": {
    "chalk": "^1.0.0",
    "compress": "^0.99.0",
    "dateformat": "^1.0.11",
    "express": "^4.12.4",
    "flux": "^2.0.3",
    "google-map-react": "^0.3.3",
    "gulp-git": "^1.2.4",
    "gulp-load-utils": "0.0.4",
    "gulp-nodemon": "^2.0.3",
    "lodash": "^3.8.0",
    "moment": "^2.10.3",
    "react-bootstrap": "^0.22.4",
    "react-google-maps": "^1.7.0",
    "react-kendo": "^0.13.10",
    "react-pure-render": "^1.0.2",
    "react-radio": "^1.0.6",
    "react-radio-group": "^2.0.2",
    "react-router": "^0.13.3",
    "superagent": "^1.2.0"
  },
  "devDependencies": {
    "browser-sync": "latest",
    "browserify-shim": "^3.8.0",
    "del": "~0.1.3",
    "gulp": "~3.8.8",
    "gulp-autoprefixer": "~1.0.1",
    "gulp-bower": "0.0.6",
    "gulp-cache": "~0.2.4",
    "gulp-git": "^1.2.4",
    "gulp-imagemin": "latest",
    "gulp-jade": "~0.8.0",
    "gulp-jest": "~0.2.2",
    "gulp-jshint": "~1.8.5",
    "gulp-load-plugins": "~0.7.0",
    "gulp-react": "^3.0.1",
    "gulp-ruby-sass": "~0.7.1",
    "gulp-run": "^1.6.8",
    "gulp-size": "~1.1.0",
    "gulp-strip-debug": "^1.0.2",
    "gulp-stylus": "~2.0.1",
    "gulp-uglify": "^1.0.2",
    "gulp-useref": "~0.4.4",
    "gulp-util": "~3.0.1",
    "gulp-webserver": "latest",
    "jest-cli": "^0.4.3",
    "main-bower-files": "~2.6.2",
    "react": "latest",
    "react-tools": "latest",
    "reactify": "latest",
    "strip-debug": "^1.0.1",
    "vinyl-source-stream": "^1.0.0",
    "watchify": "~2.1"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "jest",
    "start": "node dist/server.js"
  },
  "jest": {
    "scriptPreprocessor": "<rootDir>/preprocessor.js",
    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react"
    ]
  },
  "browserify": {
    "extension": [
      "jsx"
    ],
    "transform": [
      "browserify-shim",
      [
        "reactify",
        {
          "es6": true
        }
      ]
    ]
  },
  "browser": {
    "jquery": "./app/bower_components/jquery/dist/jquery.js"
  },
  "browserify-shim": {
    "jquery": "$"
  }
}

**Comment by istarkov** [comment]
Please have a look here http://jsfiddle.net/mozmorris/cro4bb6a/2/
I see one error in your code center must be is an array. 
But i think i must also support center as lat lng object so i'll add this to issue list right now.

**Comment by sdemjanenko** [comment]
In my case `center` is an array.  Also type is defined.  It looks like it is a React component.  Its just that `toUpperCase` is not a function on the object.

**Comment by MozMorris** [comment]
@sdemjanenko can you perhaps create a repos so we can better debug the problem?

**Comment by MozMorris** [comment]
...and @pilgrimtech too please.

**Comment by istarkov** [comment]
@sdemjanenko in code you provide center prop is not an array

**Comment by pilgrimtech** [comment]
I sanitized my solution, placed it here: https://github.com/pilgrimtech/Google-Map-React-Test

after an npm install in the directory, gulp watch will run the app on localhost:3000. The exception is thrown there.

**Comment by MozMorris** [comment]
Unfortunately the `gulp watch` & `bower install` throw a couple of errors. Can you do a fresh clone and check your `gulpfile`.

1. Bower is complaining about https://bower.telerik.com/bower-kendo-ui.git#~2014.3.1425 which I'm guessing is private?

2. Gulp is complaining about `./dist/server.js` missing.

    [19:56:35] [nodemon] starting `node dist/server.js`
    module.js:338
        throw err;
              ^
    Error: Cannot find module '/Users/Moz/Sites/Git/Google-Map-React-Test/dist/server.js'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    [19:56:35] [nodemon] app crashed - waiting for file changes before starting...

**Comment by MozMorris** [comment]
@pilgrimtech just found this was a bug in the library. But we've already fixed it in e4505e2a6b560cb3e061d5d542b8bfff5fa5c3d3 

If you upgrade to `0.4.0` in your `package.json` the problem should go away.

`"google-map-react": "^0.4.0"`

**Comment by MozMorris** [comment]
@sdemjanenko upgrading should also fix it for you.

**Comment by sdemjanenko** [comment]
@MozMorris Sweet, that fixed it.  Thanks!

**Comment by istarkov** [comment]
@MozMorris is this error depends on difference between `export *` and `export default`?
I thought that for this situation it almost the same commands.

**Comment by MozMorris** [comment]
These two sections explain it better than I ever could 😀

1. http://www.2ality.com/2014/09/es6-modules-final.html#default_exports_%28one_per_module%29
2. http://www.2ality.com/2014/09/es6-modules-final.html#re-exporting

Essentially, the problem could easily have been fixed by using `var {GoogleMapReact} = require('google-map-react');`. The `export default` allows us to just use `var GoogleMapReact = require('google-map-react');`

**Comment by istarkov** [comment]
Re-exporting means adding *another module’s exports* to those of the current module. You can either add all of the other module’s exports:
```
    export * from 'src/other_module';
```
I've read that, and `export *` work as expected for es6 modules, but not for `require`

**Comment by MozMorris** [comment]
👍

**Comment by DVLP** [comment]
I just had this error because at the end of one module this line was missing:

    module.exports = ModuleNameHere;
