### ISSUE TITLE
Clicking on overlay doesn't prevent click to google POI

### ISSUE THREAD

**Issue by umyeah** [istarkov/google-map-react#140]
You can see this in your main example http://istarkov.github.io/google-map-react/map/main/

If you click on a marker or info bubble that is on top of a google POI (town name or train station), the POIT info bubble will popup as well. Is there any way to prevent this? I have tried stopPropagation/preventDefault with no luck. Any ideas why this may be happening?

**Comment by istarkov** [comment]
Pleas read google documentation or just use search, there are must be an option to disable internal POIs. 

For example:
http://stackoverflow.com/questions/7478069/disable-point-of-interest-information-window-using-google-maps-api-v3

http://stackoverflow.com/questions/7538444/how-do-i-remove-default-markers

I use map in a lot of projects and never had this issue from customers, it looks like it's not so easy to click on marker and on POI.

For example on example - on which marker you should click to get google tooltip?

**Comment by umyeah** [comment]
Thanks for your help and quick response!

Yes this is definitely an edge case and disabling POIs is one option although I would prefer not to have to. As an example, it will depend on zoom level but Mckenzie-Waelchi over Frunzenskaya is what I tested with.

Do you have any thoughts on using the floatPane instead of the overlayMouseTarget?

**Comment by istarkov** [comment]
> Do you have any thoughts on using the floatPane instead of the overlayMouseTarget?

Looks like pane I selected based on `copy-paste` from somewhere ;-) So I can't say much ;-) about.

I'll accept PR where pane can be set via some prop.
