### ISSUE TITLE
How to manually set marker zindex?

### ISSUE THREAD

**Issue by clearmirror** [istarkov/google-map-react#141]
With google api, a marker object has a function setZIndex. Is there a way for me to access the marker object when I put react components as children inside <GoogleMap>

I also notice that on the main example (http://istarkov.github.io/google-map-react/map/main/) when a marker is hover the marker is brought to the top, which is exactly what I want. I can't find the code that calls setZIndex so can anyone show me how I can achieve it?

**Comment by istarkov** [comment]
It's not a google markers, just react components, so you can change z-index using css

**Comment by clearmirror** [comment]
oh I always thought it would convert them into marker lol.. thanks for the help!

**Comment by talyh** [comment]
I don't think this is still true. Currently the provided marker component is wrapped by a `div`, and that's the element that would need the `z-index`. Setting `z-index` in elements inside that div, doesn't seem to interfere with their stacking display.
