### ISSUE TITLE
Tap instead of hover on mobile

### ISSUE THREAD

**Issue by yotamDvir** [istarkov/google-map-react#145]
Considering using this library, looks great! One problem...

On my mobile, I tried tapping on the markers [in the examples](http://istarkov.github.io/google-map-react/map/events), but it doesn't seem to replicate the same action that would activate upon hovering on the PC (more accurately, it does nothing at all).

Not sure if this is supposed to work or not, but I couldn't figure this out from the documentation.

By the way, using Chrome on Android if relevant.

**Comment by istarkov** [comment]
Hovering is impossible on mobile, and there are no click action in this example. So it does not show anything on mobile.

**Comment by yotamDvir** [comment]
OK I thought hovering would translate to tapping on mobile, and I understand that it's possible to add tap events, just doesn't appear in the examples.
