### ISSUE TITLE
Minimum zoom

### ISSUE THREAD

**Issue by bruno12mota** [istarkov/google-map-react#146]
Hey! great job with the lib.

Trying to set the minimum zoom to a value on the map options, and I see you're ignoring it:

```js
const minZoom = this._getMinZoom();
this.minZoom_ = minZoom;
```

Shouldn't this try to fetch the min zoom from the options, and default to the getMinZoom function? Like this:

```js
const minZoom = options.minZoom || this._getMinZoom();
this.minZoom_ = minZoom;
```

Cheers

**Comment by istarkov** [comment]
As I know, I do not ignore it, just dont allow to set minZoom less than some calculated level.  Details are here https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L295

**Comment by bruno12mota** [comment]
Not familiar with the zooming restraints on google maps 😅  although I'm not being able to achieve a full map view (with all countries showing up), which is quite crucial in my case.

![screen shot 2016-04-26 at 1 35 15 pm](https://cloud.githubusercontent.com/assets/4086031/14818204/bc0a572c-0bb3-11e6-8948-1c386332d4d9.png)

**Comment by istarkov** [comment]
It is not a gmap restraints. With big map sizes and small zoom it is possible that you get for example two or more Usa (or any other country) on the map. So where to show marker if it has two view position. I dont know. Showing marker in all positions - make some internal computations more complex. So I decieded to restrict minZoom level as I have no tasks where I need full map on the screen.

**Comment by thunderkid** [comment]
I have the same issue. Sometimes I need to show the whole world. Probably the ideal is to show a copy of the marker at each position - but even if I could only show a single copy of the marker, it would be better than nothing. Perhaps an ignore-minimum-zoom flag would be useful for some people. (I'm thinking about how to build a many->one mapper, but as you say, it's more complex.)

**Comment by istarkov** [comment]
This guy does not answer https://github.com/istarkov/google-map-react/pull/118
So u could make your PR

**Comment by istarkov** [comment]
Will accept PR like #118 with changes I wrote

**Comment by deviantony** [comment]
Yeah, I need to display the whole world too. This makes a no-go for this component (at the moment), will check again later.
