### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by istarkov** [istarkov/google-map-react#147]
- [ ] Add width height and create example of how to use AutoSizer from react-virtualized https://github.com/istarkov/google-map-react/issues/124#issuecomment-214830421

**Comment by RUPOJS** [comment]
Hi @istarkov I am trying to create a PR for this issue/enhancement. I have integrated https://github.com/sdecima/javascript-detect-element-resize (I reckon AutoSizer also uses it internally) in 'google-map-react' and I am able to pass callbacks when resize is happening. Now, I have a small doubt shall I call initMap or onWindowResize as a callback to the resize event or shall I write a new callback method for this. Feedback/Suggestions will be much appreciated.

Regards,
Rupesh
