### ISSUE TITLE
Support for streetViewControl?

### ISSUE THREAD

**Issue by Ajar-Ajar** [istarkov/google-map-react#148]
Hi there, Awesome component and examples!
Does this component support Google Street View?
I've noticed in the code you have a default value of false to the streetViewControl flag.
I've set it to true and nothing really changed.
Is it suppose to show the controller? is it on your road-map?
Cheers
Ajar

**Comment by rfriberg** [comment]
@Ajar-Ajar - you can pass that in via the `options` prop: 
`<GoogleMapReact  options={{streetViewControl:true}} />`  

That will enable the street view "pegman".

**Comment by Ajar-Ajar** [comment]
Thanks!!
:)
