### ISSUE TITLE
Drawing routes

### ISSUE THREAD

**Issue by riourbana** [istarkov/google-map-react#149]
Hi,
is there a way to draw a route between two markers inside the map component?

**Comment by metalsushi** [comment]
Is there a way to draw polylines?

**Comment by worldlyjohn** [comment]
+bump

**Comment by istarkov** [comment]
You could draw svg in your React components or use GMap api.
I use svgs.
![mape](https://cloud.githubusercontent.com/assets/5077042/16172079/afd30cca-3588-11e6-90ed-53794910ae62.gif)

**Comment by mkontula** [comment]
So do you basically use an svg as a marker? How do you do the scaling?

**Comment by istarkov** [comment]
@mkontula 
1 redraw
2 css hacks to prevent borders to be thinker-thinner until polygons on new zoom drawed

**Comment by mmoutenot** [comment]
@istarkov would you add the above or something similar as an example?

**Comment by istarkov** [comment]
@mmoutenot not sure, as in current realization it needs server support with at least 1Gb mem for polygon tiling and simplification algorithms. I don't want to pay money to support just an example.

**Comment by mmoutenot** [comment]
@istarkov what about a non-deployed code example?

**Comment by mmoutenot** [comment]
great library, by the way. I'm using polygons via the maps api for now but would be interested how you did the svgs.

![image](https://cloud.githubusercontent.com/assets/339996/16749414/fe96c06a-4797-11e6-8443-78ebaf2ac726.png)

**Comment by istarkov** [comment]
Code without working example causes a lot of issues like - 'not work, cant
run, blabla' I think every visual component should have working example.

**Comment by istarkov** [comment]
In short svg realization works as:
Split geojson on tiles https://github.com/mapbox/geojson-vt
Having tiles, draw each tile as marker
Some logic on hovers - as one polygon can be on different tiles.
Optimizations - optimizations - optimizations.

**Comment by mkontula** [comment]
@mmoutenot Easiest solution I found is to use Google Maps' Data Layer documented quite well here: https://developers.google.com/maps/documentation/javascript/datalayer. To use the `DataLayer`, you need to have access to `map` object. The library gives you that in `onGoogleApiLoaded` callback. On that callback, store the reference to map object in module level variable or your hosting components state. I chose the module level, which works just fine. Then you can have a custom `drawMyGeoJson` method in your component and do whatever you like with map object, which exposes the complete Google Maps API. Call this custom method in your components' render().

If you have KML, convert those to GeoJson features with https://github.com/mapbox/togeojson. KML is tricky imho, since it's locked to constant styles IN the KML document, which isn't quite dynamic. I can post a code sample later on if needed.

**Comment by snakeyak** [comment]
@mkontula I'm struggling with this, could you please post a sample code?

**Comment by finetype** [comment]
@mkontula, code example would be great. I think I can follow that, but it's always faster to have something to look at.

**Comment by snakeyak** [comment]
@finetype I've since managed this, using the internal Google Maps API.

1. Save Map and Maps reference to state
```
import GoogleMap from 'google-map-react' 

<GoogleMap
          ....
          onGoogleApiLoaded={({ map, maps }) => { this.setState({ map: map, maps:maps, mapLoaded: true }) }}
          yesIWantToUseGoogleMapApiInternals
        >
```

2. Add the polyline component right after the map component, passing map and maps
```
 <GoogleMap
        ...
        </GoogleMap>
        { this.state.mapLoaded && <Polyline map={this.state.map} maps={this.state.maps} /> }
```

3. The path component can use the standard Google Maps API via those props, e.g.
```
class Polyline extends PureComponent {

  componentWillUpdate() {
    this.line.setMap(null)
  }

  componentWillUnmount() {
    this.line.setMap(null)
  }

  getPaths() {
    const { origin, destination } = this.props

    return [
      { lat: Number(origin.lat), lng: Number(origin.long) },
      { lat: Number(destination.lat), lng: Number(destination.long) }
    ];
  }

  render() {
    const Polyline = this.props.maps.Polyline

    const renderedPolyline = this.renderPolyline()
    const paths = { path: this.getPaths() }

    this.line = new Polyline(Object.assign({}, renderedPolyline, paths))

    this.line.setMap(this.props.map)

    return null
  }

  renderPolyline() {
    throw new Error('Implement renderPolyline method')
  }

}



class Normal extends Polyline {

  renderPolyline() {
    return {
      geodesic: true,
      strokeColor: this.props.color || '#ffffff',
      strokeOpacity: 1,
      strokeWeight: 4
    }
  }
}
```

Hope this helps

**Comment by mborseparagyte** [comment]
@snakeyak Thanks for the help!

**Comment by samwest7** [comment]
Was anyone able to  successfully import a KML file into their map?

**Comment by TechSaq** [comment]
I solved this by leveraging the use of Google Javascripts Map API.

1. Use the objects provided by `onGoogleApiLoaded`
```
<GoogleMapReact
  ...
 onGoogleApiLoaded={({ map, maps }) => setMap(map); setMaps(maps); setIsMapLoaded(true) }
/>
```

2. Use these objects to make use native Google Javascripts Map API.
It takes an array of latlang to draw path.
```
map.data.add({
   geometry: new maps.Data.LineString([
            { lat: -32.364, lng: 153.207 },
            { lat: -35.364, lng: 153.207 },
            { lat: -35.364, lng: 158.207 },
            { lat: -33.364, lng: 159.207 },
        ])
})
```
_maps.Data basically creates a Data Layer where we can draw
It has Point, LineString, Polygon etc. to draw different shapes.
For line we need LineString and for making triangle, rectangles etc we can use Polygon class._

For more details:
https://developers.google.com/maps/documentation/javascript/examples/layer-data-polygon?hl=en
https://developers.google.com/maps/documentation/javascript/reference/data#Data.LineString
