### ISSUE TITLE
map size change does not trigger onChange?

### ISSUE THREAD

**Issue by geritol** [istarkov/google-map-react#151]
just put together a dumb demo.
if you click the marker, the map is resized.
the onChange does not seem to triger.
I should console.log the size.
(I wndow resize resizes the map it seems to work)

Is this expected behaviour?

https://jsbin.com/zaxemotiwu/edit?js,console,output

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/issues/147
