### ISSUE TITLE
Map not rendering

### ISSUE THREAD

**Issue by diegoaguilar** [istarkov/google-map-react#155]
I got following JSX:

```
<div>
  <GoogleMap
   center={{lat: 59.938043, lng: 30.337157}}
   zoom={9}>
  </GoogleMap>
</div>
```

I've imported the library this way:

`import GoogleMap from 'google-map-react';`

But I'm getting nothing rendered, what else should I setup?

**Comment by istarkov** [comment]
Having zero height div what are you want to view on the screen?

**Comment by ryuker16** [comment]
You need to specify height and width of the container it appends google map too.

By default, height/width is not set for the google maps element inserted into the page.

**Comment by vasco** [comment]
Please someone document this in the README ASAP! I lost 4h+ today with this issue!

Thank you so much for the solution!

**Comment by istarkov** [comment]
@vasco It's opensource project you can document anything you need.
BTW just read documentation carefully https://github.com/istarkov/google-map-react#my-map-doesnt-appear
```
Make sure the container element has width and height. The map will try to fill the parent container, but if the container has no size, the map will collapse to 0 width / height.
```

**Comment by vasco** [comment]
@istarkov you're absolutely right! Thank you once again.
