### ISSUE TITLE
shouldComponentUpdate issue

### ISSUE THREAD

**Issue by be-codified** [istarkov/google-map-react#156]
Hi, thank you for the great component. I am using ES6 and trying to use shouldComponentUpdate but I don't know how. Should this be done in constructor? What is this lib doing?

Please see my code.

    import React, { Component, PropTypes } from 'react';
    // import shouldPureComponentUpdate from 'react-pure-render/function';

    import { customMarkerStyle } from './customMarkerStyle.js';

    class CustomMarker extends Component {
        // shouldComponentUpdate = shouldPureComponentUpdate;

        render() {
            return (
                <div style={customMarkerStyle}>
                    {this.props.text}
                </div>
            );
        }
    }

    CustomMarker.propTypes = {
        text: PropTypes.string
    };

    CustomMarker.defaultProps = {};

    export default CustomMarker;

**Comment by raulmatei** [comment]
Hi,

If you don't want to use class fields (https://github.com/jeffmo/es-class-fields-and-static-properties) you can add the method to the class prototype:

```js
CustomMarker.prototype.shouldComponentUpdate = shouldPureComponentUpdate;
```

**Comment by istarkov** [comment]
Or use HOCs https://github.com/istarkov/google-map-react/blob/master/develop/markers/ClusterMarker.js#L51
