### ISSUE TITLE
onMouseEnter event fired multiple times in Bubble

### ISSUE THREAD

**Issue by nicholasray** [istarkov/google-map-react#157]
You can replicate this behavior by putting a console log in the onMouseEnterContent handler here:

https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_main/marker_example.jsx#L107-L109

When you run this example and the mouse enters the bubble, you can see that the event is fired multiple times. Why is this? Is this a bug?

**Comment by istarkov** [comment]
Not a bug, expected behavior

**Comment by nicholasray** [comment]
@istarkov thank you for your reply. Excuse my ignorance, but can you please explain why this is expected behavior?

**Comment by pts-ccontreras** [comment]
Hi @istarkov @nicholasray I ran into this issue, MouseEntered is being fired multiple times. Is there a reason why this behaviour is expected?
