### ISSUE TITLE
contains method for LatLngBounds class

### ISSUE THREAD

**Issue by evgenTraytyak** [istarkov/google-map-react#158]
@istarkov what do you think about `.contains()` method for `LatLngBounds`(https://github.com/istarkov/google-map-react/blob/master/src/utils/lib_geo/lat_lng_bounds.js) class.
Like this: https://developers.google.com/maps/documentation/javascript/reference#LatLngBounds

**Comment by istarkov** [comment]
Is it exposed in public api?

**Comment by evgenTraytyak** [comment]
@istarkov no

**Comment by evgenTraytyak** [comment]
@istarkov maybe this lib has some method to check that bounds contain specific coordinates (marker)?

**Comment by evgenTraytyak** [comment]
@istarkov `Leaflet` has this method in public api - https://github.com/Leaflet/Leaflet/blob/87eee7fbcbcc8f0794b9d5e9bb0c69434456e451/src/geo/LatLngBounds.js#L44

**Comment by istarkov** [comment]
BTW this lib uses this class internaly, what the need to expose it as public api? For your needs you could use Leaflet or any other libraries - turf, etc.

For now I think that even current public is to big, and want to shrink a lot of props in order to simplify it ;-)

**Comment by evgenTraytyak** [comment]
@istarkov ok, i got it. How can i convert `bounds` argument `{ nw: Object, se: Object }` from `onChange` method for `google.maps.LatLngBounds(sw?:LatLng | LatLngLiteral, ne?:LatLng | LatLngLiteral)` https://developers.google.com/maps/documentation/javascript/reference#LatLngBounds

`{ nw: Object, se: Object }` -> `{ sw: Object, ne: Object }`

**Comment by istarkov** [comment]
My fault with corners ;-) incompatibility with GMap API

It's a simple math, how to from two rectangle corners get other two. Just write a rectangle on a paper ;-)

**Comment by evgenTraytyak** [comment]
@istarkov ok, thanks.

i just drop it here 😄 :

```js
   handleChange({ center, zoom, bounds, marginBounds }) {
       bounds.sw = { lat: bounds.se.lat, lng: bounds.nw.lng };
       bounds.ne = { lat: bounds.nw.lat, lng: bounds.se.lng };
    
       const googleLatLngBounds = new google.maps.LatLngBounds(bounds.sw, bounds.ne);

       googleLatLngBounds.contains({ lat: Number, lng: Number }); // boolean
   }

```

**Comment by evgenTraytyak** [comment]
@istarkov you can close this issue

**Comment by istarkov** [comment]
To simplify your code, you could create a PR for this lib, which will add `sw` `ne` for bounds ;-)

**Comment by evgenTraytyak** [comment]
@istarkov i'll do it when I'll have time 👍
