### ISSUE TITLE
get map bounds in the end of zoom

### ISSUE THREAD

**Issue by evgenTraytyak** [istarkov/google-map-react#159]
@istarkov how i can get map bounds in the end of zoom animation? in `handleZoomAnimationEnd` handler

**Comment by istarkov** [comment]
The problem that you does not hold `onChange` data in your component, or at the moment of `onZoomAnimationEnd` this data is outdated?

```
_onChange({bounds}) {
  this._bounds = bounds; // is it outdated?
}
```

**Comment by evgenTraytyak** [comment]
@istarkov in `onChange` I has bounds like in `onZoomAnimationStart`stage. But I need bounds like for `onZoomAnimationEnd` stage, when zoom was changed.

```

**Comment by istarkov** [comment]
Please look 
https://jsbin.com/zazecefiri/edit?js,console,output

As I see bounds different for start and end phases
![image](https://cloud.githubusercontent.com/assets/5077042/15603263/5ea00642-2402-11e6-9caf-f595b6dc5cfb.png)

**Comment by evgenTraytyak** [comment]
@istarkov hmm, it works on `jsbin`, but i have the same bounds in `onChange` and `onZoomAnimationEnd`
