### ISSUE TITLE
Standart marker style

### ISSUE THREAD

**Issue by NazariiStrohush** [istarkov/google-map-react#161]
How i can set default marker style like in maps.google.com? 
![Marker](http://ignitordigital.com/wp-content/uploads/2013/10/map-pin1-183x300.png)

**Comment by istarkov** [comment]
There are no markers in this library. As it said in the [README](https://github.com/istarkov/google-map-react) *It allows you to render any React component on the Google Map.*
So markers is your React components. 
Please read documentation and examples.

**Comment by NazariiStrohush** [comment]
Thank you now I finally realized :)
