### ISSUE TITLE
Add custom control to map

### ISSUE THREAD

**Issue by khmelevskii** [istarkov/google-map-react#165]
How can I access to `map.controls` and push new element into Google Map?
https://developers.google.com/maps/documentation/javascript/controls#CustomPositioning

**Comment by istarkov** [comment]
Please write exactly what you want, as there is a lot of information on your ref. Also be sure that you have an access to any google api props, aso just read an google api and documentation and issues of this library.

**Comment by khmelevskii** [comment]
I solved the problem. Thanks

**Comment by DeBaum** [comment]
I ran into the same problem. Can you tell us _how_ you solved the problem?

**Comment by DeBaum** [comment]
If someone stumbles across this, here is the solution:
Use the [onGoogleApiLoaded(map, maps)] (https://github.com/istarkov/google-map-react/tree/27cf164beacb78a5b4111ae6a645a83c61377d09#ongoogleapiloaded-func) callback to get the map-object.
