### ISSUE TITLE
How do I draw a transparent circle on the map?

### ISSUE THREAD

**Issue by EdwardDrapkin** [istarkov/google-map-react#167]
Hey there, I'm trying to add a transparent circle around a point on the map.

Here's what I'm doing:

                new google.maps.Circle({      
                    strokeColor: '#000000',  
                    strokeOpacity: 0.8,
                    strokeWeight: 2,
                    fillColor: '#FF0000',
                    fillOpacity: 0.35,
                    map: this.refs.gmap.map_,
                    center: center,
                    radius: this.state.pinRadius
                });

The circle renders, but it doesn't render with the correct opacity.  

EDIT: nevermind, i was rendering it in a loop by accident... oops

**Comment by jabidof** [comment]
Hi, I have the same need, i.e. drawing **polygons ([Lats/Lngs...])** and or **circles (Lat/Lng + radius)** on the Map. Any chance to have this integrated within google-map-react?

Thanks for your feedback
