### ISSUE TITLE
Wrong Calculation on Zoom Out

### ISSUE THREAD

**Issue by raphaguasta** [istarkov/google-map-react#168]
Hi!

I liked very much this plugins. Congratulations and thanks!

I really want to use this in my application, but I have a problem.

When I decrease the zoom, the positions of my Markers are wrong:

**Initial position:**
![screen shot 2016-06-10 at 11 46 49 am](https://cloud.githubusercontent.com/assets/6708227/15968116/fdfca278-2f00-11e6-8684-6d7e3ffb2b02.png)

**Position on zoom out (my mark goes to ocean):**
![screen shot 2016-06-10 at 11 54 02 am](https://cloud.githubusercontent.com/assets/6708227/15968246/81c5567c-2f01-11e6-930f-4cbe16699a40.png)

**My component code:**
```
<GoogleMap
  bootstrapURLKeys={{ key: 'XXX' }}
  defaultCenter={myPosition}
  center={myPosition}
  defaultZoom={15}>
      <UserPin {...myPosition} />
 </GoogleMap>
```

I forgot some configuration or it's a bug? Someone can help me?

Thanks!

**Comment by istarkov** [comment]
It's better to use map as controllable component as in this example https://jsbin.com/lepadusowo/edit?js,console,output

And if you will use the same coords for center and for pin, you will got that pin will always be placed on the map center. And not at the coordinate you want

**Comment by raphaguasta** [comment]
Hi @istarkov 

I modified my code, but nothing has changed:

`handleChangeMap=({center, zoom})=>{
    this.setState({
      center: center,
      zoom: zoom
    });
  }

  renderMap = ()=> {
    return (
      <GoogleMap
        bootstrapURLKeys={{ key: 'XXX' }}
        onChange={this.handleChangeMap}
        center={this.state.center}
        zoom={this.state.zoom} >
        <UserPin lat={this.state.myPosition.lat} lng={this.state.myPosition.lng} />
      </GoogleMap>
    )
  }`

Do you have another idea?

Thanks agains!

**Comment by istarkov** [comment]
Please add your code on jsbin, as example I provide in previous comment works as expected

**Comment by raphaguasta** [comment]
I tested by your example, and i discovered that my SVG icon was the problem, he had a transparency.

Thanks a lot!!!

**Comment by lauterry** [comment]
Hi @raphaguasta 

What have you done about you svg icon to solve the issue ?

Best regards

**Comment by GingerBear** [comment]
for anyone who havs the same issue, the problem is that the custom marker is anchored at top left of the marker, but we actually want for marker to anchor is usually at center bottom. The fix would be adding a negative marginTop and marginLeft to adjust the anchor.

**Comment by Suresh-R-S** [comment]
Hi,

I'am having the same issue. @GingerBear 's answer is not working for me. Any other workarounds?

**Comment by itsmichaeldiego** [comment]
@Suresh-R-S You just need to use `transform: translate(-50%, -50%)` and that will do

**Comment by raphaguasta** [comment]
@GingerBear is right!!

**Comment by IhsanMujdeci** [comment]
@itsmichaeldiego perfect fix :)

**Comment by itsmichaeldiego** [comment]
@IhsanMujdeci Glad it worked!

**Comment by DeekshaPandit** [comment]
> @Suresh-R-S You just need to use `transform: translate(-50%, -50%)` and that will do

Do you have jsbin running for this code?, please share. Thanks in advance.

**Comment by seyaobey** [comment]
I am reopening this issue hoping that I can find some help. I'm facing the same issue. 
`"google-map-react": "^1.1.7"`
Especially when I'm zooming out, the icon goes far from its original position:
The pin below is at the center of Brussels. But you can see that when I zoom out, at the level where I am, the pin is way to the left of the city. But if I zoom in enough then recenters.
What should I do to keep my pin at its initial position>?
I have tried all the above solutions, nothing is working. I really like this plugin. I have been using `leaflet maps` so far. I would like to use this plugin. Thank you for your help

![image](https://user-images.githubusercontent.com/2738569/77258191-443e5600-6c79-11ea-83ad-807b0f152075.png)

**Comment by wahlforss** [comment]
@seyaobey I'm having the same issue. Did you solve it?

**Comment by binarytrance** [comment]
For anybody still having this issue, in my case, I had a custom svg made by me using svg code. (I converted it into a data URI and passed it into my map). The svg tag didn't have a width and height explicitly defined. I had a `rect` tag which did have a width and height. What happened was that when this svg was rendered on the map, a different, larger width and height were added to the image and it's surrounding container, and the svg image itself was positioned to the top left corner of the oversized container.

SOLUTION: Adding an explicit width and height to the svg tag fixed the issue.

The `image` tag and the container no longer took a larger sized than the svg image itself.

**Comment by jolker** [comment]
> > @Suresh-R-S You just need to use `transform: translate(-50%, -50%)` and that will do
> 
> Do you have jsbin running for this code?, please share. Thanks in advance.

hi bro, how i can add css `transform: translate(-50%, -50%)`

**Comment by rickli1989** [comment]
> > > @Suresh-R-S You just need to use `transform: translate(-50%, -50%)` and that will do
> > 
> > 
> > Do you have jsbin running for this code?, please share. Thanks in advance.
> 
> hi bro, how i can add css `transform: translate(-50%, -50%)`

const CustomMarker = () => (
		<RoomOutlinedIcon style={{ transform: 'translate(-50%, -50%)' }} color="primary" fontSize="large" />
	);

**Comment by itsmichaeldiego** [comment]
@seyaobey You just need to add the following css property:
```transform: translateX(-50%)```

**Comment by itsmichaeldiego** [comment]
@seyaobey You just need to add the following css property:
```transform: translateX(-50%)```

Default position for the marker is bottom-left, if you want to move it, you should change one of the axis, in your case you want to set it in bottom-center, so you just need to change the X asis.

If you want it to point top-left, then you change the Y axis, if you want it in the center you change both, and so on.

Does it makes sense?

Take a look at [this code in google-map-react-examples](https://github.com/google-map-react/google-map-react-examples/blob/master/src/components/Marker.js#L15)

CC  @jolker @wahlforss @DeekshaPandit

**Comment by ziaulrehman40** [comment]
One thing which wasted lots of my time was to add margins of inner SVG, i had wrapping divs for some text placement on custom pointers, and adding margins on those wrapping divs caused weird issues of pointer placements. When i moved negative margins to inner most SVG and p tag of the text separately, issue was fixed

**Comment by petrok1995** [comment]
The zoom out is fine, the reason that it seams that your marker is moving is that it's "centred" around the top left corner of your marker icon, make the css for your icon position relative, set a top margin that equals the height of your icon and a left margin that equals half it's width and it'll do fine
