### ISSUE TITLE
jsFiddle with more advanced examples

### ISSUE THREAD

**Issue by tgoldenberg** [istarkov/google-map-react#17]
For @MozMorris, 

Would it be possible to put up a jsFiddle with the more advanced examples? I am trying to go through the example source code and finding it difficult to transfer to the var Map = React.createClass({}), etc. syntax. 

I got the first simple example working, but I am confused about the absolute positioning of the marker in the top left corner of the map. Could not get the marker to render anywhere except the top left corner :/. 

Appreciate the help!

**Comment by MozMorris** [comment]
Hello, I'm currently in Paris at React Europe but I'll see what I can do when I return to the UK.

**Comment by MozMorris** [comment]
@tgoldenberg this fiddle shows the simple example with markers...

http://jsfiddle.net/mozmorris/cvju3p2v/1/

**Comment by tgoldenberg** [comment]
Thank you @MozMorris :)
