### ISSUE TITLE
How to use regular Google Maps Markers?

### ISSUE THREAD

**Issue by joshuajung** [istarkov/google-map-react#173]
I understand and appreciate your decision to enable customized React markers. However, in certain occasions it may be helpful to rely on the standard Google Maps markers. Is there an easy way to use them? Is there a "mapHasLoaded" event that provides the original Google Maps component and enables me to amend it?
Thanks for your effort and support.

**Comment by istarkov** [comment]
Yes there is event available, please look docs (Im from mobile phone)

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react#ongoogleapiloaded-func

**Comment by joshuajung** [comment]
Perfect, sorry for being blind. Works great!

**Comment by mikebski** [comment]
Here's an updated link to the docs -> https://github.com/istarkov/google-map-react/blob/956c0ca5d2b9aeb33ef2693a5e43801385ded7cb/API.md
