### ISSUE TITLE
request/ask: change size of map marker based on zoom level

### ISSUE THREAD

**Issue by worldlyjohn** [istarkov/google-map-react#175]
I recall working with the Google Maps API a while back and being to make marker adjustments (show/hide) based on zoom level.

I know this is very specific, but any idea what the react way to get the markers to be aware of current zoom level?  (would i have to setup an event for each marker to listen for zoom changes?)

thanks!

**Comment by istarkov** [comment]
Here https://github.com/istarkov/google-map-clustering-example/blob/master/src/GMap.js output depends on zoom and other param.

Example: http://istarkov.github.io/google-map-clustering-example/

**Comment by worldlyjohn** [comment]
wow fast response!  just what i was looking for -- thanks!
