### ISSUE TITLE
Map ignores zoom/center state changes after user pans map with built-in controls

### ISSUE THREAD

**Issue by worldlyjohn** [istarkov/google-map-react#176]
I have a basic map example with a button that on click will change map zoom and center. The button works as intended on load. 

However, **once you pan the map or use the built-in zoom controls** the map **stops listening to the state events**. When you try the button event after zooming in with controls, the map fails to respond and update.

Anyone else experience this?  Some sample code to reproduce is below...

```
handleClick() {
  this.setState(update(this.state, {
    zoom: 12,
    center: {lat: 44, lng: 13}
  }));
},
render() {
  <div onClick={this.handleClick}>re-zoom</div>
  <GoogleMap
    center={this.state.center}
    zoom={this.state.zoom}>
  </GoogleMap>
}

```

**Comment by istarkov** [comment]
Please provide jsbin examples https://jsbin.com/roqutisoqu/1/edit?js,console,output
Otherwise I have no idea how to help with information u provide.

**Comment by worldlyjohn** [comment]
ahh, thank you.  looks like i need to capture the onChange and set state from those changes as well, otherwise it stops working.

that said, now im seeing more of the problems with "GoogleMap bounds not eq" referenced by https://github.com/istarkov/google-map-react-examples/issues/8
