### ISSUE TITLE
Can a getMap() method be added?

### ISSUE THREAD

**Issue by EdwardDrapkin** [istarkov/google-map-react#179]
Hey, there are a few things I wanted to do with the Google Maps API, so I wound up referencing the internal 'map_' variable e.g. `this.refs.gmap.map_`.  This works fine, but I feel dirty accessing a "private" variable.

Can you add a method like this? 

    getMapRef() {
       return this.map_;
    }

Or were you intentionally trying to hide the google map reference from external consumers and is there a better way for me to get at it?

**Comment by istarkov** [comment]
There is a callback `onGoogleApiLoaded` https://github.com/istarkov/google-map-react#ongoogleapiloaded-func

**Comment by EdwardDrapkin** [comment]
Since it's guarded with `yesIWantToUseGoogleMapApiInternals` I figured referencing the map instance directly was preferable.  My bad!
