### ISSUE TITLE
Simple click events

### ISSUE THREAD

**Issue by lancetw** [istarkov/google-map-react#18]
Need a way to make click event on map and get something like LatLng,
I only see an `onChildClick` event in the library and no examples like this way,
it seems like could not easy to dynamic add new markers since no feedback when user click on the map,
or maybe am I missing something?

**Comment by jedwards1211** [comment]
You can definitely compute the lat/lng yourself from the bounds you get from the `onBoundsChange` handler you pass from the map.  But I agree that ability to pass a map click handler would be nice. @istarkov what do you think -- I could create an `onMapClick` prop that GoogleMap will call with `(event, {lat, lng})` if no child was close enough to the click, or perhaps just add the `lat` and `lng` to the event itself.

**Comment by istarkov** [comment]
good idea about onMapClick, 
next week i will add some new features to this project and add onMapClick onMapMouseMove etc. with this interface

**Comment by Andreyco** [comment]
@istarkov are you on this? Just asking, so that we don't do double work. But not promising anything...

**Comment by istarkov** [comment]
Yes, there will be a lot of changes soon.

**Comment by istarkov** [comment]
Mb this week

**Comment by Andreyco** [comment]
Awesome.

Temp workaround to hook into click (or any other event) until you deliver proper solution.

```js
handleClick() {
  console.log('click');
}

componentDidMount() {
  window.setTimeout(() => {
    const map = this.refs.map.map_;
    map.__customClickListener = this.refs.map.map_.addListener('click', this.handleClick.bind(this));
  }, 200);
}

componentWillUnmount() {
  const map = this.refs.map.map_;
  google.maps.event.removeListener(map.__customClickListener);
}

render() {
  return <GoogleMap ref="map"/>;
}
```

**Comment by istarkov** [comment]
For now, i almost finished support of this great mapbox library https://github.com/mapbox/geojson-vt
[Click here](http://recordit.co/MciFGBL3b7) to view gif example of google-map-react svg drawing 200M+ geojson file over google map. 
Example of geojson-vt server and drawing will be published soon. (need 2 fix some small issues)

**Comment by Andreyco** [comment]
I need click-to-map (actually right click) functionality badly right now so I came up with dirty solution for the time being. 

Speaking about upcoming features, they are insane, really :+1:  Cannot wait to play with!  

Do you use this package in a project or is it just hobby?

**Comment by istarkov** [comment]
Yes I use it in some real projects, 
( IMHO it's not possible to add new features on a hobby basis )

**Comment by Andreyco** [comment]
That's why I am asking :) It's possible to pay attention to hobby project for a short time, eventually it will die. Hope this is not the case.

**Comment by istarkov** [comment]
Usage example:
```javascript
_onClick = ({x, y, lat, lng, event}) => console.log(x, y, lat, lng, event)

<GoogleMap  onClick={_onClick} ... />
```

**Comment by lancetw** [comment]
Thanks :+1:

**Comment by vsshaposhnikov** [comment]
@istarkov may be you can add usage example to documentation ? Thanks

**Comment by Busin731** [comment]
Hey, Andreyco,
Why don't you use this?

onMapClicked = () => {
    console.log("============clicked=========");
    // console.log(center);
  };

  render() {
    const { center, triangleCoords } =  this.state

    console.log("============center=========");
    console.log(center);

    return (
      <div id="map">
        <Map 
          google={this.props.google}
          onReady={this.initMap}
          onClick={this.onMapClicked}
          initialCenter={center}
          zoom={15}
          yesIWantToUseGoogleMapApiInternals 
        >
        </Map>
      </div>
    );
  }

I wrote like this, but the onClick event does not work.
I hope urgent help.

**Comment by dowrow** [comment]
Hey @Busin731 looks like you are using a functional component, so the this. keyword is not needed here.
Anyways, looks like onClick is not triggered on touch devices.
