### ISSUE TITLE
Not detecting Key

### ISSUE THREAD

**Issue by kingreza** [istarkov/google-map-react#182]
I have the key setup in the GoogleMap bootstrapURLKeys property but it I'm still getting 

32 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

```
  <GoogleMap bootstrapURLKeys={{
          key: "API_KEY"
          }}
        center={this.state.center}
        zoom={this.state.zoom}>

        <MapMarker lat={this.state.center.lat} lng={this.state.center.lng}  type="mechanic"/>
      </GoogleMap>
```

**Comment by istarkov** [comment]
Be sure that key is set in all instances of `GoogleMap`,
I use `client` key in all my `at work` software and have no any issues.

**Comment by pandabrand** [comment]
I am having the same issue, I have only one instance 'GoogleMap' and it does not detect the key.
`        <GoogleMap
          key={Meteor.settings.public.GMAP_KEY}
          center={this.props.center}
          zoom={this.props.zoom}>
            <MapMarker lat={59.955413} lng={30.337844} text={'A'} />
            <MapMarker {...this.props.mapPlaceCoords} text={'B'} />
        </GoogleMap>
`

**Comment by frankdavidcorona** [comment]
`<GoogleMapReact
              defaultCenter={this.state.center}
              defaultZoom={this.state.zoom}
              key={this.state.mapKey}
       >
 </GoogleMapReact>`

I did it of this way, but not work for me.
