### ISSUE TITLE
IE10 errors "Promise" is undefined

### ISSUE THREAD

**Issue by achimkoellner** [istarkov/google-map-react#183]
Hi Istarkov,
great library! Thanks for the good work!

We're using the lib just to display a simple map in a webpack app that uses promise-polyfill:

    <GoogleMap
    ref="GoogleMapElement"
    options={MAP_OPTIONS}
    bootstrapURLKeys={{
      key: API_KEY,
      language: LANGUAGE
    }}
    center={CENTER}
    zoom={ZOOM}
    >
    </GoogleMap>

It runs well on all browsers except IE 10 that complains that "Promise" is undefined.
It looks like the GoogleMapLoader is invoked before we can initialize our promise-polyfill.
Or can this maybe be a conflict with babel-polyfill (used by you) and promise-polyfill (used by us)?

We're using version 0.15.0 of google-map-react

Thanks for any idea or comment.

**Comment by istarkov** [comment]
I removed all polyfills (and Promise too) from library few releases before, as I think it's on user to add polyfills to it's code.
For example at my main work I need to support just two browsers - Chrome and Safari, so there is no need for me in most polyfills at all.
So just add any Promise polyfill you like.
