### ISSUE TITLE
Drawing google.maps.Circle

### ISSUE THREAD

**Issue by THernandez03** [istarkov/google-map-react#184]
There's a way to create a [google.maps.Circle](https://developers.google.com/maps/documentation/javascript/examples/circle-simple?hl=en) ??

The idea is, zoom on the map and the radius of the circle goes bigger depending of the zoom of the map.

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react#ongoogleapiloaded-func

**Comment by shudson250** [comment]
You can draw a circle (or any other marker) using the google maps API.

Goolge map reference: https://developers.google.com/maps/documentation/javascript/shapes#circle_add
```ts
import GoogleMap from 'google-map-react';
...
const Map = ({latlng, zoom}) =>(
  <div style={{height: 400}}>
    <GoogleMap
      bootstrapURLKeys={{ key: GOOGLE_MAPS_API_KEY }}
      defaultZoom={zoom}
      defaultCenter={latlng}
      onGoogleApiLoaded={({map, maps}) =>
        new google.maps.Circle({
          strokeColor: '#FF0000',
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: '#FF0000',
          fillOpacity: 0.3,
          map,
          center: latlng,
          radius: 275,
        })}
    />
  </div>
);
```

**Comment by danieladea** [comment]
> You can draw a circle (or any other marker) using the google maps API.
> 
> Goolge map reference: https://developers.google.com/maps/documentation/javascript/shapes#circle_add
> 
> ```ts
> import GoogleMap from 'google-map-react';
> ...
> const Map = ({latlng, zoom}) =>(
>   <div style={{height: 400}}>
>     <GoogleMap
>       bootstrapURLKeys={{ key: GOOGLE_MAPS_API_KEY }}
>       defaultZoom={zoom}
>       defaultCenter={latlng}
>       onGoogleApiLoaded={({map, maps}) =>
>         new google.maps.Circle({
>           strokeColor: '#FF0000',
>           strokeOpacity: 0.8,
>           strokeWeight: 2,
>           fillColor: '#FF0000',
>           fillOpacity: 0.3,
>           map,
>           center: latlng,
>           radius: 275,
>         })}
>     />
>   </div>
> );
> ```

Is the radius in meters?

**Comment by hai98th** [comment]
> he radius in

yes, meters

**Comment by hai98th** [comment]
> Is the radius in meters?

yes, meters

**Comment by bobbybrownwubwub** [comment]
Hi guys, I have the map with a circle over the center and the map is updating when I change the lat and long props, however the circle does not move to the new lat and long, and stays in the same place. Ideas?

**Comment by itsmichaeldiego** [comment]
@bobbybrownwubwub How are you drawing the circle? You probably need to re-draw based on new center

**Comment by ssa11200** [comment]
> Hi guys, I have the map with a circle over the center and the map is updating when I change the lat and long props, however the circle does not move to the new lat and long, and stays in the same place. Ideas?

I defined a refreshMap function in which map is unmounted for mili second and mounter again.

  const refreshMap = async () => {
    setIsRefreshingMap(true);
    setTimeout(() => {
      setIsRefreshingMap(false);
    }, 100);
  };

**Comment by ssa11200** [comment]
> Hi guys, I have the map with a circle over the center and the map is updating when I change the lat and long props, however the circle does not move to the new lat and long, and stays in the same place. Ideas?

I defined a refreshMap function in which map is unmounted for mili second and mounter again.

const refreshMap = async () => {
setIsRefreshingMap(true);
setTimeout(() => {
setIsRefreshingMap(false);
}, 100);
};

and in you jsx

{!isRefreshingMap && (
       <GoogleMapReact>
             .
             .
             .
       <GoogleMapReact />)}

wherever you want to update the map just run the refreshMap function.

**Comment by bobbybrownwubwub** [comment]
I set it in a useEffect to clear out any circles, then updating

 ```
 useEffect(() => {
    if (mapReference && mapsReference) {

      if (circles.length) circles.map((circle) => circle.setMap(null));

      circles.push(
        new mapsReference.Circle({
          strokeOpacity: 0.4,
          strokeWeight: 2,
          fillColor: "#000",
          fillOpacity: 0.2,
          map: mapReference,
          center: latLong,
          radius: rng * 1000,
        })
      );
    }
  }, [mapReference, mapsReference, latLong, rng]);
```

**Comment by ssa11200** [comment]
> I set it in a useEffect to clear out any circles, then updating
> 
> ```
> useEffect(() => {
>    if (mapReference && mapsReference) {
> 
>      if (circles.length) circles.map((circle) => circle.setMap(null));
> 
>      circles.push(
>        new mapsReference.Circle({
>          strokeOpacity: 0.4,
>          strokeWeight: 2,
>          fillColor: "#000",
>          fillOpacity: 0.2,
>          map: mapReference,
>          center: latLong,
>          radius: rng * 1000,
>        })
>      );
>    }
>  }, [mapReference, mapsReference, latLong, rng]);
> ```

Thanks for sharing.
In my case, useEffect did not work as I working with a multi step form.

**Comment by istarkov** [comment]
Hey all this map wasnt intended to work with imperative native api, few months ago I wrote map realisation which solves issues like this and many others.

Here polygon example. 

https://realadvisor.github.io/rgm/geojson

**Comment by gerardopar** [comment]
```
interface LocationObj {
    address: string, 
    lat: number, 
    lng: number,
    status: Status,
    locationPreference: LocationPreference
}

const Map:React.FC<LocationObj> = ({ address, lat, lng, status }) => {
  
    return (
        <GoogleMapReact
        bootstrapURLKeys={{ key: 'SOME_KEY' }}
        center={{ lat: lat, lng: lng }}
        defaultZoom={15}
        options={{
            streetViewControl: true,
            styles: [{ featureType: 'poi', elementType: 'labels', stylers: [{ visibility: 'on' }] }]
        }}
        onGoogleApiLoaded={({ map, maps }) => new google.maps.Circle({
            strokeColor: '#1aa086',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#1aa086',
            fillOpacity: 0.3,
            map,
            center: { lat: lat, lng: lng },
            radius: 500,
        })}
        yesIWantToUseGoogleMapApiInternals
        >
            <LocationPin
                // @ts-ignore
                lat={lat}
                lng={lng}
                text={address}
            />
        </GoogleMapReact>
    );
};
```
