### ISSUE TITLE
Map fires onChange event after mounting

### ISSUE THREAD

**Issue by alex-e-leon** [istarkov/google-map-react#189]
This looks like it could be an issue with google-maps firing the event itself during initial load.

I found that sometimes google maps makes initial adjustments to the provided center position - so at first I thought this may be the cause.

However I've also tested with providing a center position that matches the value returned by google maps and the onChange event is still being fired.

**Comment by istarkov** [comment]
Its fired by design. So you could get bounds,  and yes - center that differs than provided. 
Center differs because of all internal calculations based on left top map coordinate, so conversion center - topleft - center could lost some precision.

**Comment by alex-e-leon** [comment]
@istarkov If you want to fetch markers/marker-data from another endpoint on onChange events, this causes you to always make an extra (avoidable) call on first render.

At the moment I run a check against the zoom levels + distance between the center points (provided vs returned by onChange) before making a request - but without digging into the internals, I'm not sure how much distance the new center might be adjusted so it's not foolproof. I'm also not sure it's a great pattern.

I wonder if it would be better to add a prop to set that behaviour ex: `fireInitialOnChange` or to just have it fire from a different event ex: `onChange` and `onLoad` ?

**Comment by istarkov** [comment]
To fetch initial data in most cases you need to know bounds, so u need onChange. Also for fetching markers I use tile strategy, to avoid refetching markers and not be dependent on small movements. I dont think some boolean is needed, as its easy to avoid refetching just setting some small epsilon to compare center positions in your case, imo there is at least milimeter precision or better.

**Comment by alex-e-leon** [comment]
Fetching markers using the tiling strategy is a good approach, and while it does prevent most refetching it still fails for edge cases, if the new center happens to adjust the map over a tile edge.

I'm currently doing exactly that, and comparing the distance between center positions. That's part of my concern though is that I don't know what the precision level of the re-centering algorithm is so I can match against it. You mentioned millimeter precision, but the one test I've done so far re-centers ~1.5m and I'm not sure if that's near the upper or lower bound.

**Comment by istarkov** [comment]
I think this precision is highly depends on latitude, as latitude transform to-from world coordinates is not linear and has math like https://github.com/istarkov/google-map-react/blob/master/src/utils/utils.js#L7
