### ISSUE TITLE
Map Marker disappearing after zooming in

### ISSUE THREAD

**Issue by Carpetfizz** [istarkov/google-map-react#192]
Hello,

I have a map marker that looks like this when zoomed out:

![screenshot from 2016-07-10 00-33-49](https://cloud.githubusercontent.com/assets/2084896/16712251/541aaf6e-4636-11e6-8023-7f63350f8000.png)

But after zooming in a little bit, it disappears.

![screenshot from 2016-07-10 00-33-58](https://cloud.githubusercontent.com/assets/2084896/16712255/6f49824c-4636-11e6-9278-c0d8e9236a48.png)

 
This is what the component looks like:

```
var PSMarker = React.createClass({
    render: function() {
        
        var MARKER_WIDTH = 40;
        var MARKER_HEIGHT = 40;

        var PSMarkerStyle = {
            position: 'absolute',
            width: MARKER_WIDTH,
            height: MARKER_HEIGHT,
            left: -MARKER_WIDTH / 2,
            top: -MARKER_HEIGHT / 2,
            borderRadius: MARKER_HEIGHT,
            backgroundColor: 'white',
            textAlign: 'center',
            color: '#3f51b5',
            fontSize: 16,
            fontWeight: 'bold',
            padding: 0
        };

        return (
            <div style={PSMarkerStyle}>
                <img src="/img/pokeball.png"></img>
            </div>
        )
    }
});
```

In order to render my `PSMarker` elements, I use the following loop:

```
                    <GoogleMap
                        defaultCenter = {this.state.center}
                        defaultZoom = {this.state.zoom}>
                        {this.state.sightings.map(function (sighting, i) {
                            console.log(sighting);
                            return (
                                <PSMarker name={sighting.name} lat={sighting.lat} lng={sighting.lon} key={i}/>
                            )
                        })}
                    </GoogleMap>
```

The markers come back once I zoom out again.

I'm not sure what could be causing this issue. I tried it without the image and the same thing occurred. I don't change the state or anything, I just use zoom regularly. Any help would be much appreciated - thanks!

**Comment by istarkov** [comment]
Not sure that without jsbin example or additional information I could help.
