### ISSUE TITLE
Dragging on mobile Chrome reloads the page

### ISSUE THREAD

**Issue by raulmatei** [istarkov/google-map-react#193]
Google Chrome mobile has the pull-to-refresh feature that seems to be triggered when dragging the map (see below):

![drag](https://cloud.githubusercontent.com/assets/1718341/16715698/69f19860-46f0-11e6-9a25-b7a4ae9cdbaa.gif)

This doesn't seems to happen with the demo google map that can be found here:
https://google-developers.appspot.com/maps/documentation/javascript/examples/full/map-simple

![simple-map](https://cloud.githubusercontent.com/assets/1718341/16715708/91c0b498-46f0-11e6-8f4e-f34731742c02.gif)

I was able to stop this behavior by adding `onTouchMove={(event) => event.preventDefault()}` on the `div` element that I use to wrap the map.

Wouldn't it be better to have `google-map-react` behave the same as GoogleMap?

Thanks,
Raul.

**Comment by istarkov** [comment]
Thank you, as I does not use this library for mobile development, (In 99.99 cases I write code for the non mobile web) I need a time to understand clearly why google map with my wrappers causes such behavior. 
As `preventDefault` is just a symptoms therapy, not the problem itself. Could anyone explain what really causes such effect?

**Comment by moodysalem** [comment]
@istarkov Is it possibly because the drag event is starting on the marker element in the example and not the map? @raulmatei Does this occur if you start your drag away from any marker?

**Comment by raulmatei** [comment]
@moodysalem it looks like it occurs even if you drag from a marker or if you drag from away from any marker.

**Comment by EmilTholin** [comment]
It might not be the prettiest solution, but to get this fine library to work on mobile you could do the following:

```js
<GoogleMap
  onGoogleApiLoaded={({ map }) => {
    if(isMobile) {
      map.addListener('mousedown', e => document.body.style.overflow = 'hidden');
      map.addListener('mouseup', e => document.body.style.overflow = '');
    }
  }} />
```

Might be a better solution out there, but works as a temporary fix.
