### ISSUE TITLE
Info adding a searchbox

### ISSUE THREAD

**Issue by guillaume-miara** [istarkov/google-map-react#195]
Thanks a lot for this awesome package! You have made my day when I found it. 

This is a "need help" issue. 

I want to tie a searchbox to my map in order to be able to center the map on the searched place. 

And I have been wrapping my head around this but cannot think of a good way to do it. 

Do you have any advice?

**Comment by istarkov** [comment]
Can't get the problem ;-) What the problem you have - how to add search box, or how to center the map or what?

**Comment by kencana-voilaah** [comment]
would like to know how to add the search box as well.

**Comment by istarkov** [comment]
Have you read the end of this https://github.com/istarkov/google-map-react#adding-a-searchbox paragraph?
Also you can use this callback https://github.com/istarkov/google-map-react#ongoogleapiloaded-func
Also you can use custom gmap loader.

**Comment by kencana-voilaah** [comment]
ah yeah, just got it work. thanks a lot
