### ISSUE TITLE
Need Help : How can we fill color in specific country using this library.

### ISSUE THREAD

**Issue by nishankkumar1994** [istarkov/google-map-react#196]

**Comment by nishankkumar1994** [comment]
@istarkov : Hi, I am using this library awesome work thanks. Need you help, how we can fill color in a specific country like translucent color.  Thanks in advance.

**Comment by istarkov** [comment]
Please search issues here about polygons.
https://github.com/istarkov/google-map-react/issues/149
https://github.com/istarkov/google-map-react/issues/62

There will be some ideas-solutions about how.

**Comment by nishankkumar1994** [comment]
Thanks for the help

On Wed, Jul 13, 2016 at 5:11 PM, Ivan Starkov <notifications@github.com>
wrote:

> Please search issues here about polygons.
> #149 <https://github.com/istarkov/google-map-react/issues/149>
> #62 <https://github.com/istarkov/google-map-react/issues/62>
>
> There will be some ideas-solutions about how.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/istarkov/google-map-react/issues/196#issuecomment-232331018>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH2ctWp--oBSfyVvBiGNa48i6GOwTReWks5qVM8FgaJpZM4JLU86>
> .
>



-- 
*Thanks & Regards*
*Nishank Kumar*
*Skype Id - nishankkumar94 *
*M.N.  -  +919891782404*

-- 
CONFIDENTIALITY NOTICE: The information contained in this e-mail is for the 
intended recipient(s) alone. It may contain privileged and confidential 
information that is exempt from disclosure under applicable law. If you 
have received this email in error, please notify the sender of the error 
and delete this message immediately.
