### ISSUE TITLE
Hiding and showing the map

### ISSUE THREAD

**Issue by ksavenkov** [istarkov/google-map-react#20]
I render GoogleMapReact in a hidden div. When I show the div, the map is absent. How to make it show?

http://jsfiddle.net/L3k4ktdj/1/

As I understand, as the div state (hidden/shown) is in the component state, it is rerendered after the state is updated. However, that doesn't really happen. I am just learning react, so maybe the error on my side. I'd appreciate you help with this, thanks.

**Comment by MozMorris** [comment]
How about using the state directly like this? http://jsfiddle.net/L3k4ktdj/2/
