### ISSUE TITLE
Can you extend fitBounds utils/func

### ISSUE THREAD

**Issue by ipostol** [istarkov/google-map-react#200]
Hello, in my project i am often I change the position of the map on the basis of the extreme coordinates, center and zoom i always take from fitBounds in render method. All my changes written to url and i can push or pop map position.

Problem: when trigger re-render with new NW, SE: center and zoom - correctly but NW and SE changed for themselves after onChange call. I know this is need but i will know future real NW and SE before change map.

Maybe you can in fitBounds send future NW and SE, or please say me how i can do this.

**Comment by istarkov** [comment]
You could try it yourself, and create a PR for this, adding future NW SE coords here,
https://github.com/istarkov/google-map-react/blob/master/src/utils/utils.js#L93

math is simple
All you need is to take `middle` point which is center but in world coordinates.
Then you need to convert `width`, and `height` to world coordinates

```javascript
    const scale = Math.pow(2, zoom);
    const ww = width / scale / GOOGLE_TILE_SIZE;
    // .. the same for height
```

then you need to convert from world coordinates not only the middle point but also
`middle - (ww/2, hh/2)` and `middle + (ww/2, hh/2)` and add to return { newBounds: { nw, se}}

then test that it works as expected and make a  PR here.

**Comment by ipostol** [comment]
Big thank for response. You really help me with this. Now i am know more about maps :)
https://github.com/istarkov/google-map-react/pull/202
