### ISSUE TITLE
Consider using gitter for active discussion

### ISSUE THREAD

**Issue by jgoux** [istarkov/google-map-react#201]
Hi,

Could you add your project on [gitter](https://gitter.im) so we can discuss about it without polluting the issues ?

Thanks for this project, I love the approach of abstracting away shapes from google API! :+1:

**Comment by istarkov** [comment]
Don't like gitter it's so slow.
Also don't think that chat is a good idea for not super popular libraries like current.

I want a service like: 
- I'll answer on any react - js - map question using my poor english via skype or similar voice service.

This will be fair exchange: my knowledge vs english speaking skill

**Comment by jgoux** [comment]
I find that a chat (gitter or something else I don't really care) is a better medium than github to deal with beginners questions and quick help between users.

Also, you don't have to be the only person helping others, I'm sure we can all learn together. :smile: 

My :gb: isn't good as well, I won't be of any help on this sorry.  

In the end it's your project and I respect your decision. Keep up the good work! :100:
