### ISSUE TITLE
Invoke google.maps.event.trigger("resize")?

### ISSUE THREAD

**Issue by artcups** [istarkov/google-map-react#206]
Is it possible to invoke resize on the map component? I have the map in a tab that is hidden on render and the map is therefor not shown when the tab is chosen.

I know about the modal solution but i don't want to rerender the map all the time.

**Comment by istarkov** [comment]
Please read https://github.com/istarkov/google-map-react/issues/106#issuecomment-187944697
What are you think about proposed solution

**Comment by artcups** [comment]
The proposed solution to change center after _setViewSize did'nt work for me. I have two tabs where the map is rendered in the second hidden one, and i do the setViewSize in a postRenderCallback from the tabs component. I am using Redux and the tabs is onsen UI. I tryed setting the size of the container using css but the map is still gray. Any suggestions?

**Comment by moodysalem** [comment]
@istarkov you could check size of the map container on componentDidUpdate and store it in an instance variable of the google map, and trigger refresh when width or height changes-this would work as long as the parent component doesn't override shouldComponentUpdate I think

btw I'm having issues where the internal _setViewSize call isn't recalculating positions of the children

![image](https://cloud.githubusercontent.com/assets/7897876/17861626/77d40e3a-6857-11e6-8aff-310178d08022.png)

![image](https://cloud.githubusercontent.com/assets/7897876/17861631/7b3eed1a-6857-11e6-8d54-3d348fcfad7f.png)

**Comment by istarkov** [comment]
Looks like most sizing issues shoud be fixed by this PR #219 
just use `resetBoundsOnResize={true}`

It works perfectly with resizable elements.

**Comment by istarkov** [comment]
@moodysalem  In most cases checking element size on each update is not a good idea, as in all modern browsers this operation caused reflow.

please check latest npm version and set `resetBoundsOnResize={true}` on the map.

**Comment by moodysalem** [comment]
It works for me, thanks

**Comment by istarkov** [comment]
Thanks is not for me, but for @RUPOJS 
he did that amazing PR.

**Comment by ribeiroguilherme** [comment]
Amazing! This property is missing in the api docs, isn't? @istarkov

**Comment by istarkov** [comment]
Half of features are missing in the documentation ;-)
