### ISSUE TITLE
Support lat/lng in center to be functions so address.geometry.location can be assigned

### ISSUE THREAD

**Issue by bzbetty** [istarkov/google-map-react#209]
SearchBoxes return an address object that has a nested lat/lng in it but they're functions instead of numbers.  Would be nice if this object could be passed in.

Current work around

{ lat: address.geometry.location.lat(), lng: address.geometry.location.lng() }

**Comment by istarkov** [comment]
There are just few situations, where APIs can receive functions as parameters - props.
This situation does not provide any value for API, so no ;-)
