### ISSUE TITLE
Where can I find map markers in the Elements tree?

### ISSUE THREAD

**Issue by jedwards1211** [istarkov/google-map-react#21]
Sometimes changes I make to map markers cause them to have zero size.  I can find the markers in the React plugin for Chrome, but I can't seem to find them anywhere in the HTML Elements tab.  Where does the GoogleMapMarkers component get mounted?

**Comment by istarkov** [comment]
<img width="1327" alt="screenshot 2015-07-29 10 12 28" src="https://cloud.githubusercontent.com/assets/5077042/8951897/7f0b8260-35da-11e5-9fc4-95c383153ea9.png">

In chrome you can click on magnifier icon (top left corner in dev tools) and then place a mouse cursor over the marker, then click

**Comment by jedwards1211** [comment]
@istarkov well that works when the markers are visible, but when they're zero size I can't find them (if only the React dev tools simply had a go to DOM element function)

**Comment by istarkov** [comment]
It looks like overlay views are always placed by gmap in same places, and you need to remember that path (find path with visible marker and magnifier tool)
