### ISSUE TITLE
Change zoom to fit all markers without change center

### ISSUE THREAD

**Issue by khmelevskii** [istarkov/google-map-react#210]
How calc zoom for visible all markers and don't change map center

**Comment by nguyenhose** [comment]
I got the same issues

**Comment by istarkov** [comment]
As a fast solution just get a `zoom` from fitBounds, and then check that if it not enough just take `zoom - 1`

**Comment by istarkov** [comment]
To get the idea of bounds check please look how newBounds calculated https://github.com/istarkov/google-map-react/blob/master/src/utils/utils.js#L111
(just use your middle point to calculate your bounds with zoom)

**Comment by nguyenhose** [comment]
I see that, but how I find `{nw: xxx, se: xxx}` when I have latitudes of markers ?

**Comment by nguyenhose** [comment]
Got it!, but I dont know if any way make better: 

`const bounds = new google.maps.LatLngBounds();
      for (let i = 0; i < markers.length; i++) {
        const marker = markers[i];
        const newPoint = new google.maps.LatLng(marker.lat, marker.lng);
        bounds.extend(newPoint);
      }
      const size = {
        width: 640, // Map width in pixels
        height: 380, // Map height in pixels
      };
      const newBounds = {
        nw: {
          lat: bounds.getNorthEast().lat(),
          lng: bounds.getNorthEast().lng()
        },
        se: {
          lat: bounds.getSouthWest().lat(),
          lng: bounds.getSouthWest().lng()
        }
      }; `

**Comment by leandrooriente** [comment]
Google Maps use North East and South West and this lib use North West and South East. 

We can't get the center and zoom data from fitBounds util based on bounds makers.

@istarkov

**Comment by istarkov** [comment]
> We can't get the center and zoom data from fitBounds util based on bounds makers.

Wow! What a nice description of the problem. 
What I can get from this problem description having that bounds can be easily converted from one format to another and that center calculus does not depends on bounds format at all?

**Comment by leandrooriente** [comment]
## Google Maps fitBounds params: 
https://developers.google.com/maps/documentation/javascript/reference#LatLngBounds

```
sw?:LatLng|LatLngLiteral,
ne?:LatLng|LatLngLiteral
```

Bounds Methods:

```
getNorthEast()
getSouthWest()
```

## Google Map React fitBounds method: 
https://github.com/istarkov/google-map-react/blob/master/src/utils/utils.js#L67

```
fitBounds({ nw, se }, { width, height }) {...
```

## Workaround 

```
      let bounds = new google.maps.LatLngBounds()

      nextProps.places.forEach(p => {
        bounds.extend(new google.maps.LatLng(p.lat, p.lng))
      })

      // WRONG DEFINITION: 
      const se = bounds.getNorthEast() // SE --> NE
      const nw = bounds.getSouthWest() // NW --> SW
      const { center, zoom } = fitBounds({
        se: { lat: se.lat(), lng: se.lng() },
        nw: { lat: nw.lat(), lng: nw.lng() }
      }, { width: 777, height: 225 })

      this.setState({ center, zoom: 14 })
```

**Comment by istarkov** [comment]
Im supereasy :-) but problem descriptions like - I cant do something, without any explanation make my arse fire ;-)
