### ISSUE TITLE
react-unknown-prop

### ISSUE THREAD

**Issue by BesatZardosht** [istarkov/google-map-react#213]
Warning: Unknown props `lat`, `lng`, `$hover`, `$getDimensions`, `$dimensionKey`, `$geoService`, `$onMouseAllow`, `$prerender` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop.

After react 15, unknown props cannot be used

**Comment by istarkov** [comment]
Thank you, I know, in process.

**Comment by istarkov** [comment]
Will fix today

**Comment by BesatZardosht** [comment]
That's great!! Thanks

**Comment by istarkov** [comment]
Looks like no PR will help, as the problem that in new React you should not use `div` or other DOM react elements as a children of a Map.
even I'll remove internal `$` props on React.cloneElement you are still will have `lat` `lng` props on your `div` (etc) so the problem will not gone.

IMO the best way is not to use DOM elements as Map children, you should create your own Marker etc component.

**Comment by BesatZardosht** [comment]
OK.. Thanks.. as a suggestion I think it would much more sense if we could pass an array of markers to google-map-react component instead of having to add a separate child inside the component.
anyway.. Thanks for your response and for your wonderful work!

**Comment by rhagigi** [comment]
@BesatZardosht +1 on your suggestion -- I also wish we could do that. It would also be nice if this lib exposed the native google maps Marker support. Not sure if that's something @istarkov would want but I could submit PRs
