### ISSUE TITLE
Document $geoService, $getDimensions, $dimensionKey and other APIs for child components

### ISSUE THREAD

**Issue by moodysalem** [istarkov/google-map-react#216]
I'm trying to figure out how the bubble is placed so well in the google maps example, and there's this important block of code which makes use of three undocumented props

```
// baloon position calc
    const mapWidth = this.props.$geoService.getWidth();
    const mapHeight = this.props.$geoService.getHeight();
    const markerDim = this.props.$getDimensions(this.props.$dimensionKey);

```

**Comment by istarkov** [comment]
IMO public and private API should be cut in future versions, as almost all methods and props were created having heavy deadline pressure ;-)
Also there are some hard to implement issues with current API, and internally for some tasks I use the other ideas of rendering react over map, but these ideas should be generalized. (_Like subgrouping children, tiles rendering, etc_)
