### ISSUE TITLE
Mark area with circle, resize circle when zooming

### ISSUE THREAD

**Issue by laursen86** [istarkov/google-map-react#217]
The Google Maps API (_google.maps.Circle_) allow you yo create circles which resizes with zooming such the area within the circle remain the same. Can the same be done with this without using the Google Maps API directly?

**Comment by belohlavek** [comment]
Is this what you mean? https://github.com/istarkov/google-map-react/issues/123

**Comment by laursen86** [comment]
Spot on it is, thank you. I think i will use this instead of using the Google Map API directly.
