### ISSUE TITLE
Better isomorphic experience. 

### ISSUE THREAD

**Issue by DylanPiercey** [istarkov/google-map-react#22]
I am wonder if you guys have thought of using the [static google maps api](https://developers.google.com/maps/documentation/staticmaps/intro) to render the map's image statically and then replace it when in the browser?

Currently only the markers will render isomorphically, but this would allow for everything to work (except obviously navigation and such).

**Comment by istarkov** [comment]
But what a real need in this? 
Isomorphic markers allows to share information with search engine bots.
Also user can see some info before map api loads.

There is no speedup for user page loading if i place image before map api loads (map images is not small).
