### ISSUE TITLE
With version 0.18.1, it is not server-rendable due to requestAnimationFrame of undefined

### ISSUE THREAD

**Issue by minheq** [istarkov/google-map-react#220]
With the latest addition to the version, which I believe is resize detection, on the server the **window** object is _undefined_

I suggest using the detectElementResize used in react-virtualized project

[server-rendable detectElementResize.js] (https://github.com/bvaughn/react-virtualized/blob/497776bcd00000aa860b368d320c43db98225c35/source/vendor/detectElementResize.js)

**Comment by istarkov** [comment]
got it, thank you, will fix in near future

**Comment by istarkov** [comment]
In npm 0.18.2
