### ISSUE TITLE
IE9 and IE10 - Unable to get property 'center' of undefined or null reference

### ISSUE THREAD

**Issue by joaovpmamede** [istarkov/google-map-react#223]
I'm getting this error with the last version of the lib.
Might be because of this line here:
```
var _this = _possibleConstructorReturn(this, Object.getPrototypeOf(GoogleMap).call(this, props));
```

Specifically `Object.getPrototypeOf(GoogleMap).call(this, props)` which I think is not supported by these browsers.

What should we do? Use some sort of polyfill?

**Comment by istarkov** [comment]
I think yes.

**Comment by joaovpmamede** [comment]
Do you know exactly how? 
I'm struggling with this for a couple of hours. Thought that by using `babel-polyfill` things would start working, but either I'm using it in the wrong way or it's not enough.
Thanks.

**Comment by istarkov** [comment]
Even Microsoft does not support IE-10, so do I. 
I even has no any otherIE version at my computer.

**Comment by istarkov** [comment]
So I'm not a IE expert as last ie version I use frequently was ie-6 ;-)

**Comment by joaovpmamede** [comment]
Totally understand, wish I wouldn't have to support it (client demands).

**Comment by istarkov** [comment]
Have u googled for this polyfill? Like this http://ejohn.org/blog/objectgetprototypeof/ etc some of them could work, but even shim authors https://github.com/es-shims/es5-shim write about problems with getPrototypeOf

**Comment by istarkov** [comment]
May be older gmap version builded with previous babel will work?

**Comment by joaovpmamede** [comment]
@istarkov Yup I tried with that polyfill but it didn't work. I'll try a couple more options.
I'm still trying to understand what this does exactly: `Object.getPrototypeOf(GoogleMap).call(this, props)`.
This is basically "injecting" the `props` object to `this`, correct?

Maybe but not sure if could break other things or not.

**Comment by joaovpmamede** [comment]
@istarkov fixed :)

PR here https://github.com/istarkov/google-map-react/pull/224

And thanks for trying to help me.
