### ISSUE TITLE
Programmatically trigger resize

### ISSUE THREAD

**Issue by mattecapu** [istarkov/google-map-react#226]
When my `google-map-react` component is mounted before being styled, it doesn't correctly detect styles so bounds collapses to `0` and the map is not rendered. A manual resize triggers recalculation and it then renders as expected.
Currently I workaround this by adding an inline style, which I'd like not to because my styles live in CSS files, is there a better way?

**Comment by istarkov** [comment]
The latests library version has this PR https://github.com/istarkov/google-map-react/pull/219
just play with `resetBoundsOnResize={true}` and in most cases it should work.

**Comment by mattecapu** [comment]
It doesn't solve the issue because resize isn't (apparently) triggered when the styles are applied, which is after the component computes size.

**Comment by istarkov** [comment]
Please provide jsbin example with latest map version.
