### ISSUE TITLE
Broken in IE 11

### ISSUE THREAD

**Issue by jopdeklein** [istarkov/google-map-react#229]
The project used to work (last I tried was `0.11.2`), but when I upgraded to `0.18.3` it no longer works in IE11. I haven't been able to figure out the root cause but it could be babel / es6-promise related as we se `Promise` is undefined errors every once in a while.

**Comment by istarkov** [comment]
I decided not to support polyfills in library code, it's on user to add polyfills unsupported by browsers he need.

**Comment by jopdeklein** [comment]
OK clear, in which version did you remove the polyfills? I can check which we need and serve to them to the correct browsers.

**Comment by istarkov** [comment]
> in which version did you remove the polyfills?

Have no idea ;-), sorry have no time to parse history

**Comment by thunderkid** [comment]
I'm using 
```
var Promise = require('es6-shim').Promise;
var GoogleMap = require('google-map-react').default;
```
and it works with IE11, Windows 10.

**Comment by jopdeklein** [comment]
Thanks @thunderkid.
@istarkov I made a PR documenting this: #231
