### ISSUE TITLE
All markers rendering when mouse moves.

### ISSUE THREAD

**Issue by thunderkid** [istarkov/google-map-react#230]
I have a map with 300 markers. When I move the cursor over one marker, all 300 markers are re-rendered. With a small number of markers this doesn't matter, but with hundreds it gives a significant performance lag. The re-rendering seems to occur even when `onChildMouseEnter` and `onChildMouseLeave` are absent. 

Is this the expected behavior? Is there a way to prevent it?

**Comment by istarkov** [comment]
You could optimize your marker code like `pure` recompose HOCs to prevent rerendering if no property has changed. Here https://github.com/istarkov/google-map-react/blob/master/develop/GMapOptim.js#L96 I played with idea to notify marker directly via rxjs, this gives a significant performance gain BUT only in develop mode. In production mode, it also faster but not significantly, so I decided not to implement this ideas.
Locally I use other ideas to speedup big amount of markers - like grouping, etc, but almost all of them is dirty api (and having that current library api also not good, I also just use these ideas locally)

**Comment by thunderkid** [comment]
Thanks, but I'm still not understanding why it's necessary for `OnChildMouseEnter` to trigger a redraw of all markers. My markers have a property `isHovered` which I turn on and off with `OnChildMouseEnter` and `OnChildMouseLeave`, and I use css to make the hovered marker appear yellow. When I move the mouse around the map, performance is very bad because all map markers are redrawn each time. The yellow spot moves very jerkily.

But then I added a table beside the map that also shows the same marker data in a list. Hovering over the table row uses `OnMouseEnter` to turn on `isHovered`, which also makes the corresponding marker on the map appear yellow. Moving my cursor up and down the table list gives good performance - the yellow spot on the map moves around very fast, and only a single map marker is being re-rendered each time.

So React (with mobx in my case) correctly notifies just a single marker to update. I think that If instead of using `OnChildMouseEnter`, I could just use `OnMouseEnter` directly within the map marker html, it would update efficiently. So `OnChildMouseEnter`seems to come with a big cost. Is it possible to turn it off altogether and just use `OnMouseEnter` instead?

**Comment by istarkov** [comment]
In example I gave to you this prop https://github.com/istarkov/google-map-react/blob/master/develop/GMapOptim.js#L40 disables all marker rerendering on hover. But this property will not be supported and will be removed in the future. 
As I said even notifying a marker directly gives a big performance gain in Dev mode, this gives almost nothing in Production builds if your own markers uses shallowEquality in shouldComponentUpdate. 
So I will not support additional properties etc. until I see any advantages in this solution.
Rerendering now occurs because of some internal not documented properties (with $ at begin) I use in my projects.

**Comment by thunderkid** [comment]
Ok, thanks. For me, adding the `experimental` tag improves performance significantly, for both development and production builds. With 1000 markers on a desktop machine there is now almost no perceptible lag. (Although I admit that with 4000 markers the lag is still very bad at ~500ms. I don't know whether I can improve that. I'm investigating further.)
 
I have a request - if you deprecate the `experimental` property in the future, perhaps preserving this particular feature as a new `noRenderOnHover` property would be nice. (Or even require `renderOnHover` so that the default behavior is simpler with higher performance.) I know it's not significant for small numbers of markers, but extra performance is always nice and sometimes essential. To me it also just seems cleaner that way, though I don't know anything about your undocumented $ properties.

**Comment by istarkov** [comment]
I know how to draw 4000 markers, somewhere in issues I wrote all math for that.
I draw markers in tiled SVG over map, tile size depends on speed I need. 
Then I use a small buffer of markers (=20) over that svg layer, this buffer just for drawing hover markers animation.
When I hover over svg point I hide that point, make next element in buffer visible, give to it  coordinates, and start to draw html react element animation over that place, this works really fast for a thousands of markers.

**Comment by thunderkid** [comment]
That sounds very efficient. Did you give more details in another issues thread? I searched for 'tiles', and 'SVG', etc but couldn't find anything.

**Comment by istarkov** [comment]
The same math as in how to draw polygons https://github.com/istarkov/google-map-react/issues/62
And may be in other polygons issues
