### ISSUE TITLE
Panning the map with touch devices is very clunky

### ISSUE THREAD

**Issue by jooj123** [istarkov/google-map-react#232]
Not sure what is causing this - it seems to also be on the reproducible on the demo site with an iPad: 
http://istarkov.github.io/google-map-react/map/main/

If you pan with your finger the map seems to get stuck and you end up moving the entire browser window.

**Comment by jooj123** [comment]
Im happy to create a PR if you can provide me with some guidance / hints as to where the issue could lie

**Comment by istarkov** [comment]
1) Examples are very outdated
2) IMO google map even without any additional components is unusable on mobile devices
3) I have zero mobile devices now (_just simple android phone_) to view the map, so I can't say anything about ;-), I never developed for mobile web and I really have no idea how this library works there ;-)

So sorry I can't help here now.

**Comment by jooj123** [comment]
Other react google maps plugins work smoothly on ipad but i prefer this plugin - so ill try and figure out the issue ..

**Comment by jooj123** [comment]
This is fixed in this PR: https://github.com/istarkov/google-map-react/pull/233
