### ISSUE TITLE
Implementing marker drag and drop

### ISSUE THREAD

**Issue by ippa** [istarkov/google-map-react#234]
I'm looking to implement moving of markers via drag and drop. I don't see any such functionality built-in, do I miss something?

If that kind of thing isn't in the scope of google-map-react and I would need to implement it from scratch, is there some kind of way of stopping the map move (if I click and drag on a marker).

Thanks for a great lib, got a map and markers up insanely quick :)

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/issues/59
