### ISSUE TITLE
Doubleclicking on a marker always triggers mapzoom

### ISSUE THREAD

**Issue by ippa** [istarkov/google-map-react#236]
So I have very simple markers on my map, with this prop:
`onDoubleClick={ e => { alert("dbl"); e.stopPropagation(); e.preventDefault(); return false; }`

If I doubleclick on a marker, the alert will trigger but the map will also zoom in. Niether stopPropagation or preventDefault will stop that from happening. Is there another way?

**Comment by istarkov** [comment]
> Is there another way?
Yes
