### ISSUE TITLE
Calculate zoom level to display a given circle

### ISSUE THREAD

**Issue by mgtitimoli** [istarkov/google-map-react#237]
Hi!

I'm dealing with a situation where I have a circle of a certain radius (in mts) with the center on a given lat/lon, and I would like to calculate the required max zoom level, so the circle would fit entirely on the screen.

I would really appreciate any help on this,
Thanks!

**Comment by istarkov** [comment]
The same as `fitBounds` is intended for
https://github.com/istarkov/google-map-react#fitbounds-func

**Comment by mgtitimoli** [comment]
(Thanks for your quick response)

Yes, I Initially thought that I could use that one with the following points:

- nw = (lat1, lon1)
- se = (lat1, lon1 - diameter)

But the thing is that **fitBounds** does a lot of calculations that for circles aren't necessary (like getting the center), so I was wondering, since this is a very common case, I mean, having a circle centered in the map with a "search" radius, that if it's worth to add some helpers to deal with circles.

What do you think?

**Comment by istarkov** [comment]
I dont think that it's very common case :-) as you are the first with this task ;-)
So the most common solution with fitBounds is enough ;-) 
Even it make additional calculations, I see no task where the performance improvements of this method make sense.
