### ISSUE TITLE
Popup windows not staying open on hover

### ISSUE THREAD

**Issue by bradyhigginbotham** [istarkov/google-map-react#238]
I was checking the [main](http://istarkov.github.io/google-map-react/map/main) example (Chrome) and noticed that when hovering over a marker and attempting to enter the popup window, the window would disappear/close. It seems this isn't expected as all the windows show a "click to view more info" line. I'd love to be able to use this library, and need the ability to hover or click a marker and enter a customizable, animatable popup. Is this currently a bug or something the example is simply missing?

**Comment by istarkov** [comment]
This library does not provide nor markers nor popups. 
Please read second sentence in the readme.
Its on you what library to use for popups, make them hoverable, clickable or not.

**Comment by istarkov** [comment]
ps: In examples just click on marker.
