### ISSUE TITLE
Can Markers Be Used Inside a Container?

### ISSUE THREAD

**Issue by NoxHarmonium** [istarkov/google-map-react#239]
Hi,

Using your great example I have made markers animate in when they are added to the map. 

http://istarkov.github.io/google-map-clustering-example/

I am now trying to animate the markers out when they are removed from the map. The only way I can think of doing this is to nest the markers inside a container that can manage their lifetime and not destroy them until the animation has finished such as a React Transition Group.

https://facebook.github.io/react/docs/animation.html

This doesn't work however because the markers are positioned automatically by the map and the whole group gets the same position.

Can you think of any way I would be able to pass the marker positions to the container or any other way I would be able to animate markers out when they are removed?

Thanks for such a useful library!

**Comment by istarkov** [comment]
You could use react-motion for in out animations, please read about TransitionMotion. Please write if you will have any issues.

**Comment by NoxHarmonium** [comment]
It looks like `TransitionMotion` needs to be a wrapper for multiple elements like `TransitionGroup`

https://github.com/chenglou/react-motion#transitionmotion-

It has a `styles` property rather than `style` that you have to pass an array to. I would have the same problem where the map would set the position of the `TransitionMotion` element rather than each individual element it wraps.

**Comment by istarkov** [comment]
TransitionMotion is intended for animation of such situations as you described, adding - removing elements.
Here are similar - multiple markers, adding removing. 
Please provide a non working example about what is not working for you, as I can't understand what are you talking about.

Here is what you need: 

pseudocode
```
<TranstionMotion>
  (styles => 
     <Map>
          styles.map(style => <Marker />
    </Map>
```

**Comment by NoxHarmonium** [comment]
Oh I see! I was thinking you would have to put the `TransitionMotion`  element inside the map element, I'll try putting it outside the map and see how how I go.

Thanks!

**Comment by MLBD-Turash** [comment]
Is there any working demo for this?
