### ISSUE TITLE
how can i draw a polyline in this component?

### ISSUE THREAD

**Issue by Verten** [istarkov/google-map-react#240]
Hi, my question is how can i draw some polyline in this component, thanks.

**Comment by istarkov** [comment]
please use search for polygon in issues

**Comment by hemedani** [comment]
please create a simple example

**Comment by yehyaumar** [comment]
This helped me a lot in drawing polygons or polylines on Map Component: [Google Maps Shapes](https://developers.google.com/maps/documentation/javascript/shapes)
Get Map refs in `onGoogleApiLoaded={({ map, maps }) => handleMapLoad(map, maps)}`
In this, add a listener (click or contextmenu) on map,
```
function MapComp () {
  const gMap = useRef();
  const gMaps = useRef();
  let poly;

  const handleMapLoad = (map, maps) => {
    gMap.current = map;
    gMaps.current = maps;

    poly = new maps.Polygon({
      strokeColor: "#000000",
      strokeOpacity: 1.0,
      strokeWeight: 3,
      editable: true,
    });
    poly.setMap(map);

    map.addListener("contextmenu", addLatLng);
  };
  const addLatLng = (event) => {
    const path = poly.getPath();

    // Because path is an MVCArray, we can simply append a new coordinate
    // and it will automatically appear.
    path.push(event.latLng);

    // Add a new marker at the new plotted point on the polyline.
    new gMaps.Marker({
      position: event.latLng,
      title: "#" + path.getLength(),
      map: gMap,
    });
  };
return (
<GoogleMap
        yesIWantToUseGoogleMapApiInternals //this is important!
        onGoogleApiLoaded={({ map, maps }) => handleMapLoad(map, maps)}
      />
    </div>
  );
}

```

**Comment by pegues** [comment]
@yehyaumar I'm trying to create a polyline, but I'm using a class component. I added const gMap and const gMaps outside the class, and I'm getting the errors:

    src\components\MapView\MapView.js
      Line 9:14:   'useRef' is not defined                                                                                                                          no-undef
     Line 9:14:   React Hook "useRef" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
     Line 10:15:  'useRef' is not defined                                                                                                                          no-undef
     Line 10:15:  React Hook "useRef" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks

Do I have to add any particular imports? I currently use just `import GoogleMapReact from 'google-map-react';`
