### ISSUE TITLE
Uncaught Invariant Violation - GoogleMapMarkers

### ISSUE THREAD

**Issue by bondarewicz** [istarkov/google-map-react#245]
Hi There,
Could anyone point me into the right directing here?

I followed this [jsbin example](https://jsbin.com/roqutisoqu/1/edit?html,js,console,output)
and basically on the page where I would like to display the map I firstly:

`import GoogleMap from 'google-map-react';`

then set both center & zoom in page contructor and then use following:

```
<GoogleMap
  defaultCenter={this.state.center}
  defaultZoom={this.state.zoom}>
     <div className="place" lat={60.955413} lng={30.337844}>MyPlace</div>
</GoogleMap>
```

Map container is initially hidden and once the button is clicked to display the map I get :

Uncaught Invariant Violation: Objects are not valid as a React child (found: /> */). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `GoogleMapMarkers`.

package.json
```
"google-map-react": "^0.19.0",
"jquery": "2.2.3",
"moment": "^2.15.0",
"node-uuid": "^1.4.7",
"object-assign": "^4.1.0",
"react": "15.0.2",
"react-bootstrap": "^0.30.3",
"react-dom": "15.0.2",
"react-redux": "4.4.5",
"react-router": "2.4.0",
"react-router-redux": "4.0.4",
"redux": "3.5.2",
"redux-logger": "^2.6.1",
"redux-thunk": "2.0.1",
```

**Comment by rhagigi** [comment]
Are you sure that's your problem? Can we see the rest of the code? It's saying: `(found: /> */)` -- which tells me you might have a lagging `*/` comment-ending somewhere in your JSX (which isn't valid JSX)

**Comment by bondarewicz** [comment]
@rhagigi indeed, it was hot reloading issue (bad jsx), thanks for your reply anyways 👍 
closing this issue as unrelated to google-map-react
