### ISSUE TITLE
Isomorphic rendering - missing Google map

### ISSUE THREAD

**Issue by jFensch** [istarkov/google-map-react#247]
Should I be seeing the underling Google map when rendering on the server?  I'm seeing that disabling Javascript doesn't render the map.

**Comment by istarkov** [comment]
Just markers, as I'm not creator of google map itself.

Map could be done with google map static, but as I know it need an API key and server to sign requests to work.

**Comment by jFensch** [comment]
May want to call that out in the README.  

> _It renders on the server._  

leads to believe that the Google Map will render server side.
