### ISSUE TITLE
Marker animations

### ISSUE THREAD

**Issue by VLNTNA** [istarkov/google-map-react#252]
Hello,

is there an easy way to animate markers when loading the map for the first time ? Is it possible to use standard [Google Maps Marker Animations](https://developers.google.com/maps/documentation/javascript/examples/marker-animations?hl=de) when using own components as markers ?

For example, when creating markers you would usually do:
```javascript
marker = new google.maps.Marker({
  map: map,
  animation: google.maps.Animation.DROP,
  position: { lat: 59.327, lng: 18.067 }
});
```

Thanks !

**Comment by peitalin** [comment]
You can access the Google API by using `onGoogleApiLoaded` in the GoogleMap component:

`<GoogleMap bootstrapURLKeys={{key: APIKEY}} onGoogleApiLoaded={this.initMap} />` 

Then you can write:

```
    initMap({map, maps}) {
        var marker = new maps.Marker({
            map: map,
            animation: maps.Animation.DROP,
            position: {lat: -27.63453, lng: 153.0387}
        })
}
```

The objects `{map, maps}` in the callback function gives you access to:
        `map` -> Animation, ControlPosition, MapTypeControlStyle, MapTypeId, ... 
        `maps` -> qg {gm_bindings_: Object, __gm: rf, gm_accessors_: Object, streetViewControl: true…

**Comment by istarkov** [comment]
source: https://github.com/istarkov/google-map-clustering-example
example: http://istarkov.github.io/google-map-clustering-example/

**Comment by VLNTNA** [comment]
Thanks for your quick response - this helps me a lot. Thanks ! :)
