### ISSUE TITLE
Please keep Changelog up to date

### ISSUE THREAD

**Issue by jschlieber** [istarkov/google-map-react#254]
First things first: I really like this project. Thanks for sharing it.

But, it would be nice to have an up to date Changelog. I had to lock down my version to 0.11.2 because new versions didn't work as expected anymore. As there is no Changelog up to these versions I have no idea why and/or if the problem might have been solved in later versions (And I don't have the time to find out myself by trial and error, looking at the source or digging through closed issues...). Thanks a lot.

**Comment by itsmichaeldiego** [comment]
@jschlieber We've been adding tags and descriptions, let me know how is it looking now. Closing this issue now.
