### ISSUE TITLE
bootstrapURLKeys & apiKey no longer work in current version

### ISSUE THREAD

**Issue by JacobWeyer** [istarkov/google-map-react#256]
Hi all, I'm not able to use bootstrapURLKeys OR apiKey in the current version. It's not being recognized at all.

```
js?callback=_$_google_map_initialize_$_&key=undefined:37 Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error_.kb @ js?callback=_$_google_map_initialize_$_&key=undefined:37(anonymous function) @ common.js:50(anonymous function) @ common.js:201c @ common.js:44(anonymous function) @ AuthenticationService.Authenticate?1shttp%3A%2F%2F127.0.0.1%3A8000%2Fsearch&4sundefined&callback=_x…:1
index.js:152  action @ 23:21:50.644 RECEIVE_PROPERTIES 
```

**Comment by JacobWeyer** [comment]
I'm dumb. I need more sleep. Disregard me.

**Comment by ConzorKingKong** [comment]
Mind telling me what your error was? I seem to be in the same boat right now lol

**Comment by JacobWeyer** [comment]
I don't remember for sure, but I think my key variable was showing up as
undefined.

I think I might not have been passing an object to bootstrapURLKeys. Try
that and see if it works for you. Sorry I was slow!

<GoogleMap
    bootstrapURLKeys={{
        key: Config.GoogleMapApiKey
    }}
    defaultCenter={center}
    defaultZoom={zoom}
    onChange={onBoundaryChange}
    onChildClick={onMapTagClick}

>
