### ISSUE TITLE
Cannot read property 'fromLatLngToDivPixel' of undefined 

### ISSUE THREAD

**Issue by Bronsequences** [istarkov/google-map-react#257]
Intermittently seeing `Cannot read property 'fromLatLngToDivPixel' of undefined`  errors in production. Unable to successfully reproduce this locally. 

Stack trace from Raygun: 
<img width="803" alt="screen shot 2016-10-17 at 6 03 29 pm" src="https://cloud.githubusercontent.com/assets/4352192/19428165/1f75feba-9494-11e6-9c41-7ee33be45378.png">
<img width="175" alt="browsers affected" src="https://cloud.githubusercontent.com/assets/4352192/19428051/7829c2ea-9493-11e6-9124-6ae91c2582e4.png">

Implementation below: (using custom pointer component for styling only)

```
  renderMap() {
    const { location, googleMaps } = this.props;

    if (location.lat && location.lon) {
      return (
        <GoogleMap options={this.createMapOptions}
          defaultCenter={{lat: location.lat, lng: location.lon}}
          defaultZoom={16}
          bootstrapURLKeys={{key: googleMaps.apiKey, language: 'en'}}>
          <Pointer lat={location.lat} lng={location.lon} />
        </GoogleMap>
      );
    }

    return null;
  }
```

**Comment by reintroducing** [comment]
I saw this today too, locally, but just refreshed and it went away. It's definitely intermittent but I have no clue when/why it happens :\  Only happened to me once thus far.

**Comment by gabriel-laet** [comment]
Also noticing the same exception in production. I couldn't see a clear pattern between users, seems to affect all modern browsers as well.

**Comment by yuya373** [comment]
Hi! I have same exception. I got this.
```
TypeError
Cannot read property 'fromLatLngToDivPixel' of undefined
/assets/sources/pc_app-41d9587d14747b5803601f7937d20217e68a31a68be1a1cbed079760151ca726.js in apply at line 98459:39
	          var div = overlay.div;
	          var overlayProjection = overlay.getProjection();
	          var bounds = map.getBounds();
	          var ne = bounds.getNorthEast();
	          var sw = bounds.getSouthWest();
	          var ptx = overlayProjection.fromLatLngToDivPixel(new maps.LatLng(ne.lat(), sw.lng()));
	          // need round for safari still can't find what need for firefox
	          var ptxRounded = (0, _detect2.default)().isSafari ? { x: Math.round(ptx.x), y: Math.round(ptx.y) } : { x: ptx.x, y: ptx.y };
	          this_.updateCounter_++;
	          this_._onBoundsChanged(map, maps);
```

exception shows `overlayProjection` is `undefined` , so I read google maps reference and I found ` The projection is not initialized until onAdd is called by the API.`  in the document of `getProjection()` method of `OverlayView` instance.
I think `getProjection()` is called before `onAdd` is excecuted, and then `overlayProjection` is `undefined` and then got `Cannot read property 'fromLatLngToDivPixel' of undefined`.

[Google Maps JavaScript API V3 Reference  |  Google Maps JavaScript API  |  Google Developers](https://developers.google.com/maps/documentation/javascript/reference#OverlayView)
[google-map-react/google_map.js at 7a9a8d3fb7f3d1bf4409bddd326f2cc0545857cc · istarkov/google-map-react](https://github.com/istarkov/google-map-react/blob/7a9a8d3fb7f3d1bf4409bddd326f2cc0545857cc/src/google_map.js#L608)

**Comment by snakeyak** [comment]
same issue here. Unfortunately no clear pattern, happens "sometimes"

**Comment by xparthx** [comment]
Hello,

Same for me too. Not found any clear pattern yet for this error. Did anyone ever fixed that?

Thanks

**Comment by xparthx** [comment]
Hello,

I think I found the solution. Just use the latest version of the infobox.js:

https://github.com/googlemaps/v3-utility-library/blob/master/infobox/src/infobox.js

I was using version 1.0 before. After upgrading to the version 1.1.13, I'm not getting that error anymore.

Hope this will help someone.

Thanks

**Comment by mariusandra** [comment]
I'm also occasionally seeing this reported by Bugsnag, but can never reproduce locally. Has anyone find something that could help?

I'm not sure I understand what InfoBox has to do with this?

**Comment by mariusandra** [comment]
I released a package called [`@mariusandra/google-map-react`](https://www.npmjs.com/package/@mariusandra/google-map-react) on NPM, which is google-map-react v0.24.0 plus a quick `if (overlayProjection)` [hack](https://github.com/mariusandra/google-map-react/commit/6447cfe34293cbfa7ecadd098aeebeb52d1d61eb) in the hopes of fixing this bug. 

I'm not sure if it works, but putting this out there for the adventurous to try.

**Comment by nuclearspike** [comment]
I'm also seeing this in production. Any plan to apply something like @mariusandra 's solution to master?

**Comment by itsmichaeldiego** [comment]
@mariusandra You can totally create a PR and we'll merge it into our master, test it and release it 👍 

@nuclearspike ^

**Comment by Bronsequences** [comment]
Thanks @itsmichaeldiego for releasing a fix for this. 
I'm upgrading to the 0.32.0 package now and as it's intermittent will report back as to whether it's fixed. We've seen 88 instances of this error logged in Raygun over the last week so I should know in a day or so.

**Comment by Bronsequences** [comment]
Haven't seen any new instances of this error since updating to 0.32.0 so I'm calling it fixed and will close this issue now. Thanks again for taking the time to fix this for us. :)

**Comment by nuclearspike** [comment]
Thanks for getting this out. Upgrading now.
