### ISSUE TITLE
FitBounds get zoom null

### ISSUE THREAD

**Issue by UrukovMaxim** [istarkov/google-map-react#258]
FitBounds utility get null zoom property, center - correctly. Variable `var dy = seWorld.y - nwWorld.y;` less than zero. 
![react-google-maps](https://cloud.githubusercontent.com/assets/5775034/19471896/c830b402-952d-11e6-885e-74ba31b5e488.png)

**Comment by istarkov** [comment]
You should set south as south coordinate, in your case your south.lat > north.lat, so it's not south

**Comment by UrukovMaxim** [comment]
Thanks!
