### ISSUE TITLE
Dynamic width and hover/click

### ISSUE THREAD

**Issue by JiDai** [istarkov/google-map-react#259]
Hi, and thanks for this lib.
I try to add interactivity on marker (click and mouse hover) but I have a problem, It doesn't work when marker size is dynamic. Here is the Marker class :

```
class Marker extends Component {
    static propTypes = {
        lat: PropTypes.number,
        lng: PropTypes.number,
        text: PropTypes.string
    }
    render() {
        let {text, key} = this.props
        const {w, h} = meters2ScreenPixels(300, {lat: this.props.lat, lng: this.props.lng}, mapZoom);
        return (
            <div
                key={key}
                style={{
                    width: w,
                    height: h,
                    fontSize: w/2
                }}
                className="estima-marker">
                {text}
            </div>
        )
    }
}
```
I `w` and `h` are constant, the event `onChildClick` works, but if  I use `meters2ScreenPixels`, it does not works. The hover zone is still here but not match to the marker overlay.
How can I do that ?

**Comment by istarkov** [comment]
There are a few possibilities how to detect hovers and clicks, what method do u use?
Is it native DOM hovers-clicks or this library [internal-hover-algorithm](https://github.com/istarkov/google-map-react#internal-hover-algorithm)

**Comment by JiDai** [comment]
I use `onChildClick` and `onChildMouseEnter` on map component

**Comment by istarkov** [comment]
For this case you should also use specific `distanceToMouse` property function and `hoverDistance` https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L97-L102
As by default it calculates distances to markers as an euclidean distance to marker central point, 
and detect hovered marker using the following logic: 

Hovered marker is the marker with shortest distance to mouse and that distance should be less than `hoverDistance`.

Having non round markers distance function should be changed to other form, in a simple case with the function which returns 0 inside rectangle and INFINITY outside (you could extend it to return hoverDistance on rectangle borders and 0 at the center) 

PS: distanceToMouse has signature `distanceToMouse(markerPos, mousePos, markerProps)` so you could easily use marker properties for calculations. (it called for every marker)

**Comment by JiDai** [comment]
Ok got it. I tried native Dom event and it worked. But what it the recommended way ? Using native events or use  map events with `hoverDistance`/`distanceToMouse` method ?

**Comment by istarkov** [comment]
Native Dom events does not allow to hover on markers when their are intersected by each other as in the main example. 
Having that in real life markers are not uniformly distributed along the map, and often placed in one place it will be hard to hover on a lot of them, as sometimes just few pixel visible. 
Internal hover idea allows to hover on any marker based just on a distance (and any other parameters) so you could hover on any, 
also it allows to make some markers more "hoverable" (one of my clients wanted that people click on some markers more often (there is an example https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_distance_hover/distance_hover_map_page.jsx#L31-L46))

**Comment by istarkov** [comment]
PS: So the answer - it depends ;-) 
for a lot of situations native dom events are enough

**Comment by JiDai** [comment]
Ok thanks for explanations and responsiveness :)
