### ISSUE TITLE
onChange triggered multiple times

### ISSUE THREAD

**Issue by lpetrovhr** [istarkov/google-map-react#261]
First of all, nice project. 

I have one little issue, in my app I want to periodically update the markers in some interval after changing the bounds. One issue I came across is that when I change bounds the function call is called multiple times before the interval time has passed. 

Is there any way to prevent this from happening and call that event only when user stop moving the map?

**Comment by istarkov** [comment]
I think you could use debounce](https://lodash.com/docs/4.16.4#debounce) in your code to avoid multiple calls.

**Comment by lpetrovhr** [comment]
fixed this issue, thx
