### ISSUE TITLE
Map crashes on Android 4.3

### ISSUE THREAD

**Issue by catalinfeier** [istarkov/google-map-react#262]
I know that Android 4.3 is already pretty old, but i am required to support it. This is the error i get when using it on a Android 4.3 device:
![screen shot 2016-10-21 at 14 42 58](https://cloud.githubusercontent.com/assets/4579039/19597477/89b637fc-979d-11e6-841d-d000cb2c9ef7.png)
`Map` is the parent component of the `google-map-react` component in my setup. However, my setup is no that relevant, given that this is also reproducible when opening the [clustering example](http://istarkov.github.io/google-map-clustering-example/) on an Android 4.3 (i used the Android studio emulator, so no real device needed).

One thing to note, older versions work, just the newer versions of `google-map-react` don't. From my tests:

```
0.7.5 does work
0.14.5 doesn’t work
0.20 doesn’t work
```

Since the error is related to the way modules are imported/exported, the issue must come from a change in the way it is built/packaged. Any ideas what changed, where can i begin searching for the issue?

I can't revert to an older version because i also need this for mobile support: https://github.com/istarkov/google-map-react/pull/233 (and that's a recent addition)

**Comment by istarkov** [comment]
Other errors at console?

**Comment by catalinfeier** [comment]
Unfortunately, no other errors. Since the chrome debugger doesn't work with Android <4.4 i used [this](https://people.apache.org/~pmuellr/weinre/docs/latest/Home.html) for getting that warning. Yeah, it's difficult to debug on old androids, that's why i am asking for some guidance.

**Comment by istarkov** [comment]
I really have no idea what it is. May be the problem with polyfills I removed from this library.
for example promises "0.12.1" - "0.13.0"

**Comment by catalinfeier** [comment]
Thanks for the hint, that was it. It needs the es6 promise polyfill in order to work. I don't know if i should close this. Do you want to put the polyfill back in, or you want to leave it on a need-to-use basis?

At the very least, a readme note would be required as a heads up for others encountering this.

**Comment by itsmichaeldiego** [comment]
@catalinfeier Thanks for the contribution, as we're way behind Android 4.3, I don't think anything would be needed here. Closing the issue.
