### ISSUE TITLE
Custom maps styles?

### ISSUE THREAD

**Issue by kevinSuttle** [istarkov/google-map-react#265]
I don't see this in the props. 

https://developers.google.com/maps/documentation/javascript/styling

**Comment by mattydoincode** [comment]
Hey Kevin, it's just wrapped up into the options prop. Just ctrl + f on the docs and you'll see it. Here is my map (es6 react)

```
const Map = ({center}:PropsT) => {
    const mapOptions = {
        styles: mapStyles // straight out of something like snazzymaps
    };
    return (
        <div className={styles.mapWrapper}>
            <GoogleMap
                center={center}
                zoom={14}
                options={mapOptions}
                bootstrapURLKeys={{
                    key: '<MY_KEY>'
                }}>
            </GoogleMap>
        </div>
    );
};
```

**Comment by kevinSuttle** [comment]
Thanks!

**Comment by joebentaylor1995** [comment]
Just tried this, my custom colours from Snazzymaps applies until I scroll to the map, then it reverts

**Comment by itsmichaeldiego** [comment]
@joebentaylor1995 It is probably an issue with your implementation, we are all using map styles with no problem 👍

**Comment by lxibarra** [comment]
Where is an example of this

**Comment by snotrman** [comment]
This doesn't work

**Comment by gresbtim** [comment]
let's put it into the docs?
