### ISSUE TITLE
GoogleMap: defaultCenter prop changed. You can't change default props.

### ISSUE THREAD

**Issue by ir-fuel** [istarkov/google-map-react#267]
I used the map component like this:
```
<GoogleMap
            bootstrapURLKeys={{
              key:GoogleMapsApiKey,
              language:'en'
            }}
            defaultCenter={{lat:4.352130,lng:50.845926}}
            center={{lat: this.state.office.latitude, lng: this.state.office.longitude}}
            defaultZoom={9}
            zoom={12}
          >
          </GoogleMap>
```

So why is it complaining that I changed the `defaultCenter` prop?

**Comment by istarkov** [comment]
You changed. Every render u create a new object for def center, so reference equality gives false on compare. Also try issue search, there were similar issues.

**Comment by ir-fuel** [comment]
I searched on `defaultCenter` in the issues before posting but didn't find anything.
Thanks for the info.

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/pull/249

**Comment by ir-fuel** [comment]
Didn't see that one.
Thanks

**Comment by lokesh755** [comment]
I would suggest to use "center" instead of "defaultCenter". That works because it doesn't compare with older center.

**Comment by NangoliJude** [comment]
Use center instead of defaultCenter
