### ISSUE TITLE
Pass map bounds to markers

### ISSUE THREAD

**Issue by superlaziness** [istarkov/google-map-react#268]
Hi, 
Thank you for the useful component!

It would be nice to pass map bounds or map object to children props (markers). This will allow do some calculations within marker component like bubble offset.

Now I have to use onChange method and local state for this case.

**Comment by istarkov** [comment]
Not documented but exists, 
https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_main/marker_example.jsx#L147-L149

**Comment by superlaziness** [comment]
Thank you!
