### ISSUE TITLE
Grouping Markers

### ISSUE THREAD

**Issue by arvinkx** [istarkov/google-map-react#27]
Hi, thanks for the great work on this, really appreciated. I was wondering if you had any ideas for a way to group the markers that are closer together when zoomed farther out. There are existing libraries like ([googlemaps/js-marker-clusterer] (https://github.com/googlemaps/js-marker-clusterer)) but I don't think they work very well out of the box with this. Any ideas on how to implement something like that? Thanks again

**Comment by jedwards1211** [comment]
It would be cool if it were part of core functionality!  But I think you could write your own code to group markers before passing them into the map without too much difficulty, and you would have the advantage of being able to customize it however you want in that case.  Here are my suggestions for how to do it:

If you pass in a bounds change callback, i.e. `<GoogleMap onBoundsChange={this.onBoundsChange}/>`, then it will call that function when the user zooms or finishes dragging with the following arguments: `onBoundsChange([centerLatLng.lat, centerLatLng.lng], zoom, bounds, marginBounds)`.

So first off, you could store that in state, with `setState({bounds: bounds})`.

You would also need to know the size of your map, so in your `componentDidMount()` and probably also a window resize event callback, you could:
```
var map = React.findDOMNode(this.refs.map);
this.setState({
  width: map.offsetWidth,
  height: map.offsetHeight
});
```

With this information, in your `render()`, you compute each child's position in pixels by finding its percent X and Y relative to `this.state.bounds` and multiplying those by `this.state.width` and `this.state.height`.  Then you can use whatever algorithm you want to group children that are too close together (doing it efficiently isn't completely trivial, but I bet with a bit of Googling you could find a JavaScript RTree or other spatial index library to help with that).

You could pass these groups into some `<MarkerGroup>` component you create that displays whatever information you want about the group, and possibly even expands itself out to the individual children when hovered over.  And of course pass in isolated children as you normally would.

One could easily put this functionality in a nice wrapper component that could be used as a drop-in replacement for `<GoogleMap>`, so if you manage to get something working, feel free to make a pull request!

**Comment by arvinkx** [comment]
Thanks for the quick and detailed response. I have a question on calculating the child's positions, I have the bounds and the map width/height but how do I find the marker's percent X and Y in relation to the `this.state.bounds` values I have? 

The `this.state.bounds` value I have is an array of GPS coordinates if I am understanding correctly I need to figure out a percentage x value and y value in relation to the GPS coordinates and translate it to pixels then feed the width, height and all the point's x and y values into a R-tree library (like [mourner/rbush] (https://github.com/mourner/rbush)) to determine how close together they are? 

Thanks again for the help.

**Comment by jedwards1211** [comment]
The bounds are in this form (yeah we should document this at some point):

`[topLatitude, leftLongitude, bottomLatitude, rightLongitude]`

Important note: It's possible for `rightLongitude < leftLongitude` if the map area includes 180 degrees longitude.  So we have to check this when computing the pixel position of the marker.

So a basic method should be, in ES6 code: (**I haven't tested this**)
```es6
var {bounds, mapWidth, mapHeight} = this.state;
var [topLat, leftLng, bottomLat, rightLng] = this.state.bounds;
if (rightLng < leftLng) rightLng += 360;

React.Children.forEach(this.children, marker => {
  var {lat, lng} = marker.props;
  if (lng < leftLng) lng += 360;

  var x = (lng - leftLng) * mapWidth / (rightLng - leftLng),
      y = (lat - topLat) * mapHeight / (bottomLat - topLat);

  // use RTree to determine whether to group or not
  ...
});
```

**Comment by istarkov** [comment]
I've add an example https://github.com/istarkov/google-map-clustering-example just now

**Comment by jide** [comment]
Nice ! Too bad there's recompose, it makes it harder to understand :/

**Comment by nishankkumar1994** [comment]
@arvinkx  and @istarkov : Hi do you have any idea how can i grouping into different types like  (googlemaps/js-marker-clusterer ) does,  using this library.

**Comment by istarkov** [comment]
@nishankkumar1994  I'm not an expert of google maps, please provide href to example

**Comment by nishankkumar1994** [comment]
Here is the example and thanks for the help,
https://github.com/googlemaps/js-marker-clusterer

On Thu, Jul 14, 2016 at 11:47 PM, Ivan Starkov <notifications@github.com>
wrote:

> @nishankkumar1994 <https://github.com/nishankkumar1994> I'm not an expert
> of google maps, please provide href to example
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istarkov/google-map-react/issues/27#issuecomment-232748087>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH2ctQGFb2YHoGKb_1QfC1LPshqY3O8fks5qVn1AgaJpZM4Fn8SA>
> .
>



-- 
*Thanks & Regards*
*Nishank Kumar*
*Skype Id - nishankkumar94 *
*M.N.  -  +919891782404*

-- 
CONFIDENTIALITY NOTICE: The information contained in this e-mail is for the 
intended recipient(s) alone. It may contain privileged and confidential 
information that is exempt from disclosure under applicable law. If you 
have received this email in error, please notify the sender of the error 
and delete this message immediately.

**Comment by istarkov** [comment]
As I see it's just different markers for usual clustering algorithm so just output different markers using the same idea as here https://github.com/istarkov/google-map-react/issues/27#issuecomment-178769160

**Comment by seleckis** [comment]
Could someone provide simpler example of clustered markers without recompose? That would be very helpful!

**Comment by istarkov** [comment]
@seleckis recompose is very simple library, I promise that your development life will changed a lot since u will start using it. Im saying that not because Im collaborator of recompose, but because I work with a huge react projects, and nice plain logic flow seems like the only thing which makes team code readable.

**Comment by seleckis** [comment]
I see, but I need to use google maps in our existing project where we have defined code style and there are a lot of dependences, so we prefer to not expand the code as possible.

**Comment by istarkov** [comment]
In my practice such limitation causes just one thing - legacy code increase in your project.
As instead of using well documented - maintained open source libraries people write their own versions of similar things.
BTW it's fun to write such code, so why not ;-)
It's easy to rewrite clustering example by yourself, just do what enhancers says you.
`withHandlers` - just methods in your class
`withPropsOnChange` - update internal state when `shallowEqual` of picked props is not true,
`withProps` - just transform props
`withState` - just an object property of your state

**Comment by seleckis** [comment]
Thank you! Works well! But why cluster shoud be doubleclicked instead of one click like in original Marker Clustering example https://developers.google.com/maps/documentation/javascript/marker-clustering? Or simple click is just not implemented and map is zoomed because I just doubleclick on the map?

**Comment by istarkov** [comment]
This clustering example is fully independent of google clustering api, so I did that clusters depends on zoom only, and does not use clicks as the source of information like show this as not a cluster.
Its just a simple example, nothing else.

**Comment by seleckis** [comment]
Ok, thank you for explanation.

**Comment by ribeiroguilherme** [comment]
@seleckis Do you have an example that you can provide clustering without recompose? I'm newbie on react yet, and I've been facing the same issue as ours

**Comment by seleckis** [comment]
@ribeiroguilherme I adopted this example for my project, so I could post an example without recompose later, when I finish current sprint.

**Comment by ribeiroguilherme** [comment]
Thanks @seleckis for your help. It will be very appreciated.

**Comment by nandafirmans** [comment]
Hi @istarkov could you explain marker cluster algorithm on your example [here](https://github.com/istarkov/google-map-clustering-example/blob/master/src/markers/ClusterMarker.js)
sorry.. because it's hard to understand that code, especially for noob like me :|

**Comment by BrockBeldham** [comment]
@seleckis any update on an example without recompose? I've almost got it figured out, but a 'vanilla' example would help a lot.

**Comment by BrockBeldham** [comment]
@istarkov right, I get that and it looks pretty handy, but the code is organized strangely and not immediately apparent what's happening, especially to unseasoned React devs. Similar to @seleckis I don't have the time to go through the large React/Redux app I've built and reorganize everything when really I just need to get clustering working on a map. It might be something I consider in the future, but right this second clustering is more important.

**Comment by r3ticuli** [comment]
It's been done here : https://github.com/Tim152/clustering-google-map-react

**Comment by HashemKhalifa** [comment]
@r3ticuli Thanks, can we have the tooltip card as well?

**Comment by patelrr** [comment]
@r3ticuli How to expand cluster when it's clicked ? Can you help me to get this feature in my map ?

**Comment by bkitaec** [comment]
Maybe if someone still looking simple decision:
`import MarkerClusterer from '@google/markerclusterer';`
