### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by riorulzz** [istarkov/google-map-react#274]
Is there a way to convert clientX, clientY or any other property that we get as part of mouse event to LatLng on Map.. 
I need to drag a marker/div from an area outside of map and detect its LatLng once when dropped.

**Comment by istarkov** [comment]
You need 
1) [world2LatLng](https://github.com/istarkov/google-map-react/issues/62#issuecomment-157183002)
2) inverse version of `world2Screen` aka `screen2World` from this comment https://github.com/istarkov/google-map-react/issues/62#issuecomment-157181739

All other math is simple, convert screen coordinates into world, convert world into `lat`, `lng`

**Comment by istarkov** [comment]
PS: inverse is simple - just replace multiply with divide

**Comment by riorulzz** [comment]
`static world2LatLng({ x, y }) {
      const n = Math.PI - 2 * Math.PI * y;

      // TODO test that this is faster
      // 360 * Math.atan(Math.exp((180 - y * 360) * Math.PI / 180)) / Math.PI - 90;
      return {
        lat: (180 / Math.PI * Math.atan(0.5 * (Math.exp(n) - Math.exp(-n)))),
        lng: x * 360 - 180,
      };
    }`

`static screen2World(obj, zoom){
        var {x, y} = obj;
        const scale = Math.pow(2, zoom);
        return {
          x: x /( scale * 256), // 256 = 256,
          y: y /( scale * 256 )
       }
    }`

Is this implementation correct ?
I found incorrect latLngs after quick testing ..

**Comment by istarkov** [comment]
Be explicit, what input gives incorrect results

**Comment by istarkov** [comment]
Also don't forget to add to calculus upper left corner in screen or in world coordinates. Otherwise all your screen coordinates is around 0,0 point

**Comment by riorulzz** [comment]
adding upper left corner solved the problem .
Thanks a lot for your help :)
