### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by raphaguasta** [istarkov/google-map-react#276]
Hello!

Is there any method to cache the map?

Some way that in the second time that I open the map, can this second load came from the cache?

Thanks! ;)

**Comment by istarkov** [comment]
1st load of what? 
What means cache map?

**Comment by raphaguasta** [comment]
Hello @istarkov! My fault, I updated the comment..

I mean.. When I open the map for the second time, we have any way to get this map from the cache?

Sometimes would be better if the user didn't reload the map from the API every time.

Is it possible?

**Comment by istarkov** [comment]
gmap tiles is taken from the cache. Scripts also. 
Just open network tab in devtools and see there.

So I can't get the question ;-)

**Comment by raphaguasta** [comment]
Ok. I'll verify. Thanks!! :)
