### ISSUE TITLE
Documentation on experimental flag

### ISSUE THREAD

**Issue by alex-e-leon** [istarkov/google-map-react#277]
@istarkov What's the status on the experimental flag? It's been 4 months since that update, is it ok to use in production?

Rendering large amounts of markers has performance issues when the marker events are triggered

**Comment by istarkov** [comment]
I Still have no opinion about, it works good mostly for dev builds, and even I see some performance gains at Release builds, can't say that I will prefer this flag over standart way.
So it can be removed.

**Comment by istarkov** [comment]
Locally I have versions with grouping support, there markers split on groups, so updates is propagated just for group, and not for all, BTW api is so bad now so I cant release it.

**Comment by jooj123** [comment]
@istarkov we see a big jump in performance if this is used when there is many SVG markers on the map

**Comment by alex-e-leon** [comment]
@istarkov It looks like the only thing the experimental flag is doing is enabling a `shouldComponentUpdate` on `google_map_markers`. Is there a reason you wouldn't want to have a shouldComponentUpdate method running?

It looks to me like there's no reason for the flag at the moment.

**Comment by istarkov** [comment]
This part is the difference
https://github.com/istarkov/google-map-react/blob/7ae63cb3d733b91ef14332ed52dd38b5886459f5/src/google_map_markers.js#L62-L65

Having that flag is experimental let's don't think about it's nature and
other things ;-)

**Comment by alex-e-leon** [comment]
I must have been half asleep when I was reading the code last time, I totally missed the other return value.

That said, here's an example of the performance benefits we're seeing with the flag turned on vs off:
Note that with the experimental flag turned on there are no react updates called on hover.
![experimental](https://cloud.githubusercontent.com/assets/7065873/20249993/54771352-aa5a-11e6-8a61-6eba86babec9.gif)
![non-experimental](https://cloud.githubusercontent.com/assets/7065873/20249994/54777ab8-aa5a-11e6-9d95-f9a45f823080.gif)

**Comment by itsmichaeldiego** [comment]
@alex-e-leon Is there something I can help here? I am closing the issue as for now as it seems you could make it work, but please re-open if you need further help Alex!

**Comment by alex-e-leon** [comment]
@itsmichaeldiego It looks like the experimental flag is still available and undocumented. I ended up successfully using it to increase performance in my application, so there's no work required from me, but I think that it could be useful for other consumers to know about the flag, or for the experiment to be finished up and turned into default behaviour so that the performance improvements are made available to everyone.

**Comment by itsmichaeldiego** [comment]
That sounds good @alex-e-leon, it seems that you know more about the experimental flag than me, would you mind adding simple documentation in `DOC.md`?

**Comment by alex-e-leon** [comment]
Unfortunately @itsmichaeldiego I don't really remember too much about this ticket/flag, so I probably won't be of much help.
