### ISSUE TITLE
Editable Polyline doesn't work.

### ISSUE THREAD

**Issue by RubashkoM** [istarkov/google-map-react#280]
Hi Ivan.
On my current project used your component for adding markers and it works fine, thank you for that. But now I should add ability to draw routes, and for that I use Polylines with editable option. The problem is that middle points on Polyline is not available. Can you fix it?

**Comment by RubashkoM** [comment]
I fix that problem by adding zIndex option to Polyline.

**Comment by jabidof** [comment]
Hi,
I'm drawing polyline, circles and other SVG using this lib. You say you use

> Polylines with editable option

; can you detail what you mean by 

> editable

Are they editable on the map?

Thanks for sharing,
J.

**Comment by RubashkoM** [comment]
Here is about [editable option](https://developers.google.com/maps/documentation/javascript/reference#PolylineOptions).
If you set that option 'true', than you can edit polyline on map.
Here you can see [example](https://developers.google.com/maps/documentation/javascript/examples/delete-vertex-menu).

**Comment by jabidof** [comment]
Hi
Thanks for sharing.
Actually I thought you were generating raw svg with editable vertex. 
In my case i need to draw zones on the map that can be edited directly on the map. I want to avoid using google maps api.
Enjoy the weekend 
J.
