### ISSUE TITLE
Do this component have support for drag childs (a.k.a. markers)?

### ISSUE THREAD

**Issue by edcolcode** [istarkov/google-map-react#286]
Hello all,

**First this is not an issue.**
I'm using this component and I feel it is amazing, I'm a newbie but enthusiast in React things. I want to create child (marker) with the capability of be draggable. I tried to follow the source code to check it could be possible but I didn't get any hint.

Any hint or help?

**Thanks a lot :)**

**Comment by istarkov** [comment]
Please read this https://github.com/istarkov/google-map-react/issues/59

**Comment by edcolcode** [comment]
Thanks a lot @istarkov
