### ISSUE TITLE
How to get only visible markers 

### ISSUE THREAD

**Issue by Matol66** [istarkov/google-map-react#289]
Hi,

I tried to get all markers id or coords of markers in current map viewport but i failed.

I tried to use onChange handler but cant access to markers coords from this point. Got only current bounds.

I'm working with map clusters

Need help with this

**Comment by istarkov** [comment]
It is your markers, your ids, your coordinates, and all u need is just to detect is point in rectangle (bounds) .
I cant get your problem

**Comment by Matol66** [comment]
I couldn't get detect those point in rectangle - As you wrote. I tried to write a func for that but finally I used withPropsOnChange to get all visible markers coords. Is this approach is correct for that?

**Comment by istarkov** [comment]
> I couldn't get detect those point in rectangle

Why?

> Is this approach is correct for that?

For what?

---

IMO it's unclear what you want and why are you asking this question here.

**Comment by Matol66** [comment]
I've just get deeper in your code, everything is there so no problem and there is no problem to get what i want.

Thanks for great lib. 

All best for you.
