### ISSUE TITLE
Map fails to render properly when DOCTYPE is declared

### ISSUE THREAD

**Issue by RobAWilkinson** [istarkov/google-map-react#29]
If `DOCTYPE` is declared in the html, map fails to render, when `DOCTYPE` is removed it works fine.

**Comment by jedwards1211** [comment]
Must be a standard/quirks mode issue, though I'm not sure what exactly...

http://stackoverflow.com/questions/9080575/google-map-api-doesnt-work-when-doctype-declared-in-chrome-and-firefox
