### ISSUE TITLE
Pass on inline style to the marker holder

### ISSUE THREAD

**Issue by szchenghuang** [istarkov/google-map-react#290]
I need to customize the marker holders. For now I set prop `$markerHolderClassName` that is passed onto the marker holder and set CSS for the class.

However I think it would be handy to pass on an inline style prop, perhaps `markerHolderStyle`. How do you like it?

**Comment by itsmichaeldiego** [comment]
@szchenghuang I believe its better to use classes than inline styles in this case. Also, this is very low priority, we will be re-thinking the marker logic soon as we're facing some issues. Thanks for the comment!
