### ISSUE TITLE
TypeError: Cannot read property 'lat' of undefined

### ISSUE THREAD

**Issue by undermuz** [istarkov/google-map-react#293]
The error occurs when you use "fitBounds" with "ne" and "sw"

```javascript
import { fitBounds } from 'google-map-react/utils'
const size = {
                width: $( this.refs.mapWrapper ).width(),
                height: $( this.refs.mapWrapper ).height()
            }

const bounds = {
                ne: {
                    lat: NorthEast.lat(),
                    lng: NorthEast.lng()
                },
                sw: {
                    lat: SouthWest.lat(),
                    lng: SouthWest.lng()
                }
            }

const {center, zoom} = fitBounds(bounds, size)
```
In the folder with the module in the code I do not see the code for such a case, although it is in the readme:
http://joxi.ru/KAx91RZuMZlZJr

At the same time, I see support for such behavior here:
https://github.com/istarkov/google-map-react/blob/master/src/utils/utils.js

**Comment by istarkov** [comment]
What version of library do u use?

**Comment by undermuz** [comment]
@istarkov 
my dep: "google-map-react": "^0.21.5"

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/pull/287#issuecomment-263983131
Not last ;-)

**Comment by undermuz** [comment]
ok, sorry for issues)
