### ISSUE TITLE
Calculating bounds by viewport, zoom, and center

### ISSUE THREAD

**Issue by 3plusalpha** [istarkov/google-map-react#294]
I dived into this topic for a few hours as I couldn't find any ready made code for it. So I wrote my own and would like to contribute it here.
@istarkov are you interested to have a look (and possibly integrate it)? :)

**Comment by istarkov** [comment]
We have inverted public method `fitBounds` which provides `zoom` and `center` having `bounds`. It's needed for tasks like to show all markers on the screen etc.

Internally bounds are already calculated and passed via `onChange` callback, 
it's a simple math and I'm not sure it's needed, as it can be written easily. 

I wrote in a few topics all the math user needs to work with map coordinates for example here https://github.com/istarkov/google-map-react/issues/62#issuecomment-157181739

**Comment by 3plusalpha** [comment]
Yes, I know this method and always needed the inverted version of it to calculate if a set of map pins will be visible before passing them to the google map react component. This is quite handy when displaying a result list next to the map. You already know upfront, which pins are visible on the map and render the list, without waiting for google map (and detecting somehow the pins).

But I would also agree to move the calculations into a separate npm package to make it available to other google map implementations (if there is any).

**Comment by istarkov** [comment]
May be `mapbox` has something like such library available. 
For now I think how to remove all that existing API today ;-) 
as from small and easy to use API at the beginning, current looks like a monster ;-)

**Comment by 3plusalpha** [comment]
I see your point. Maybe move it into a separate package, that does some calculation we miss in the google map API. I could/would contribute my calculations to it.
I will check out ```mapbox``` too.

**Comment by istarkov** [comment]
Feel free to add a link into readme here when such library will be available

**Comment by wang3g** [comment]
Hi,  I m stuck on the bound calculation. Say we have the lat/lng of a central point, viewport size (width and height in pixel) and zoom value, how do we calculate the coordinates (lat/lng) of NW and SE of that viewport? What is the formula of calculation? Thanks a lot!

**Comment by itsmichaeldiego** [comment]
@wang3g @3plusalpha Let me know if this is helpful: https://github.com/istarkov/google-map-react/issues/512#issuecomment-366352763

If this is still an issue, please open a new issue and we will take care of it, thanks in advance.
