### ISSUE TITLE
Markers position in fullscreen mode

### ISSUE THREAD

**Issue by nitroin** [istarkov/google-map-react#296]
Enable fullscreen control and control position with `options` prop:

```
const options = {
    fullscreenControl: true,
    fullscreenControlOptions: {
        position: 10
    }    
};

<GoogleMap
    center={this.props.center}
    zoom={this.props.zoom}
    options={options}
    >
    {this.renderMarkers()}
</GoogleMap>
```

**Expected:**
- [x] A React component should render with proper control for fullscreen mode, with markers in the correct position.
- [x] A click on the fullscreen control should render the component in fullscreen.
- [ ] Markers are correctly positioned while in fullscreen mode.

**Comment by freecates** [comment]
Hi @nitroin , is this solved?

**Comment by viperfx07** [comment]
> Markers are correctly positioned while in fullscreen mode.

still waiting for this to be fixed

**Comment by istarkov** [comment]
@viperfx07 having that I'm not using this feature in any of my projects, I'm not interested to somehow fix it. Its opensource project, you are welcome to fix.

**Comment by thg303** [comment]
I'm using version 0.31.0, problem still exists. markers do not move in fullscreen mode.

**Comment by itsmichaeldiego** [comment]
@thg303 Please upload a snippet reproducing the issue, thanks
