### ISSUE TITLE
bootstrapURLKeys seems to be not working

### ISSUE THREAD

**Issue by m1lwoj** [istarkov/google-map-react#298]
There is an error during processing the map,

I pass the key in given format to google-map-react component

**bootstrapURLKeys={{key: 'mygooglemapkey'}}**

As a result i still get the error _Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error_

**Comment by istarkov** [comment]
What is the query string u use to load google map without react? As key prop name depends on your google access rights

**Comment by istarkov** [comment]
And be sure it working, as I use it in a lot of different projects

**Comment by m1lwoj** [comment]
Sample script src which works correctly to me (key is changed)

<script src="https://maps.googleapis.com/maps/api/js?key=BIzaSyCGWacdqQ5XH1yjUxsqdgt6K5YNQM31iY3&callback=initMap"
    async defer></script>

**Comment by m1lwoj** [comment]
Definitely my mistake, I was loading google maps script twice.
