### ISSUE TITLE
API Issue with searchbox

### ISSUE THREAD

**Issue by bawpcwpn** [istarkov/google-map-react#299]
When adding the searchbox as per the readme, I get the following API key error when I try to search something:

_This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_ For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key_

Any idea what could possibly cause that? The specific service is the AutocompletionService.GetQueryPredictions:2

Thanks for any help!

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react#bootstrapurlkeys-object

**Comment by bawpcwpn** [comment]
Thanks @istarkov - this is how I have the component configured

`<GoogleMap
                                            bootstrapURLKeys={{
                                                key: 'MY_KEY_HERE',
                                                libraries: "places"
                                            }}
                                            defaultCenter={{lat: 58.390278, lng: 13.846121}}
                                            defaultZoom={12}>

                                        </GoogleMap>`
