### ISSUE TITLE
Invoking a fitBounds on initialization

### ISSUE THREAD

**Issue by dmitry** [istarkov/google-map-react#3]
How to execute a method `fitBounds` once the map object initialized?

Where am I so far (terribly wrong, but most of the time works):

```javascript
  render() {
    var center = [59.938043, 30.337157];
    var zoom = 8;

    return (
      <div className="search-map">
        <GoogleMap
          center={center}
          zoom={zoom}
          ref="googleMap">
          {this.renderMarkers()}
        </GoogleMap>
      </div>
    );
  },
  componentDidUpdate() {
    var map = this.refs.googleMap.map_;
    if (map) {
      var maps = this.refs.googleMap.maps_;
      var bounds = new maps.LatLngBounds();
      each(this.props.places, (place) => {
        var latLng = new maps.LatLng(place.lat, place.lng);
        bounds.extend(latLng);
      });
      map.fitBounds(bounds);
    }
  }
```

Most of the time it works, but sometimes an update happens before the map mounted, or in other words `googleMapLoader` is resolved.

I believe the correct solution is to invoke `props` callback in `componentDidMount` `GoogleMap` component.

**Comment by istarkov** [comment]
It's not a good idea to use internal private variables. 
And also i don't want to expose google api for many reasons. 

There is [Geo class](https://github.com/istarkov/google-map-react/blob/master/src/utils/geo.js) inside, which i can expose to users. 
But you can import it now `import Geo from 'google-map-react/modules/utils/geo.js';` 

Using Geo class it is easy to write your own fitBounds function without `google api`.  

After you can calculate `center` and `zoom` props in any place of your code like
const {center, zoom} = fitBounds(mapWidth, mapHeight);

**Comment by istarkov** [comment]
You can twek fitBounds realization from this code https://github.com/mapbox/mapbox-gl-js/blob/65d0d6d9b15d9e2fa7da6aa55601465b2bb74f94/js/ui/camera.js

**Comment by dmitry** [comment]
@istarkov thank you for the quick response. What are the main reasons not to expose google API? Isn't it easier to reuse native classes and methods, rather than introducing them into a library. What benefits I can see so far:

- less bugs
- more features
- less code to bundle

**Comment by istarkov** [comment]
**The first reason is**
The first versions of this library was written not for google api but for great [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js). And in some internal projects i still use `mapbox-gl-js`.
As you see in code `Geo class` is copy paste from `mapbox-gl-js` library. There is their [LICENCE](https://github.com/istarkov/google-map-react/blob/master/src/utils/lib_geo/LICENCE.txt) in code.

Some times later i will publish `mapbox-gl-js` react library with same API as now. And it will be easy for everyone switch from one library to another. It will be impossible if i expose `google api` for everyone.

**The second reason is**
**Bugs** - the more api users can use - more bugs users can get.

**Comment by dmitry** [comment]
Seems reasonable. Looks like it may be easily adopted later to leaflet or something similar.

**Comment by raulmatei** [comment]
Hi,

I have the same issue, I'm trying to use fitBounds to make all markers visible on the map, this should happen only on page load - which means that I should be able to remove bounds_changed,
center_changed, zoom_changed events handlers, and reattach them after fitBounds finishes execution. Those events are used to trigger some actions that filter a list of results.

Is the fitBounds going to get into the public API any time soon?

Thanks!

**Comment by raulmatei** [comment]
@istarkov - do you have any news on this one? Thanks.

**Comment by istarkov** [comment]
I'll add this feature in next few days

**Comment by raulmatei** [comment]
:+1: sounds good

**Comment by istarkov** [comment]
Add `utils` functions, with `fitBounds` and other functions
Use fitBounds to get zoom and center.

Usage example:

```javascript
  import { fitBounds } from 'google-map-react/utils';

  const bounds = { 
    nw: {
      lat: 50.01038826014866,
      lng: -118.6525866875,
     },
     se: {
      lat: 32.698335045970396,
      lng: -92.0217273125,
     },
  };
  
  const size = {
    width: 640, // Map width in pixels
    height: 380, // Map height in pixels
  };

  const {center, zoom} = fitBounds({nw, se}, size);
```

**Comment by RBdevelop** [comment]
How would you approach setting   `bounds` from markers generated from our db rather than specifying the exact lat and lng for `nw` and `se`

**Comment by yrik** [comment]
What is the best way to get `nw`, `se` from set of markers?

**Comment by manuj545** [comment]
I am trying to use fitbounds to work. 
using following code 
`const bounds = {
            nw: {
                lat: 30.4646593,
                lng: -97.74710249999998
            },
            se: {
                lat: 37.6239079,
                lng: -122.38159239999999
            }
        };

        const size = {
            width: 640, // Map width in pixels
            height: 380, // Map height in pixels
        };

        const {center, zoom} = fitBounds(bounds, size);`
But i am getting **Uncaught TypeError: (0 , v.default) is not a function** on the fitBounds call in the browser.
does someone have any idea, what am i doing wrong ?

**Comment by robbielane** [comment]
What is the size of the map is dynamic?

**Comment by ng-hai** [comment]
> What is the best way to get `nw, se` from set of markers?

**Comment by istarkov** [comment]
@ng-hai You can use fitBounds method in current library and a simple algorithm to find bounds of points set.
The only problem you need to solve in such algorithm is zero meridian problem as you can have real interval of point be across zero meridian
Like  ***__________________*** where * is a point and here real `lng` interval is not `0-360`

**Comment by istarkov** [comment]
Fast and dirty realization and please no questions about as I will not answer

```javascript
import { sortBy } from 'lodash';
import { fitBounds } from 'google-map-react/utils';

// Here world is a tube
const findZoomAndCenter = (
  {
    size,
    center: defaultCenter = { lat: 35.689, lng: 139.741 },
    zoom: defaultZoom = 10,
    zoomBounds = { min: 3, max: 17 },
  },
  points
) => {
  if (size === undefined) return { center: defaultCenter, zoom: defaultZoom };
  if (points.length === 0) return { center: defaultCenter, zoom: defaultZoom };

  // to not write additional logic for one point
  const eps = 0.0001;

  const pointsNorm = points
    // convert all that latitude longitude
    .map((pt) => ({
      ...pt,
      lat: pt.lat !== undefined ? pt.lat : pt.latitude,
      lng: pt.lng !== undefined ? pt.lng : pt.longitude,
    }))
    // add bounding box corners to points
    .reduce((r, pt) => {
      r.push(pt);

      if ('leftTopLatitude' in pt) {
        r.push({
          ...pt,
          lat: pt.leftTopLatitude,
          lng: pt.leftTopLongitude,
        });

        r.push({
          ...pt,
          lat: pt.rightBottomLatitude,
          lng: pt.rightBottomLongitude,
        });
      }

      return r;
    }, []);

  const { lat: latFirst, lng: lngFirst } = pointsNorm[0];

  const { nw, se } = pointsNorm
    .reduce(
      ({ nw: ptNW, se: ptSE }, { lat, lng }) => ({
        nw: {
          lat: Math.max(ptNW.lat, lat + eps),
          lng: Math.min(ptNW.lng, lng - eps),
        },
        se: {
          lat: Math.min(ptSE.lat, lat - eps),
          lng: Math.max(ptSE.lng, lng + eps),
        },
      }), {
        nw: { lat: latFirst, lng: lngFirst },
        se: { lat: latFirst, lng: lngFirst },
      }
    );

  // bounds on the tube can be not as simple {from, to}
  // ____***_____
  // but having zero meridean we could get bounds like
  // **_________*
  // The only idea I have is to use n^(log2(n) + c) algorithm to find such bounds

  // The idea is to find max distance between nearest pts (as I know similar algos always n*log(n))
  // so sorting is good here
  const pointsSorted = sortBy(pointsNorm, 'lng');

  let dist = 0;
  let leftLng = 0;

  for (let i = 0; i < pointsSorted.length - 1; ++i) {
    const d = pointsSorted[i + 1].lng - pointsSorted[i].lng;
    if (d > dist) {
      leftLng = pointsSorted[i].lng;
      dist = d;
    }
  }

  const minInterval1 = se.lng - nw.lng;
  const minInterval2 = 360 - dist;

  // decide what kind of bounds we have
  // this ____***_____
  // or this **_________*
  const bounds = minInterval1 < minInterval2
    ? { nw, se }
    : {
      nw: {
        lat: nw.lat,
        lng: leftLng + dist,
      },
      se: {
        lat: se.lat,
        lng: leftLng + 360,
      },
    };

  const primitiveCenter = {
    lng: (bounds.se.lng + bounds.nw.lng) / 2,
    lat: (bounds.se.lat + bounds.nw.lat) / 2,
  };

  const { center: center0, zoom: zoom0 } = fitBounds(bounds, size);

  const center = zoom0 > zoomBounds.max
    ? primitiveCenter
    : {
      ...center0,
      lng: center0.lng % 360,
    };

  const zoom = Math.min(Math.max(zoom0, zoomBounds.min), zoomBounds.max);

  return {
    center,
    zoom,
  };
};

export default findZoomAndCenter;
```

**Comment by voold** [comment]
Can you give the params of this last function?

**Comment by istarkov** [comment]
@voold No! 
have your read this? `Fast and dirty realization and please no questions about as I will not answer`

**Comment by raubas** [comment]
There is an excellent (IMHO) library for doing Geo-calculations that I use quite frequently, ´http://turfjs.org´

Makes it pretty simple to calculate bounds and such by yourself..! :)

**Comment by valorize** [comment]
Is there a reason, apart from being a hacky dirty solution, to put the function into util within the repo. So pull requests could work that over.

**Comment by itsmichaeldiego** [comment]
I mixed first solution provided by @dmitry here, with `onGoogleApiLoaded` and works like a charm: 

```
const apiIsLoaded = (map, maps, places) => {
  if (map) {
    const bounds = new maps.LatLngBounds();
    places.forEach(({ place }) => {
      const latLng = new maps.LatLng(
        place.coordinate.latitude,
        place.coordinate.longitude,
      );
      bounds.extend(latLng);
    });
    map.fitBounds(bounds);
  }
};

const GoogleMap = props => (
  <GoogleMapReact
    onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps, props.places)}
    bootstrapURLKeys={{
      key: process.env.MAP_KEY,
      language: 'en',
    }}
    options={createMapOptions}
    center={props.center}
    zoom={props.zoom}
  >
    {props.children}
  </GoogleMapReact>
);
```

Thoughts?
