### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by catalinfeier** [istarkov/google-map-react#30]
Hi, first of all, you've done some very nice work with this!
I would like to ask if there is a way to add the search box to the map? Something like here: https://developers.google.com/maps/documentation/javascript/examples/places-searchbox
If it is an already existing option, i must have missed it (sorry if that's the case).

**Comment by jedwards1211** [comment]
It doesn't look like it's an existing option.  However, it shouldn't be difficult to accomplish now, without waiting for changes to this library.

`<GoogleMap/>` doesn't provide access to the internals to do this:
```
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
```

But, that's just layout, you could easily mount the search field on a layer above the map and absolute position it to the right place.

To use the Gmaps search box in a React component would be easy (i'm not sure off the top of my head how to make sure `google.maps.places` is in the namespace though):

```jsx
import React from 'react';

export default class SearchBox extends React.Component {
  static propTypes = {
    placeholder: React.PropTypes.string,
    onPlacesChanged: React.PropTypes.func
  }
  render() {
    return <input ref="input" {...this.props} type="text"/>;
  }
  onPlacesChanged = () => {
    if (this.props.onPlacesChanged) {
      this.props.onPlacesChanged(this.searchBox.getPlaces());
    }
  }
  componentDidMount() {
    var input = React.findDOMNode(this.refs.input);
    this.searchBox = new google.maps.places.SearchBox(input);
    this.searchBox.addListener('places_changed', this.onPlacesChanged);
  }
  componentWillUnmount() {
    this.searchBox.removeListener('places_changed', this.onPlacesChanged);
  }
}
```

**Comment by catalinfeier** [comment]
That actually worker brilliantly (with minor syntax changes), thank you very much. However, in order to make this work:
```javascript
this.searchBox = new google.maps.places.SearchBox(input);
```
I had to add in the index.html for my app:
```html
<script type="text/javascript" src="https://maps.google.com/maps/api/js?libraries=places&sensor=false"></script>
```
Any ideas how to properly import it in the namespace? Is the places library already included somewhere in google-map-react or does it need a separate installation?

**Comment by jedwards1211** [comment]
Looks like that will work perfectly :smile:
You can see [here](https://github.com/istarkov/google-map-react/blob/master/src/utils/loaders/google_map_loader.js#L22) that `google-map-react` checks if the base api is already loaded, and if so, uses it.  So it won't accidentally load a second copy of the library.

**Comment by catalinfeier** [comment]
Alright, i'll leave like that, then. Thanks again. Maybe this could be added as an example here?
Anyways, this can be closed now.

**Comment by matejstrasek** [comment]
Getting `Uncaught TypeError: this.searchBox.removeListener is not a function` here. Any ideas why?

**Comment by kjg531** [comment]
I'm getting the exact same error as @matejstrasek

**Comment by raphaguasta** [comment]
I'm getting the exact same error as @matejstrasek +1

**Comment by hafizio** [comment]
@jedwards1211 How do I place the `SearchBox` on a layer above the map? Right now the `SearchBox` will be dragged when the map is dragged then it'll reposition itself.

Thanks

**Comment by jedwards1211** [comment]
@raphaguasta whoops, I made the wrong assumptions about the Google Maps API, because the way you remove listeners in it is very nonstandard.  This should work although I haven't tested it:

```js
  componentDidMount() {
    var input = React.findDOMNode(this.refs.input);
    this.searchBox = new google.maps.places.SearchBox(input);
    this.searchBoxListener = this.searchBox.addListener('places_changed', this.onPlacesChanged);
  }
  componentWillUnmount() {
    google.maps.event.removeListener(this.searchBoxListener);
  }
```

**Comment by jedwards1211** [comment]
@istarkov do you have any idea how to put the `SearchBox` on a layer above the map, like @hafizio  is asking?  Unfortunately I don't really use this library anymore.
I think using `new google.maps.places.SearchBox` on a React `ref` was probably bad advice, since it would move the input away from where React expects it to be...probably best to do whatever one would do with just the Gmaps API and no React, and then possibly update the input in the `render` method

**Comment by istarkov** [comment]
I just use geo api services directly, with react-select and similar controls. There is no need to couple map and search service.

**Comment by istarkov** [comment]
Ps: I even have no idea about what SearchBox this discussion :-)

**Comment by diegolaciar** [comment]
Hi,

The search box works great.

Question: How can I do to update the map location and put a place mark on the selected location from the search box?

@istarkov thanks for this awesome project.

**Comment by diegolaciar** [comment]
OH, my bad I see the 
    onPlacesChanged: PropTypes.func

**Comment by cmwint** [comment]
Can anyone provide a full example of how to implement the search box please? The SearchBox component plus the GoogleMaps component? I don't understand how to tie them together.

**Comment by Aphsai** [comment]
Drop this as a child of GoogleMaps: 
 ```
       <SearchBox
          placeholder={"123 anywhere st."}
          onPlacesChanged={this.handleSearch} />
```

and you'll probably have to change the header to something like this:

```
import PropTypes from 'prop-types';

export default class SearchBox extends React.Component {
  static propTypes = {
    placeholder: PropTypes.string,
    onPlacesChanged: PropTypes.func
  }
...
```

**Comment by cmwint** [comment]
@Aphsai this is great. Thank you!!

**Comment by taylorj91** [comment]
It would be great to have @Aphsai 's example of usage included in the main docs for Search Box.  Not sure if this is the place to request it or not.

**Comment by kannan007** [comment]
Can someone make this as fiddle or codepen and share it here

**Comment by itsmichaeldiego** [comment]
@taylorj91 Yes, you can create an issue and request that, and we will add it to google-map-react-examples!

**Comment by xcjackpan** [comment]
@aphsai thanks!!
