### ISSUE TITLE
Readme references MyGreatPlace, without an example.

### ISSUE THREAD

**Issue by aaronmader** [istarkov/google-map-react#300]
From the readme, section: [What's it Look Like?](https://github.com/istarkov/google-map-react#whats-it-look-like) 

    import MyGreatPlace from './my_great_place.jsx';

But this file doesn't exist within the repository. Perhaps the readme/examples could include the declaration of this expression, so new users aren't stranded with an example that can't compile?

**Comment by rob-blasetti** [comment]
+1

**Comment by alan345** [comment]
+1

**Comment by solancer** [comment]
+1

**Comment by sudhirbitsgoa** [comment]
+1

**Comment by itsmichaeldiego** [comment]
@aaronmader @rob-blasetti @alan345 @solancer @sudhirbitsgoa This issue is outdated, Readme has been improved, please feel free to share your feedback, thanks!
