### ISSUE TITLE
How to prevent click on marker under another one?

### ISSUE THREAD

**Issue by vilkoalexander** [istarkov/google-map-react#301]
There are to markers. One is under another one. When I hover the lowest one I change its z-index and make it higher. But when I click on it click event fires on marker that has been the highest one at the beginning.

**Comment by istarkov** [comment]
Use https://github.com/istarkov/google-map-react#onchildclick-func

**Comment by vilkoalexander** [comment]
@istarkov I used it. But like I said before, it works wrong when there are some elements overlaps each other. Click triggers on wrong element. 
A workaround is handle native React event onClick. If I use this approach event fires on element with the biggest z-index.

**Comment by istarkov** [comment]
If you use your logic for for hovering like using not internal algorithm for hovering like in examples it's on you to resolve what child is hovered now.

**Comment by istarkov** [comment]
So just use usual `onClick` events on your markers for example

**Comment by vilkoalexander** [comment]
Or this [function](https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_distance_hover/distance_hover_map_page.jsx#L31)? To change z-index of element under another. Not CSS' z-index.

**Comment by istarkov** [comment]
I can't say much without example, BTW here you can use 2 ways of detecting hovering and clicking on the markers, 
1) Use internal hovering, yes distance function, and you will get all that onChild* method working,
2) Use your own onMouseEnter-Leave, etc, so no onChild* callbacks will work as expected.
3) Use combination of both methods - BTW non simple algorithm to get it working combining results from both event systems, but in some cases the best.

Having that I use this control a lot at projects I'm really sure that there are no error in click events, 
as click event is called on hovered item internally https://github.com/istarkov/google-map-react/blob/7ae63cb3d733b91ef14332ed52dd38b5886459f5/src/google_map_markers.js#L104-L107, so the only way you get incorrect results you use some other detection for hovered markers

**Comment by vilkoalexander** [comment]
Here is [example](https://monosnap.com/file/PHfeguAj0uK3Q9dUc2fKg0LITvlQ7o)

In the beginning round marker was under rectangle. When I hover round one I changes its CSS `z-index`. If I use `onChildClick` and click in their overlap area click fires on the rectangle (marker was above round one).  

If I understood right, I have to use some tricky algorithm inside `distanceToMouse` function or do it in my approach with React's `onClick` event.

**Comment by istarkov** [comment]
It's not an example it's just an image ;-) What is the code to change z-index?
In a lot of cases there is no need to use internal hover algorithm, just use usual `onClick` inside your marker as I wrote above. 

Or yes use your distance function which having that markers can have really strange form can be tricky (in most cases no, as marker forms are just rectangles, triangles and circles) and in such case don'y use your own `onMouseEnter = () => changeZIndex()` use internal `onChildMouseEnter`

**Comment by vilkoalexander** [comment]
Very simple code :-)

`.markers-css-class:hover {
  z-index: 1;
}`

Ok. I'll use `onClick` event. I thought maybe it's a wrong way. But looks like, it's a good idea in my case :-)  Thank you.

**Comment by istarkov** [comment]
Internal hovering was created as my boss for unknown reasons hated any kind of clustering on the maps, and having that markers are placed on the map uniformly only in designers images (in real life they try to be in one place ;-)), I had no other choice as usual hover didn't help.

**Comment by istarkov** [comment]
Also please make a look at new docs, there I write about hovering a lot.
