### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by Alex777UAE** [istarkov/google-map-react#302]
Is it expected behavior for server rendering: only child react components are rendered, no google map itself?

To reproduce - you can check [examples](http://istarkov.github.io/google-map-react/map/main/) with disabled JS. Checked both in Safari and Chrome.
Same is happening with my local code.

Thanks.

**Comment by Alex777UAE** [comment]
Perhaps GitHub is not doing server rendering, but same is going on with code from google-map-react-examples repo.
Gone through following steps:

1. git clone
2. npm i
3. NODE_ENV=production npm run build
4. NODE_ENV=production npm run start

Btw, got warning during npm i stage:

    WARNING in ./~/google-map-react/lib/google_map.js
    Module not found: Error: Cannot resolve module 'react-dom' in /Users/alex/Projects/vericost/google-map-react-examples/node_modules/google-map-react/lib
     @ ./~/google-map-react/lib/google_map.js 82:15-35

**Comment by istarkov** [comment]
It is expected, google map api, over which this component build does not support server tile rendering.
Its easy to render them by itself, but google licence  agreement is clear in this case - you are prohibited to use google tiles outside google api.
Im a small developer, so I cant go against rules of such big company :-)

**Comment by valorize** [comment]
Hi @istarkov I don't quite understand your explanation. Are you not using the api to create the tiles looking like 
```
<div style="position: absolute; left: 395px; top: 651px; transition: opacity 200ms ease-out 0s;">
<img style="width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px; max-width: none;" draggable="false" alt=""
src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i6!2i33!3i20!4i256!2m3!1e0!2sm!3i401097718!3m14!2sde!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcy50OjMzfHMuZTpsfHAudjpvZmYscy50OjJ8cy5lOmx8cC52Om9mZg!4e0&amp;token=40484"
</div>
```
?

Isn't it that you either:
a) are using the api: then you can use them (if your on client or server)
b) are not using the api: then you are not allowed (again client as also server side)
?
