### ISSUE TITLE
Draggable Marker

### ISSUE THREAD

**Issue by colinwitkamp** [istarkov/google-map-react#305]
- How can I make the Marker draggable ?

**Comment by istarkov** [comment]
Does github disables search for some people? #59 for example :-)

**Comment by michshat** [comment]
Got it from #59 https://jsbin.com/molerasebo/2/edit?js,console,output

**Comment by andrefox333** [comment]
Anyone ever figured out how to make this work with mobile or any touch devices?

**Comment by mzparacha** [comment]
Yeah I am facing the same issue to work with touch devices. As I am not able to drag the marker. Any update on this please?
