### ISSUE TITLE
Dynamically change draggable property.  

### ISSUE THREAD

**Issue by vilkoalexander** [istarkov/google-map-react#309]
I need to dynamically switch the draggable property.

### The case

There are a marker and an infoWindow as custom react components. `onMouseDown` event on the infoWindow the map's property draggable has to be false and on `onMouseUp` becomes true.

Actually, this is not a problem to do. I added to the InfoWindow component function that calls to the parent component (the map) and rerender draggable property changes to the one that I need. If output to the console `isDragAllow` property at the time of rendering, it is the value that I need.

The Map component looks like that. 
`<GoogleMap draggable={ this.state.isDragAllow }>{ Markers }</GoogleMap>`

### The problem
Although the value of which I bring to the console such as I need to, in fact, until I move cursor out of the infoWindow remains the possibility of drag. In other words, when `onMouseDown` fires and till cursor is above the infoWindow `isDragAllow` is still true.

**Comment by istarkov** [comment]
Any example? I use dragable property a lot, and see no problems, and cant get your problem

**Comment by vilkoalexander** [comment]
Here is a [link](https://gist.github.com/vilkoalexander/600422ce9d0b52fa36f3a369be727266) to code example.

Once again. Draggable property changes only when mouse leaves a component.

**Comment by istarkov** [comment]
It's too late to prevent dragging at click event, mouse down is already occurred, the drag process is already started so can't be interrupted.
Your problem is easily solvable - just switch `draggable` property at marker mouse enter.

**Comment by vilkoalexander** [comment]
Hmmm. I've thought about it before but I refused this way. Because there are some problems with event bubbling. `onMouseEnter` and `onMouseLeave` fires when I hovering the cursor above the component too many times. Ok, I'll review my code and try do solve my problem in the way you said. Thank you for answer.

**Comment by itsmichaeldiego** [comment]
@vilkoalexander Did you find any solution?

**Comment by vilkoalexander** [comment]
@itsmichaeldiego yes, I did. I've rewrote my application using Angular. So I don't have such problems, I have others :)

**Comment by itsmichaeldiego** [comment]
Haha ok @vilkoalexander! Glad you worked it out! Let me know if you need further help!

**Comment by kylecombes** [comment]
I'm having the same problem, except that the `draggable` behavior never seems to change. I'm toggling the value of the prop (successfully) with a button outside of the component, but the map stays draggable even when the prop is `false`. Is there any way to get the behavior to update?
