### ISSUE TITLE
Why require map size in fitBounds?

### ISSUE THREAD

**Issue by isaachinman** [istarkov/google-map-react#312]
So, reading through old tickets, I know the maintainer of this (fantastic) repo doesn't want to expose the Google Maps API directly, because apparently `google-map-react` can also be used with other mapping libraries.

However, the need to explicitly pass the size of the map into the `fitBounds` util provided is quite annoying, given that the comparable Google Maps `fitBounds` doesn't require this. In my own project, I've had to pull in `react-measure` just to accurately get the size of a dynamic map.

Is there room for improvement on this?

Regardless, huge thanks for such a comprehensive mapping component.

**Comment by istarkov** [comment]
`fitBounds` here is independent of map api itself, so it can't use internal knowledge of map size.
Having that size is passed via `onChange` callback you can use the size from it.

I dislike the idea of providing methods like `fitBounds` on component `ref` itself, I also think to move all `utils` and a pack of additional methods outside this library.

**Comment by isaachinman** [comment]
Ah, I didn't know that size was passed into that `onChange` function, cool. This was specifically in regards to a search box triggering a location change via a place geometry from Google directly, so I wouldn't have an opportunity to hook into your methods, I don't think (?).

On an aside, I do agree about moving the utils outside this repo, they are quite useful in and of themselves.

**Comment by isaachinman** [comment]
@istarkov I'll close this issue, then.

Just one other question: is there currently any way to check if a child component is fully visible in the map? If you take a look at AirBnb's search, they have small map markers, which are replaced by large search-result-style markers when clicked. They have some fancy positioning going on that will pan the map to encompass these larger markers if needed. I need to create similar functionality in my own application.

Any ideas?

I could see how it would hypothetically be possible to pass around refs of children and the parent map component and then check for intersection, but then I'd have no idea how to compare the size of the child in pixels to the lat/lng adjustments necessary to pan the map to encompass it.

Hopefully there's a nicer way of doing this?

**Comment by istarkov** [comment]
I haven't seen airnbnb, 
here http://istarkov.github.io/google-map-react/map/main/ markers are clickable may be it's what you need.
To check that marker is visible just get it bbox in lat, lng and check that it's fully inside map bounds.

Math from utils and issues like this https://github.com/istarkov/google-map-react/issues/62#issuecomment-157181739 will help.

**Comment by istarkov** [comment]
Other way just check position in screen coordinates like here https://github.com/istarkov/google-map-thousands-markers/blob/master/src/controls/Markers/TooltipMarker.js#L72-L74

**Comment by isaachinman** [comment]
Okay cool, I will check that stuff out and figure something out. Cheers!
