### ISSUE TITLE
Display multiple locations on the map

### ISSUE THREAD

**Issue by Ravindra7284** [istarkov/google-map-react#315]
Hi can you anyone guide how we can show the multiple locations on the map ,I am trying to do it but its not working,I am putting bellow code to put multiple locations
 center={[{lat: 21.883851754,
      lng: -159.465845879},{lat: 21.883851754,
      lng: -159.465845879}]}

**Comment by istarkov** [comment]
WTF this mean - multiple location?

**Comment by Ravindra7284** [comment]
multiple location means show multiple pins in single map. shown in image

![multiple_pins](https://cloud.githubusercontent.com/assets/1997206/22704355/6dc8124a-ed8d-11e6-8c92-4e37ca7ccd82.png)
![Uploading multiple_pins.png…]()

**Comment by paranoico** [comment]
You can check the simple example:
https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_simple/simple_map_page.jsx

It shows two points, basically points are constructed using another component.

The syntax you are using only gets one latitude and one longitude. So, thats why it does not work.

**Comment by istarkov** [comment]
I cant get your question at all, almost all examples are showing multiple markers, one of the examples even shows 10 000 markers on the map, so what are u really need?
