### ISSUE TITLE
Component doesn't appear to load in chrome extension content script

### ISSUE THREAD

**Issue by brandonmp** [istarkov/google-map-react#318]
I'm trying to use in a `content` script in a Chrome extension.  Basically this is just html/js/css that the extension injects into certain pages.

I use the `google-map-react` successfully in my SPA, so I  am familiar with the API.

The error(s) are:

````
js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:103 
Uncaught Yc
  message: "_$_google_map_initialize_$_ is not a function"
  name: "InvalidValueError"
  stack: "Error↵    at new Yc (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:55:363)
    at Object._.Zc (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:55:473)
    at Yg (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:103:420)
    at https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:141:58 
    at Object.google.maps.Load (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:21:5)
    at https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:140:20
    at https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:141:73"__proto__: ErrorYg @ js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:103(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:141google.maps.Load @ js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:21(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:140(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=<API KEY REDACTED>&language=en:141
google_map_loader.js:65 

Uncaught (in promise) Error: google map initialization error (not loaded)(…)
  (anonymous function) @ google_map_loader.js:65
  callback @ script.js:48
  el.onload.el.onerror.el.(anonymous function) @ script.js:82
````

I initially tried loading the google Maps API via a `script` tag in the `.html` root of my `content script`, butr it resulted in the same error .

My component now, using `bootstrapURLKeys`:

````
const MapPanel = (props) => {
  return (
    <div>
      <GoogleMap
        defaultcenter={{ lat: 59.938043, lng: 30.337157 }}
        defaultZoom={9}
        bootstrapURLKeys={{
          key: '<API KEY REDACTED>',
          language: 'en'
        }}
      />
    </div>
  )
}
````

Lastly, when the error throws, I am fully able to access `google.maps` in the Chrome Console, so the library is loading correctly.  Also, the `script` tag is added to the document `head`, as well as 3 other script:

````
<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/27/12/common.js"></script>
<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/27/12/util.js"></script>
<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/27/12/stats.js"></script>
````

I looked at https://github.com/istarkov/google-map-react/blob/master/src/utils/loaders/google_map_loader.js , but it's not obvious to me what the problem could be. 

Anyone have any ideas?

**Comment by brandonmp** [comment]
I wanted to add: my chrome extension `manifest` includes `https://maps.googleapis.com/maps/api/js` as an authorized `script-src`, so I don't think it's a permissions problem.

**Comment by istarkov** [comment]
Please read https://groups.google.com/forum/#!topic/google-maps-js-api-v3/lPydWBYe1kQ or similar references, and use custom loader,
`googleMapLoader` property
custom loader should have same interface as https://github.com/istarkov/google-map-react/blob/master/src/utils/loaders/google_map_loader.js

(Should return promise which resolves with `google.maps` object)

**Comment by brandonmp** [comment]
thanks @istarkov . I've seen the link you mentioned, but unfortunately it deals only in cases where one wants to modify an existing instance of Google Maps on a page. 

I'm still working out a solution, but it looks like the problem stems from Google Maps always loading on the `window` object & Extension Content scripts being unable to access their parent page's execution context. 

Will close since it's nothing to do with `google-map-react`, but do you know of any way to load google maps other than via the `script` tag? I'm finding even the async loaders (like `script.js`) use `script` tags under the hood.
