### ISSUE TITLE
How to prevent double click zoom when user click on a marker

### ISSUE THREAD

**Issue by leandrooriente** [istarkov/google-map-react#319]
Hey guys,

I have a map that display some image galleries cards. 

I wan't to prevent the user to zoom in the map when he double click on the gallery navigation (next, previous) but preserving the double click for zoom when its in on the the map.

`disableDoubleClickZoom: true` is not an option. We need the double click zoom on map.

Some gifs explaining what I trying to do.

Expected double click zoom.
![zoomok](https://cloud.githubusercontent.com/assets/1781007/22938069/cb63f21e-f2c1-11e6-9750-fb0d38108d9f.gif)

Unexpected double click zoom
![zoomnotok](https://cloud.githubusercontent.com/assets/1781007/22938077/d013f14c-f2c1-11e6-9620-6b7db8c2a32b.gif)

I already have try some solutions.
`Ref` and `eventListener` on gallery arrow to `stopPropagation`, default `onClick stopPropagation` on arrow, `event.nativeEvent.stopImmediatePropagation()`... but without success.

Any help will be very appreciate

**Comment by demetriusnunes** [comment]
+1

**Comment by istarkov** [comment]
Set `disableDoubleClickZoom: true` in `options` props when you hover the marker.

**Comment by leandrooriente** [comment]
@istarkov it works. 

Thank you very much 😃

**Comment by istarkov** [comment]
Thanks to @alex-e-leon without that [PR](https://github.com/istarkov/google-map-react/pull/215) this workaround will never work ;-)
