### ISSUE TITLE
Right click event

### ISSUE THREAD

**Issue by Xstoudi** [istarkov/google-map-react#321]
Is there any way to get lat and lng of a right click event ?

**Comment by istarkov** [comment]
There are a lot of methods, one of
here https://github.com/istarkov/google-map-thousands-markers/blob/master/src/controls/Map/CanvasMap.js#L97-L104

I convert mouse position into lat lng coordinates

See explanation
```
        // convert into zoom-scale space (screen space without tile size) left top corner
        const ptNW = latLng2Scaled(bounds.nw, zoom);
        // convert mouse delta from left top corner into same space and add with converted corner
        const mpt = vecAdd(ptNW, vecMul(mousePos, 1 / TILE_SIZE));
       // convert point back
        const mptLatLng = tile2LatLng(mpt, zoom);
```

you can simplify this equations into one, or use as is

**Comment by Xychen1994** [comment]
How to get bounds or zoom data?
