### ISSUE TITLE
Map flickers when we have two many markers and map marker data is linked to firebase

### ISSUE THREAD

**Issue by anilreddykatta** [istarkov/google-map-react#322]
What you suggest about handling marker data which is very dynamic. Even when lat & lng data remains constant still map view flickers?

**Comment by istarkov** [comment]
Not sure what are u talking about, please publish example. Or gif or anything

**Comment by anilreddykatta** [comment]
`
/*markers data is linked to a realtime database where data inside marker keeps on changing very rapidly. I see entire google map component flickering(every other marker disappears and reappears for every small change to any marker in markers array) even when lat & lng remains same only data inside markers being changed */
const markers = [{id: '123123': lat: 35.00, lng: 95.01, data: {}}, ....];
<GoogleMap>
     {markers.map(marker => (
        <div lat={marker.lat} lng={marker.lng}>
             <CustomComponent data={marker.data} />
        </div>
     ))}
</GoogleMap>
`
I hope it explains problem.

**Comment by istarkov** [comment]
I'm working with computer graphics also and be sure flicker can mean anything in user mouth.
If you want your problem to be somehow investigated please provide working minimal example - jsbin whatever, I'm pretty sure such information like `Firebase` etc is useless.

What are u want, you want me to create a Firebase db with markers (how many markers) and start doing what? 

Please respect my time. I'll close this until you provide any example.
