### ISSUE TITLE
Chrome saying page is unresponsive

### ISSUE THREAD

**Issue by rohitgupta3** [istarkov/google-map-react#324]
I am not very clear on how to debug this so I thought I would quickly ask first.  After a while of having a page with a <GoogleMap> on it, Chrome puts up a pop-up saying the page has gone unresponsive and should I kill or wait.  The page is NOT unresponsive and I can just dismiss the alert, but I don't know what would be triggering Chrome to think this.

Anyone face a similar problem?

**Comment by GeorgeYing1** [comment]
Same issue here not sure how and why

**Comment by itsmichaeldiego** [comment]
@rohitgupta3 @GeorgeYing1 Please try with latest version and open a new issue if the problem persists.
