### ISSUE TITLE
Application on Production not showing google map

### ISSUE THREAD

**Issue by paranoico** [istarkov/google-map-react#326]
Hello,
I want to congratulate you for this fabulous component.
Now, my problem:
I am embedding google-map-react into Meteor app, and in development environment everything works correctly.
But when started on production, google map simply does not show at all, only markers:
![imagen](https://cloud.githubusercontent.com/assets/16200983/23292705/284bc0da-fa27-11e6-80e5-1fda0cd68245.png)

So I want to ask for someway to debug where the problem is, cannot find anything to dig in, nor any clue about what is happening.

Thanks in advance.

**Comment by istarkov** [comment]
Seems like for unknown reason google map api isnt loaded.
Check does your window object contains google key.
And if it not, seems like some problem with loader,
you can provide your custom and see whats happening
https://github.com/istarkov/google-map-react/blob/master/src/utils/loaders/google_map_loader.js

**Comment by paranoico** [comment]
We got the same behavior on development environment, so I discovered it was an issue after trying to upgrade Meteor to version 1.4.3.1, it seems that some dependencies broke up.

After several tries we re-created project and installed again Meteor and Node dependencies.

Thanks a lot for your support. You were right.

**Comment by paranoico** [comment]
Well seems that I closed issue too quickly.

I confirm the issue again, on Meteor development Google map shows correctly.

On Production, map simple does not load. We will investigate further more.

**Comment by paranoico** [comment]
So after adding some console.log here and there, I discovered that map was created with null center coordinates (!!!).

Map was supposed to get coordinates from database, but those was null. so after setting them everything worked again.

Childish error. Thanks @istarkov
