### ISSUE TITLE
Map not loading - You have included the Google Maps API multiple times on this page.

### ISSUE THREAD

**Issue by jonathandeclan** [istarkov/google-map-react#327]
Map does not load and errors show in console state:

You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

and
 
_$_google_map_initialize_$_ is not a function

Force refresh (Shift+refresh button) will get the map to load.

**Comment by istarkov** [comment]
Your are loading google map api from the other place, use custom loader in such case

**Comment by jonathandeclan** [comment]
In my react component's render function, I am basically calling the map component as shown in the example
`render() {
   
    return (
      <div className="map row">
        <GoogleMap
          bootstrapURLKeys={{key: "<I HAVE KEYED MY API KEY HERE>"}}
          defaultCenter={this.state.center}
          defaultZoom={this.state.zoom}
          onClick={this.onMapClick}
        >        
        </GoogleMap>
      </div>
    );
  }`
I did not include any loading of the google map api in my header scripts / etc. 
Can you explain what is a custom loader and are there examples for it? Thanks in advance
