### ISSUE TITLE
Updating bounds with markers

### ISSUE THREAD

**Issue by ribeiroguilherme** [istarkov/google-map-react#329]
First thanks for this library, it's been very useful. I'm getting an issue when re-renders the map I think. I checked the issue #3 and I'm using that method _findZoomAndCenter_  that works great.
Always when I get new markers to update the map, I pass them by properties to my Map and I want to fit the bounds. In the first time works perfectly, but in the next times that I change the markers, the zoom doesn't change, but the center does. If I put the zoom far, and then get new markers to re-render on the map, the zoom is still far.  I didn't realise what is the problem. 
My map component: https://gist.github.com/ribeiroguilherme/05f374e20dd1336d0fc36cb5dd07966c

Anyone have any ideas?

**Comment by ribeiroguilherme** [comment]
I checked few similar issues here like #87 , but even if I'm handling the onChange, my map doesn't update.
I printed my state before render and it shows the correct zoom value to be used, but the zoom don't change in the map. The same happens to the map center, but it sometimes the map center is changed, sometimes doesn't. Anyone have any ideas?



```
`import React, { Component } from 'react';
import GoogleMapReact from 'google-map-react';
import styles from 'styles/Map.scss';
import MarkerForm from 'components/monitoring/MarkerForm';
import findZoomAndCenter from 'utils/findZoomAndCenter';

const size = {
  width: 1366, // Map width in pixels
  height: 600, // Map height in pixels
};

class Map extends Component {

  constructor(props) {
    super(props);
    this.state = {
      center: { lat: -20.3865167, lng: -43.5084482 },
      zoom: 14,
    };
  }

  componentWillReceiveProps(nextProps) {
    const { center, zoom } = findZoomAndCenter({ size }, nextProps.forms);
    this.setState({
      center,
      zoom,
    });
  }

  shouldComponentUpdate(nextProps) {
    if (this.props.forms === nextProps.forms) {
      console.log('no updates');
      return false;
    }
    return true;
  }

  onMapChange = ({ center, zoom }) => {
    this.setState({
      center,
      zoom,
    });
  }

  render() {
    console.log(this.state);
    return (
      <div className={ styles.container }>

        <GoogleMapReact
          center={ this.state.center }
          zoom={ this.state.zoom }
          onChange={ this.onMapChange }
        >

          {
            this.props.forms.map(form =>
              <MarkerForm
                key={ Math.random() }
                lat={ form.latitude }
                lng={ form.longitude }
              />,
            )
          }

        </GoogleMapReact>

      </div>
    );
  }

}

Map.propTypes = {
  forms: React.PropTypes.array.isRequired,
};


export default Map;
```
`

**Comment by istarkov** [comment]
Publish this on jsbin, and explain what is not working for you using the real ui u will provide

**Comment by ribeiroguilherme** [comment]
Ok, so  you can check at  https://jsfiddle.net/rtgxna2d/4/

If you click on the button, the parent state will be updated and the map should be updated as well.
I realised that if I remove the method _shouldComponentUpdate_, works fine. But I need it to don't allow the map to render if I change other parts of my parent state that isn't related to the map.

I also realised that, even the _shouldComponentUpdate_ returning true after click on that button, my map doesn't update. But if I remove the logic inside it and return always true, works fine.  I'm very confused about what is going on :/

**Comment by istarkov** [comment]
So the problem is not with the library, but with incorrect optimization you use. Just use shouldUpdate carefully, as every optimization can be the source of problems in the future ;-)

**Comment by ribeiroguilherme** [comment]
Definitely isn't the library 👍  Can you tell me what I'm doing wrong? I changed few things but I don't understand why is not working with _shouldComponentUpdate_, even if it returns true.
I updated my jsfiddle ( https://jsfiddle.net/rtgxna2d/7/  ) trying to do some validations in _componentWillReceiveProps_ , but it didn't have any effect. I'm wrecking my head on this, I don't realise why isn't working

**Comment by istarkov** [comment]
In your case the answer is simple ;-)
You set the same center and zoom in `componentWillReceiveProps` as initial
```
      center: { lat: -20.3865167, lng: -43.5084482 },
      zoom: 14,
```
so nothing will change, just change to other value center or zoom and all will work as expected

**Comment by ribeiroguilherme** [comment]
Thanks man! It worked! 🥇  Let me ask you a question. I set the center and zoom at the constructor, but always when I move my map for example, my state is changed and my center/zoom is updated there. Why when I click on the button to update my state with different center/zoom values, my component isn't rendered, even if the values are different?

**Comment by istarkov** [comment]
I'm prefer not to trust textual description. Example?

**Comment by ribeiroguilherme** [comment]
Thanks for the help @istarkov . I sorted the problem.
For whom to be interested: https://jsfiddle.net/rtgxna2d/10/

**Comment by theHinneh** [comment]
Please I want to use your code, but I want to read the location (lat and lng) from firebase and show the markers on the map, as many locations that are in the database.
can you please help me out

**Comment by itsmichaeldiego** [comment]
@theHinneh With this issue and Google Map React, you've everything you need from our side, what you need to figure out is how to use Firebase in a React lifecycle properly so you can render the map, but this is pure JS / React skills, its not related to the library, so I think the right place for your question would be StackOverflow.

**Comment by theHinneh** [comment]
@itsmichaeldiego Thank you. I just started learning react on my own so if you could point out a good place for tutorials.

**Comment by itsmichaeldiego** [comment]
@theHinneh I personally really like https://egghead.io/, but there are many others out there!
