### ISSUE TITLE
Can't install by jspm 

### ISSUE THREAD

**Issue by Crazy-Ivan** [istarkov/google-map-react#33]

**Comment by jedwards1211** [comment]
I haven't read much about jspm yet...just out of curiosity, why are people starting to use it instead of Webpack?  Too many tools

**Comment by istarkov** [comment]
@jedwards1211 
- 1 year before now I used grunt
- 8 monthes bn I used gulp
- last 8 monthes I use webpack
- next N monthes I don't know :-)

**Comment by jedwards1211** [comment]
@istarkov Yeah, I find it pretty frustrating...it really makes me want to see any competitors to Webpack fail
