### ISSUE TITLE
offsetting marker when opening an infowindow

### ISSUE THREAD

**Issue by roura356a** [istarkov/google-map-react#330]
With the default API your infowindow auto-offsets the marker in order to make it fit in the viewport of the map. But since we use custom components as infowindows, Im wondering how to make them fit to prevent it from going out of the map limits.

**Comment by istarkov** [comment]
Hi, in main example all infowindows are fit into the screen, have u seen
that?

**Comment by roura356a** [comment]
Thanks @istarkov, I didn't realised that. Im also playing with the `yesIWantToUseGoogleMapApiInternals`, so things are much easier =)
