### ISSUE TITLE
React Motion as child of GoogleMapReact component breaks marker position

### ISSUE THREAD

**Issue by seleckis** [istarkov/google-map-react#331]
e.g.:
```jsx
render() {
	const offset = 0.00001;
	return (
		<GoogleMapReact {…mapProps}>
			<Motion defaultStyle={{x: lng}} style={{
				x: spring(lng + offset, { stiffness: 300, damping: 26 })
			}}>
				{intStyle => (
					<CMapMarker {...markerProps} lng={intStyle.x} />
				)}
			</Motion>
		</GoogleMapReact>
	);
}
```
This breaks marker position. As I understand `GoogleMapReact` child should have all props to set marker's position. I tried to add markerProps to Motion with no luck. How can I animate marker position? I need to animate lng. Animation inside CMapMarker is not suitable, because if the marker has some offset the click area will not fit the marker.

**Comment by istarkov** [comment]
So having that child of map component should have `lat` `lng` props, there are not a lot of things you can do, 
1) move Motion (TransitionMotion for multiple markers) upper one level, so 

```javascript
<TransMotion>{
  (styles) => 
     <Map>
         iter(styles, style =>
           <Marker lat={style.lat} lng={style.lng} ...
```

2) Move Motion into marker and using lat lng 2 screen transforms animate marker internals.

Method 2 is used at a half of examples to animate scale, but can be used to animate anything. 
(Yes it' will need some additional simple math)

**Comment by seleckis** [comment]
Thank you for your answer.

I provided simplified example. In real I have an array of markers, which are mapped into `<Map>`:
```jsx
<Map>
   {markers.map(marker =>
         <Marker {...marker.properties} />
   )}
```
Some of them should animate, some not. And they could have different animation params.

About method two, I don't understand this part "using lat lng 2 screen transforms animate marker internals". You meen to use css transform? I said that in this case click area of the marker will not fit markers visible position.

**Comment by istarkov** [comment]
Having that you can provide your own distance function https://github.com/istarkov/google-map-react/blob/master/DOC.md#few-markers-with-hover-example-done-right
You can provide any area etc for markers.

**Comment by itsmichaeldiego** [comment]
Please try with latest version and open a new issue if the problem persists.
