### ISSUE TITLE
Invalid prop `center`

### ISSUE THREAD

**Issue by rgrandi** [istarkov/google-map-react#333]
Trying to get this to work but when calling `<GoogleMapReact center={mapCenter} defaultZoom={11} />`, I'm getting the error message as follows:

`Warning: Failed prop type: Invalid prop ``center`` supplied to ``GoogleMap``.`

Any ideas?

I've also tried replacing `center` with `defaultCenter` as per the docs.

**Comment by istarkov** [comment]
Check type of `mapCenter` should be https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L62-L68

**Comment by rgrandi** [comment]
Still having issues with this. Converted the type of `mapCenter` to an array rather than an object and that works, however nothing at all is being rendered. No error messages now though.

```
var mapCenter = [
    lat => "51.4999809",
    lng => "-0.1334745000000339"
];

<div className="map-container" style={{width: '100%', height: '400px'}}>
    <GoogleMapReact center={mapCenter} defaultZoom={11} />
</div>
```

I just get a 400px high empty box with the following markup

```
<div class="map-container" style="width: 100%; height: 400px;">
   <div style="width: 100%; height: 100%; margin: 0px; padding: 0px; position: relative;">
       <div style="width: 100%; height: 100%; left: 0px; top: 0px; margin: 0px; padding: 0px; position: absolute;"></div>
     <div style="width: 50%; height: 50%; left: 50%; top: 50%; margin: 0px; padding: 0px; position: absolute;">
          <div style="width: 100%; height: 100%; left: 0px; top: 0px; margin: 0px; padding: 0px; position: absolute;"></div>
     </div>
   </div>
</div>
```

Any thoughts?

**Comment by istarkov** [comment]
Please learn js :-) in your case lat lng is a lambdas not an object

**Comment by rgrandi** [comment]
Well, I have also tried the following:

```
var mapCenter = [
    {lat: "51.4999809"},
    {lng: "-0.1334745000000339"}
]
```
and 
```
var mapCenter = {
    lat: "51.4999809",
    lng: "-0.1334745000000339"
}
```

with no luck. Its unclear from the documentation exactly how it should be laid out, since when I try to set `defaultProps` in the way that you have done, the JSX does not compile, so I've decided to set it as a variable instead.

I'm new to React and JSX, spent most of my time on jQuery.

**Comment by istarkov** [comment]
Please open examples, trace, learn, this is not the place where I teach people to code. Just library issues.

**Comment by izaacdb** [comment]
https://developers.google.com/maps/documentation/javascript/reference/3/coordinates#LatLng
