### ISSUE TITLE
Get click event of a Child Component under another one

### ISSUE THREAD

**Issue by Titoine** [istarkov/google-map-react#337]
Hi,
First of all, thanks for this wonderful job !

I have a child component for the user position and another one for a place.

![capture](https://cloud.githubusercontent.com/assets/3514286/23860404/2579b6f8-0807-11e7-8ea8-e0f2974a7a31.JPG)

I want to put the user over the place but that a problem because It catch clicks events.
What's the best way to let a click event pass through a child component?

**Comment by istarkov** [comment]
Please read https://github.com/istarkov/google-map-react/blob/master/DOC.md#few-markers-with-hover-example-done-right

`or to return infinite distance` this part

**Comment by itsmichaeldiego** [comment]
@Titoine Let me know if you still need help with this.
