### ISSUE TITLE
Live example is not working when i disable js on browser. means, its not working server side

### ISSUE THREAD

**Issue by rku181** [istarkov/google-map-react#338]

**Comment by istarkov** [comment]
explain what example, whats not working

**Comment by gillescochez** [comment]
I don't get this issue. It's like complaining the light doesn't work after you switch off the electricity of your house.

**Comment by itsmichaeldiego** [comment]
Unexplained issue. I've used this library while doing server-side rendering and it works perfectly. Please create a Codepen or some live example.
