### ISSUE TITLE
How to disable control the Google Map

### ISSUE THREAD

**Issue by XOneto9** [istarkov/google-map-react#339]
Hi,

I use this module of google map react
and I'm display on my web google maps

I want show the view of google maps to do not work click and moving event like as scrollWheel functioning and click event on a Mark. just like photo.

how can I do that???

**Comment by istarkov** [comment]
Have you tried to reread your writing? ;-)
What is `fixed view`?
What is `like as Zoom in/out function`?
What mean `dragging map location`?
What mean `should work to click`?

**Comment by istarkov** [comment]
And be sure to write what you have tried and what the problem, here is not the place to provide the solution of all problems you have, just issues. 
Also help to people who really tried to achieve the goal. Based on you letter I could assume that you did nothing.

**Comment by istarkov** [comment]
May be it will be better for you to use google static maps https://developers.google.com/maps/documentation/static-maps/
?

As it will be just images. No need in any client api code at all.

**Comment by istarkov** [comment]
With current map you can disable controls using options property it is the same as gmap api MapOptions object
https://developers.google.com/maps/documentation/javascript/reference#MapOptions

**Comment by XOneto9** [comment]
@istarkov wow...
amazing ...

really....very fast answer and Thanks to find solution about static maps. 
I have never seen static map. thank!

in the way to use google api, I need more study to this way on this module.
Thank you so much!

**Comment by XOneto9** [comment]
@istarkov Hi, I'm using google maps api with your beautiful module of react-google-maps
I'm now understand how to use it module with api.
but, I have no idea.

I'm using option in google api named by 'scrollwheel' 
as already know you what I want to do, I want to disable control on the map. 

So I use scrollwheel option.. ( actually I have several options of 'draggable', 'zoomControl', 'scalControl' ..etc..)
but just scrollwheel = {false}; option not work. only scroll wheel options not work. any other options very good work.

do you know about why not work scroll wheel option??

**Comment by istarkov** [comment]
It works https://jsbin.com/segopelada/edit?js,output

**Comment by XOneto9** [comment]
@istarkov  Thank you!!!
