### ISSUE TITLE
Google-map does not update tiles while touch-dragging

### ISSUE THREAD

**Issue by majodev** [istarkov/google-map-react#34]
When dragging the map via touch gestures, no new tiles get loaded until the touchEnd event occures. 

Reproduction: Emulate a touch enabled device within Chrome Dev-Tools and drag the map. This is is major bummer if this component gets used within cordova wrapped mobile applications.

Also see http://stackoverflow.com/questions/22403890/google-maps-does-not-update-tiles-while-dragging

**Comment by istarkov** [comment]
Does this real device problem? 
Or just device emulator within chrome?

**Comment by majodev** [comment]
Yes, AFAIK it's the same handling on all touch devices (ios and android), as it's the default handling of the google maps JavaScript API on touch devices (potentially to prevent heavy data loading on mobile?) 

However, it would be cool if your component would provide a way to workaround this (e.g. by forcing a redraw on touchdrag - configurable via a prop - through one of those fixes mentioned in the above stackoverflow thread).

**Comment by istarkov** [comment]
Read this https://github.com/istarkov/google-map-react/issues/31
You can access to google map instance and do all what you want.

**Comment by majodev** [comment]
Ah ok, I thought we should continue to treat the real maps instance as internal and not use it directly. Good to know that this won't break in future releases. 

Great, I'll answer back as soon as I have a proper solution.

**Comment by istarkov** [comment]
It look's like this feature will break in future releases. 
But it will looks like `const inst = await ref.getGoogleMapInstace();`

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react#ongoogleapiloaded-func
