### ISSUE TITLE
Support for marker animation on coordinates change

### ISSUE THREAD

**Issue by eltuza** [istarkov/google-map-react#340]
Hi,
I need track moving objects (cars) in a map, and can't seem to find a way to add smooth transitions to these coordinates changes. 
Adding the transition to the marker wrapper ad-hoc seems to do the trick, but can't find a supported way to do it and react-motion seems to not be of use here.

Is there a way to add that animation that I am missing?

**Comment by istarkov** [comment]
Animate from js, animate marker internals.
https://github.com/istarkov/google-map-react/search?q=animation&type=Issues&utf8=%E2%9C%93

**Comment by eltuza** [comment]
sorry @istarkov, not following. Searched through those issues but can't find a way to animate a  marker from position A to B

**Comment by istarkov** [comment]
1) Animate marker lat lng props - javascript
2) Animate marker content emulating marker moving - css or js

**Comment by eltuza** [comment]
Thanks for the hints!

**Comment by ckim16** [comment]
Does anyone mind providing a simple example for this?

I, too, need to animate marker based on lat&lng change for my own project.

Thanks
