### ISSUE TITLE
Detect click on map but not in marker/infowindow

### ISSUE THREAD

**Issue by roura356a** [istarkov/google-map-react#342]
Im able to detect `onClick` when I click on the map, also `onChildClick` when I click on the marker. But somehow is triggering `onClick` and not `onChildClick` when I click on the infoWindow, which is part of my `<Marker/>` custom component. I want to close the infoWindow when clicking outside it, on the map, like in many websites.

Any idea someone?

**Comment by istarkov** [comment]
1)  intercept mouseenter mouseleave on your infowindow, dont close if clicks are inbeteween
2) use react click outside library (there are a lot such at github,  use search)
and a pack of other solutions

**Comment by roura356a** [comment]
Hmm, if there is no other solution, thats a really good idea @istarkov, thanks for your patience ;)
