### ISSUE TITLE
Google Maps API warning: NoApiKeys

### ISSUE THREAD

**Issue by mostafiz93** [istarkov/google-map-react#344]
I've added google-map-react in my project and was trying the sample snippet. But it shows blank screen when I run. Here is the code snippet:

```
import React, { Component } from 'react';
import GoogleMapReact from 'google-map-react';

const AnyReactComponent = ({ text }) => <div>{text}</div>;

export default class MapComponent extends Component {
  constructor(){
    super();
    this.x = {
      center: {lat: 59.95, lng: 30.33},
      zoom: 11
    };
  }

  render() {
    return (
      <GoogleMapReact
        defaultCenter={this.x.center}
        defaultZoom={this.x.zoom}
      >
        <AnyReactComponent
          lat={59.955413}
          lng={30.337844}
          text={'Kreyser Avrora'}
        />
      </GoogleMapReact>
    );
  }
}

```

It shows following warning in the console:

> Google Maps API warning: NoApiKeys

As per the warning message I've generated API key. But I where to use this API key?

I'm attaching the screenshot for better convenience. 
![google map react](https://cloud.githubusercontent.com/assets/1145582/24081283/1db84492-0cdb-11e7-8313-0232de6a661a.png)

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/blob/master/DOC.md

```
On creation map uses the space of parent container and if parent container has zero height or width the map will be not visible. (This is one of the most common issue)
```

**Comment by mostafiz93** [comment]
Thanks. It works now.
I've `GoogleMapReact` into a container with defined height, width and now it works fine.
