### ISSUE TITLE
only works with api-key, not for client-id

### ISSUE THREAD

**Issue by namezero** [istarkov/google-map-react#347]
please add support to client-id instead of apikey
thanks
https://developers.google.com/maps/documentation/javascript/get-api-key#client-id

**Comment by istarkov** [comment]
It supported, see bootstrapURLKeys

**Comment by itsmichaeldiego** [comment]
@namezero Let me know if passing the client-id in the `bootstrapURLKeys` works or not please! Otherwise I will take a look. Thanks for opening the issue.
