### ISSUE TITLE
Can't Zoom Out all the way into World View

### ISSUE THREAD

**Issue by jm90m** [istarkov/google-map-react#348]
Hey I am trying to use your maps and I need the default state to show the world view. Like this:

![googlemaps-world-view](https://cloud.githubusercontent.com/assets/5067716/24308491/724f1870-109e-11e7-8f33-90865c219ceb.gif)

Right now I am unable to zoom out all the way. Is there a setting that I can pass in to let me zoom out all the way? Thanks.

**Comment by istarkov** [comment]
I prevented such zooming as it causes an interesting problem, in React you have one child but on the map you have few positions to place it. Multiplying markers internally is not the right way IMO as for you its one react component and your logic can depend on that fact. Not multiplying - what the position is correct? So I decider to prevent zooming on levels where u can get such problems. 
Don't think Ill somehow change this. 
BTW as I remember you can off that zoom check please see the code how.

**Comment by jm90m** [comment]
So you're saying that there would be errors if I had multiple markers on the map and I am trying to zoom out all the way? Also I tried finding the zoom check, was it `MaxZoomStatus` ? couldn't find it in google_map.js

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L286-L289

**Comment by jm90m** [comment]
Thank you so much

**Comment by jm90m** [comment]
@istarkov It looks like that is for the minimum zoom, I am trying to be able to zoom out all the way so i would need the max zoom?

**Comment by istarkov** [comment]
It will be faster if you just run the map example and set different zooms ;-)
minimal means - in math minimal not the visible area minimal or any other suggestions

**Comment by jm90m** [comment]
![screen shot 2017-03-28 at 11 30 11 am](https://cloud.githubusercontent.com/assets/5067716/24413600/eecaa514-13a9-11e7-8f2a-b8279a258851.png)

sorry to keep bothering you, I did use the map example and I was trying to set different zooms but the highest I get is still  only this view, when I need to see entire world view

![screen shot 2017-03-28 at 11 31 06 am](https://cloud.githubusercontent.com/assets/5067716/24413639/0b3fe2ea-13aa-11e7-9885-78fa1a385ab2.png)

**Comment by istarkov** [comment]
Please reread this line https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L287
;-)

**Comment by istarkov** [comment]
About your map styling - are you creating a horror game?

**Comment by jm90m** [comment]
Oh doh, im a fail, I was setting minZoom to 20 when it should be a lot lower. Thanks again for your help. Nope I'm not creating a horror game just testing out different map styles to use to display locations on the map for work. Was thinking of using openlayers, but I saw your library worked nicely.

**Comment by istarkov** [comment]
I really like this map https://github.com/mariusandra/pigeon-maps
The only problem good free tile access

**Comment by jm90m** [comment]
Thanks for the suggestion, I'll check it out :D

**Comment by hoschi** [comment]
@istarkov 

> I prevented such zooming as it causes an interesting problem, in React you have one child but on the map you have few positions to place it.

the problem about multiple locations are not existent for overlays (which I read you use). It always positions it in the middle. Is it an option to use overlays to place react components? I not looked into your code in depth yet.

Here is a screenshot with a little green rectangle:
![2017-07-20-142235_2058x1409_scrot](https://user-images.githubusercontent.com/163128/28417165-4c81a872-6d57-11e7-89b3-913d8bc2a655.png)
And here the fiddle for it:
https://jsfiddle.net/ko4a2aL2/1/

**Comment by itsmichaeldiego** [comment]
@jm90m We're wrapping all the zoom minZoom issues in #544, feel free to comment in there, we will need help to make this work!
