### ISSUE TITLE
custom styles from snazzy maps, can't make them to work

### ISSUE THREAD

**Issue by jpggvilaca** [istarkov/google-map-react#353]
I have a variable storing the array with the snazzy styles , and:

`createMapOptions(maps) {
    return {
      scrollwheel: false,
      zoom: 11,
      center: [41.541720, -8.422543],
      styles: mapStyles
    }
  }`

The whole map goes black.

**Comment by istarkov** [comment]
And what? Options and styles are working good with this library, please provide jsbin or any other examples as the problem is in your code not in library.
