### ISSUE TITLE
Isn't there marker prop?

### ISSUE THREAD

**Issue by jpggvilaca** [istarkov/google-map-react#354]
No default marker is appearing, how can I import one? the default one at least. I have no marker on the map.

**Comment by istarkov** [comment]
Here are a lot of examples and docs, even README contains an example how it works. 
May be first steps just to start reading?

**Comment by jpggvilaca** [comment]
I've read the whole thing :/ . There's only an example with multiple markers and that didn't help. Shouldn't the marker be rendered on the "center" by default?

**Comment by istarkov** [comment]
First sentence here https://github.com/istarkov/google-map-react#whats-it-look-like
jsbin example there, etc.
Why it should be rendered on the center?
