### ISSUE TITLE
Map renders empty grey box?

### ISSUE THREAD

**Issue by nehero** [istarkov/google-map-react#355]
Using the exact example from the readme. Am I missing something or is there a bug?

```javascript
import React from 'react'
import GoogleMapReact from 'google-map-react'

export default class MapView extends React.Component {

	static defaultProps = {
		center: {lat: 59.95, lng: 30.33},
		zoom: 5
	  };

	render() {
		const AnyReactComponent = ({ text }) => <div>{text}</div>;

		return (
			<GoogleMapReact
				defaultCenter={this.props.center}
				defaultZoom={this.props.zoom}
				bootstrapURLKeys={{
					key: 'redacted'
				}}
			  >
				<AnyReactComponent
				  lat={59.955413}
				  lng={30.337844}
				  text={'Kreyser Avrora'}
				/>
			  </GoogleMapReact>
		);
	}

}
```

![screen shot 2017-04-03 at 4 08 59 pm](https://cloud.githubusercontent.com/assets/2093630/24633865/fb538bc4-1887-11e7-93bb-185ce71d3a1a.png)

**Comment by istarkov** [comment]
Seems like google api didnt loaded for some reason (bad api key etc) What u see in console?

**Comment by istarkov** [comment]
Also what about jsbin example? Does it works for you?

**Comment by nehero** [comment]
Nada, that's why it's weird. I did just make the api key though so I'll give it a few more minutes for the API key to be "valid" maybe?

**Comment by nehero** [comment]
Okay very weird — just accidentally clicked "responsive mode" in chrome's devtools and it made the map load, but once I refresh the page it goes back to not loading

**Comment by nehero** [comment]
![screen shot 2017-04-03 at 4 23 30 pm](https://cloud.githubusercontent.com/assets/2093630/24634227/f6275502-1889-11e7-99d9-2f2a15be693f.png)

These are the network requests made after toggling the responsive mode, should the first two be made when the component mounts?

**Comment by istarkov** [comment]
Have u tried jsbin example, a link before source at readme page? Does it work?

**Comment by istarkov** [comment]
Is it possible that you load map at script tag with different api key?

**Comment by nehero** [comment]
jsbin example works, yep. No other script tags for google maps, only using this component

**Comment by nehero** [comment]
Strange. I can confirm that it loads once i resize the browser window. I'll look into it a bit more

**Comment by istarkov** [comment]
Im not at the computer, are u sure that bootstrapUrl key is 'key' and not a cliientId or any other? What if you will delete that prop ?

**Comment by nehero** [comment]
API key works fine. The parent div that the map was in is hidden initially with `display: none` and then toggled to `display: block`. I removed the initial `display: none` and now it works fine. Going to see if I can see why it does that

**Comment by istarkov** [comment]
Try "magic" property `resetBoundsOnResize`
```
<GoogleMapReact
   resetBoundsOnResize
   ....
```
should help

**Comment by nehero** [comment]
That did the trick! Might be a good point to add to the docs, I'd be happy to submit a PR later

**Comment by Luckass77** [comment]
I am having a similar problem with my web site's contact page. (http://sandermechanical.com/contact)  The WordPress theme (Envision) has a built in Google Maps widget, and all of a sudden it stopped working.  I've paid for the author's support program, but my service ticket requests have gone ignored since December 2018.  Any assistance or guidance that can be offered would be most appreciated.

**Comment by itsmichaeldiego** [comment]
@Luckass77 What this wordpress theme has to do with this library? Please open another issue, this is closed and solved.
