### ISSUE TITLE
Webpackbin examples not working

### ISSUE THREAD

**Issue by mohitleo9** [istarkov/google-map-react#356]
Hey,
The examples on the documentation page are not working. Webpack bin shows a loading icon (but no errors in console). Apparently they were built using some old version of Webpack bin.
![image](https://cloud.githubusercontent.com/assets/4260533/24789840/366bd8f8-1b92-11e7-9867-950edf799d62.png)

![image](https://cloud.githubusercontent.com/assets/4260533/24789784/0095e566-1b92-11e7-8b47-030e0656a041.png).
Nevertheless the examples are easy to understand, just thought I should bring this up!

**Comment by istarkov** [comment]
Thank you, got it, I will them.

**Comment by jameskraus** [comment]
@istarkov, I'd love to take a look at those examples when you get a chance to update them

**Comment by itsmichaeldiego** [comment]
@jameskraus @mohitleo9 Thanks for your contrib, I am tackling this in #549
