### ISSUE TITLE
No reference to map instance

### ISSUE THREAD

**Issue by mavame** [istarkov/google-map-react#358]
I need to get a reference to the map instance created to do things like run custom events on the map, like resize.
`google.maps.event.trigger(MapInstance,'resize')`

How would I get a reference to the map instance the component created?

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/blob/master/API.md#ongoogleapiloaded-func

**Comment by mavame** [comment]
Thanks! Totally missed the API.md

**Comment by istarkov** [comment]
Bad documentation. I know :-)

**Comment by mavame** [comment]
All good! Thanks for the library.
