### ISSUE TITLE
Can you pass style parameters to the map?

### ISSUE THREAD

**Issue by bpeters** [istarkov/google-map-react#36]
Interested in styling the google map, using parameters generated by something like this http://gmaps-samples-v3.googlecode.com/svn/trunk/styledmaps/wizard/index.html?utm_medium=twitter

**Comment by istarkov** [comment]
This? https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_options/options_map_page.jsx#L10

**Comment by bpeters** [comment]
@istarkov Awesome, completely missed that one! I appreciate the quick turn around. :tada:

**Comment by istarkov** [comment]
:-)
