### ISSUE TITLE
warning: manually calling a React.PropTypes validation function

### ISSUE THREAD

**Issue by Matzu89** [istarkov/google-map-react#361]
Looks like update is needed to start using `prop-types` instead of `React.PropTypes`. I receive around 40 warnings or so like the one below.

`React.PropTypes validation function for the `distanceToMouse` prop on `GoogleMapMarkers`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`

**Comment by istarkov** [comment]
Seems like you need to update this library, what version are u using now?

**Comment by istarkov** [comment]
because its already fixed https://github.com/istarkov/google-map-react/blob/master/src/google_map_markers.js#L4

**Comment by binjospookie** [comment]
And what about Flow?

**Comment by istarkov** [comment]
No flow there ;-)

**Comment by binjospookie** [comment]
I mean ability to remove 'prop-types' and use Flow. For now I can't remove 'prop-types' from my package.json and it's very sad.

**Comment by istarkov** [comment]
I use flow for other projects, but not sure I want to somehow use it here with current API. I have an idea to rewrite it, but have no time

**Comment by binjospookie** [comment]
Ok, I understood you. Now I removed 'prop-types' from my package.json and I have error:
```
Module not found: Can't resolve 'prop-types' in '/home/binjo/WebstormProjects/gitlab/react.ui/node_modules/google-map-react/lib'
 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js
Error in ./~/google-map-react/lib/google_map_markers.js
Module not found: Can't resolve 'prop-types' in '/home/binjo/WebstormProjects/gitlab/react.ui/node_modules/google-map-react/lib'
 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js
```

Any ideas?

**Comment by Snaddu** [comment]
@binjospookie Had same problem and that broke our build pipelines. Seems that prop-types is only presented as devDependencies of google-map-react and what i have understood npm doesn't install those automatically. Now google_maps_markers.js tries to use them in with distribution dependencies only and this causes error.

I'm not 100% sure but moving prop-types from devDependencies to dependencies should do the trick. @istarkov What do you think?

**Comment by istarkov** [comment]
I think we should look how its done by other libraries like react-virtualized, react-router, react-redux and just do the same ;-) On mobile now, so have no chance to look fast how its done there

**Comment by Matzu89** [comment]
@istarkov sorry for the slow response. I switched to using static maps because of project demands, so forgot about this. I was using 0.24.0.

**Comment by zacck** [comment]
I'm having this same issue on version 0.24.0, My Current fix is to add the prop-types package to my app the keep dev going.

**Comment by itsmichaeldiego** [comment]
@zacck @Matzu89 @Snaddu @binjospookie This is fixed guys:

https://github.com/istarkov/google-map-react/blob/master/src/google_map_markers.js#L32

Closing the issue, please let me know if you need more help or create a new issue, thanks!
