### ISSUE TITLE
Setting zoom to default after button click

### ISSUE THREAD

**Issue by petrck** [istarkov/google-map-react#365]
I try to return map zoom, after user click on "plus" button and zoom is changed. After this, I close modal dialog and before reopen I will set zoom back to my default value, for example 6. But when map is reopen in dialog, zoom is still set on user zoom and not to my default set. Everything is pre-rendered well, but zoom not. Value in props in my map component is correct.

In my map I have simply this:

```
<GoogleMap
                        // bootstrapURLKeys={{key: API_KEY}}
                        
                        center={this.props.center}
                        zoom={this.props.zoom}>

                        {this
                            .props
                            .transports
                            .map((transport) => {
                                return <MapPlace
                                    key={transport.id}
                                    lat={transport.gpsN}
                                    lng={transport.gpsE}
                                    transport={transport}
                                    handleMarkerClick={this.props.handleMarkerClick}/>
                            })}
                    </GoogleMap>
```

On my dialog show button is simply setState(...) calling. How is possible return map to default settings?

Thank you

**Comment by istarkov** [comment]
In most cases the problem that zoom and center can't be used alone, only with `onChange` callback in controllable manner.

**Comment by petrck** [comment]
Thank you for answer. Can you show me any simply example how I can solve it with onChange callback? Thank's.

**Comment by istarkov** [comment]
Almost all examples in readme, jsbin for example https://jsbin.com/roqutisoqu/1/edit?js,console,output
Every example in docs etc

**Comment by petrck** [comment]
Perfect. Thank you for inspiration. 👍
