### ISSUE TITLE
GoogleMap: Usage of internal api objects is dangerous 

### ISSUE THREAD

**Issue by krypton97** [istarkov/google-map-react#367]
Hi, I'm looking to use this module in production with heatmaps. I've got it working, but for some reasons it gives me this warning:

      GoogleMap: Usage of internal api objects is dangerous and can cause a lot of issues.
      To hide this warning add yesIWantToUseGoogleMapApiInternals={true} to <GoogleMap 
       instance

Is it a good practice to do for production or there's another way to do it? I'm looking to find out if it's a good choice for production usage or I should use something else

**Comment by istarkov** [comment]
It just means that supporting of google api is not the intent of this library. So you can use it, and if it works all is ok. If not I will not help :-)

**Comment by krypton97** [comment]
Seems fair, thank you!
