### ISSUE TITLE
Cannot find module 'prop-types'

### ISSUE THREAD

**Issue by figalex** [istarkov/google-map-react#369]
I just installed version 0.24.0 and got this error: Cannot find module 'prop-types'.

Seems like it is missing a dependency.

**Comment by brijesh-pant** [comment]
prop-types is a peer dependency of this module. You need to install it separately into your project.

https://github.com/istarkov/google-map-react/blob/master/package.json#L45

**Comment by tifa2UP** [comment]
@figalex You can do npm install "prop-types" or yarn add "prop-types" and it'll work!

**Comment by figalex** [comment]
Yeah I figured that out later, I just thought that maybe is a mistake that prop-types was listed as peer dependency.
