### ISSUE TITLE
Server rendered with JavaScript disabled, show a message to users..?

### ISSUE THREAD

**Issue by stephen-last** [istarkov/google-map-react#370]
I am server rendering my components, and I'd like to display a message to users if JavaScript is disabled or not available.

At the moment, with JS disabled, users just see my marker on a white background, which isn't useful for them. I need a way to display a message to users explaining why they can't see the map, something like "You need JavaScript enabled to see this map.".

Are there any options that allow this kind of message to be shown..?

The [react-google-maps](https://github.com/tomchentw/react-google-maps) package has a `loadingElement` attribute which shows and stays in view when JS is disabled. I can't use this package though, it's not very well maintained and [hasn't been updated ready for React 16](https://github.com/tomchentw/react-google-maps/issues/463). The [last commit](https://github.com/tomchentw/react-google-maps/graphs/contributors) was Oct 2016.

**Comment by istarkov** [comment]
In such case just do it as like as you do it in real life, place a div over
the map with loading message and remove it if js is available.
There is no need to support this in library as it can be written in
one-liner by yourself.

**Comment by stephen-last** [comment]
Thanks for the super fast reply @istarkov !

Just wanted to check if you had anything built-in but undocumented for this.

I've used `componentDidMount()` to show the map as it's obviously only run client-side, not server-side.

Great package BTW, thanks for your work...

```js
import React from 'react'
import GoogleMap from 'google-map-react'
import get from 'lodash/get'

import config from '../../../config/client'

const Marker = props => <div className='marker' />

class MyMap extends React.Component {
  constructor () {
    super()
    this.state = { showMap: false }
    this.oh = get(config, 'locations.oxfordHouse', { lat: 0, lng: 0 })
    this.mapProps = {
      bootstrapURLKeys: { key: config.googleMapsKey },
      defaultCenter: { lat: this.oh.lat, lng: this.oh.lng },
      defaultZoom: 11
    }
  }

  componentDidMount () {
    this.setState({ showMap: true })
  }

  render () {
    const map = this.state.showMap ? (
      <GoogleMap {...this.mapProps}>
        <Marker lat={this.oh.lat} lng={this.oh.lng} />
      </GoogleMap>
    ) : (
      <div className='map-loading'>
        <p>Loading...</p>
        <p>This map requires JavaScript to be enabled.</p>
      </div>
    )
    return <div className='map-container'>{ map }</div>
  }
}

export default MyMap
```
