### ISSUE TITLE
Changing lat/lng from using CSS top/left to using CSS transforms

### ISSUE THREAD

**Issue by jamespizzurro** [istarkov/google-map-react#371]
[I've substituted top/left with CSS transforms in my fork of this project](https://github.com/jamespizzurro/google-map-react/blob/master/src/google_map_markers.js) and it seems to work well, except for the moment the user unclicks their mouse after clicking and dragging the map to move it around. It seems there's a rerender happening on all markers at that moment which has them snap to a position that's related to where the map was dragged to, then they assume the correct position. Because I'm using CSS transitions too though, this movement after the initial snap is animated, which is not desired.

What could explain this behavior? How might I go about fixing this undesirable snapping and subsequent adjustment to the correct position for my markers? Because this snapping doesn't happen when I disable CSS transitions, I think this brief position issue is actually present in the master branch that I forked from, it just isn't noticeable because of how quickly it occurs using top/left and the only reason I'm noticing it is because I'm using CSS transitions on the CSS transforms I'm using instead of top/left, which together slows down and animates the movement so that it's noticeable.

For clarity, here are the changes I made to accomplish this so far (it didn't take much):
1. https://github.com/jamespizzurro/google-map-react/commit/5b19333106174956b69af4ad91a1ad67164b06c0
2. https://github.com/jamespizzurro/google-map-react/commit/4b89ca34210513ff8b2b38245251e415281d90ea
3. https://github.com/jamespizzurro/google-map-react/commit/8d5cf4af9e86d84b5f129cdea2d8d5b8bd18c0fb

Thanks in advance for any help.

**Comment by jamespizzurro** [comment]
Update: the initial position snapping does not occur until after the map has stopped moving after a click and drag, so if there's some left over movement from a "swipe" (a click and a drag that results in the map still moving after the unclick), the snap happens after the map position stops changing.

**Comment by istarkov** [comment]
> I've substituted top/left with CSS transforms in my fork of this project and it seems to work wel

Why?

**Comment by jamespizzurro** [comment]
To animate my markers, all of which are subject to moving around based on their current GPS position, which changes every few seconds. CSS seems like the way to go for this.

**Comment by istarkov** [comment]
Every few seconds is not a real time animation, you will see no performance benefit using css transform over left right, and will get a lot of issues and browsers bugs using translate.

I'm pretty sure all the performance problem you have is not based on left top change.
IMO if you need a big amount of realtime animated markers you need something like this https://github.com/istarkov/google-map-thousands-markers
And all that css transform gives a little performance benefit.

**Comment by jamespizzurro** [comment]
Gotcha, thanks, I'll definitely check out that project. Just to clarify though, this isn't a performance problem: the "snapping" appears to occur because, for a brief moment, the wrong position is being fed to each marker, which is then subsequently corrected. I was hoping to get some clarity on this mechanism and maybe some ideas of why this might be happening. If you don't know, that works too. :p

**Comment by istarkov** [comment]
All this project is a big hack over the black box (google map api) it can happen for enormous amount of reasons. Some hacks does not solve the problem of unsynchronised content - just reduce the probability to see it - like double raf inside the source ;-)

Two years ago when I wrote it I think I had knowledge about everything you see, but now not ;-)

**Comment by jamespizzurro** [comment]
Totally understand, haha.

I did manage to get this working with these two additional commits:
* https://github.com/jamespizzurro/google-map-react/commit/301c1d9b39c1768543dbd813482cba252529730c
* https://github.com/jamespizzurro/google-map-react/commit/40b6012ce3979b14bcc0108b58c5c53dd7fd0dc9

There's probably a performance hit to these changes or something bad, but it works. :100:

**Comment by thientran1707** [comment]
can you help me to re-position the marker? I have found something in the documentation about it? But the link is not valid
https://github.com/istarkov/google-map-react/blob/master/DOC.md
The section "Whats wrong with "Simple example" above" says about it but the link is invalid?

**Comment by itsmichaeldiego** [comment]
@thientran1707 I am taking care of the DOC links in #549, sorry about the inconvenience. 

@jamespizzurro You can just add `transform: translate(-50%, -50%);` in css to your marker component and that would do the trick. Let me know if that helps.
