### ISSUE TITLE
Google Maps API warning: NoApiKeys 

### ISSUE THREAD

**Issue by evanfrawley** [istarkov/google-map-react#372]
Hiya,

I'm using this for a React / Typescript project. My map works totally fine -- but I keep getting this warning when the page loads. I'm very sure that I have the `bootstrapURLKeys` property set up correctly: `bootstrapURLKeys={{ key:this.util.getKey() }}`. This is a valid Google Maps JS API key as well. This also occurs when the key itself is hardcoded into the pair. Is there a simple fix for this that I am missing?

Thanks for the help in advance!

Stack trace of the error (but it doesn't seem very helpful):
```
util.js:220 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
rB.j @ util.js:220
(anonymous) @ js?libraries=places&sensor=false:136
(anonymous) @ js?libraries=places&sensor=false:53
(anonymous) @ js?libraries=places&sensor=false:50
(anonymous) @ js?libraries=places&sensor=false:53
_.G @ js?libraries=places&sensor=false:52
(anonymous) @ js?libraries=places&sensor=false:53
_.v @ js?libraries=places&sensor=false:32
Yc @ js?libraries=places&sensor=false:53
(anonymous) @ js?libraries=places&sensor=false:136
```

**Comment by istarkov** [comment]
Having that there is no word `sensor` in this library, I don't know what to say, somehow it's added to gmap script tag in your case. Search you codebase to find where.

**Comment by evanfrawley** [comment]
Hi, I'm sorry it seems I copy pasted the wrong stack trace: 
```
util.js:220 Google Maps API warning: NpApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
rB.j @ util.js:220
(anonymous) @ js?libraries=places&sensor=false:136
(anonymous) @ js?libraries=places&sensor=false:53
(anonymous) @ js?libraries=places&sensor=false:50
(anonymous) @ js?libraries=places&sensor=false:53
_.G @ js?libraries=places&sensor=false:52
(anonymous) @ js?libraries=places&sensor=false:53
_.v @ js?libraries=places&sensor=false:32
Yc @ js?libraries=places&sensor=false:53
(anonymous) @ js?libraries=places&sensor=false:136
```
For reference, I got this snippet of code from the API Docs found in the README. I was trying to add a SearchBox (which works), and the docs instructed that I add a script tag in the HTML (specifically under `Adding a searchbox`). I found a way to get rid of the warning, by including the API key in:
    `<script type="text/javascript" src="https://maps.google.com/maps/api/js?libraries=places&key={YOUR_API_KEY}"></script>`, but I really dislike having to directly bake my API key into a script tag. 

In regards to the `sensor`, it was also part of the `<script>` in the API docs. 

Do you happen to know of any other fixes to adding a searchbox to the page that won't result in these warning or adding a `<script>` tag to the HTML?

**Comment by istarkov** [comment]
Docs were written not by me only, I don't even know what searchbox is. Seems like bug in docs.

Just don't use script tag, or use it after reading a google api, everything can be added via `bootstrapURLKeys`.

**Comment by evanfrawley** [comment]
Okay, thanks for the help, I'll update here if I have a solution

**Comment by axe-z** [comment]
I'm having the same issue, it does work, but my cod kicks in with warnings ;)

**Comment by sergop321** [comment]
I am using the place with searchBox by simply using libraries: 'places' in bootstrapURLKeys, No other script tags on page
```javascript
import React from 'react';
import GoogleMap from 'google-map-react';


const GoogleMapConfig = {
	key: YOUR_KEY,
	libraries: 'places',
};

export default class Map extends React.Component {
	render() {
		return (
			<GoogleMap
				bootstrapURLKeys={GoogleMapConfig}
	                        // ALL YOUR OTHER OPTIONS
			/>
		);
	}
}
```
