### ISSUE TITLE
Draw Polygon on a map

### ISSUE THREAD

**Issue by nikolayg** [istarkov/google-map-react#373]
I'd like to draw multiple polygons on a map. Each polygon is defined by a list of coordinates (lat/long). It would be nice to put transparent colour for the internal area of each polygon.

Are there any demos/examples/doco on how to achieve this?

**Comment by istarkov** [comment]
And if there exists what you need to do first? Be sure it's not writing an
issue.

**Comment by nikolayg** [comment]
Hi there,

Thanks for your quick reply. I checked the examples and the doco, but couldn't find such capability.

I'll close the issue. Where do you suggest I raise such questions?

**Comment by istarkov** [comment]
Issues search, there are few issues about polygon drawing.

**Comment by nikolayg** [comment]
My bad, I was searching in the open issues only :(

**Comment by istarkov** [comment]
Some math can be found here also https://github.com/istarkov/google-map-thousands-markers
As canvas drawing is somehow the same as polygon drawing
