### ISSUE TITLE
Can`t highlight text on pin drawer

### ISSUE THREAD

**Issue by burnjohn** [istarkov/google-map-react#374]
Hi! 
A week ago I faced the issue in my project connected with selecting text on map pin drawer. The thing is that I couldn`t select text on map pin drawer with mouse clicks  except the case when I click the right mouse button.

I couldn\`t fix this issue locally in my project. Then I started discovering the google-map-react-examples and I found that can`t select or highlight the text on pin drawer too. In the example project source code this drawer is called "hintBaloon".

In google maps examples we can simply highlight text on pin drawer https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple

I guess the root cause is that in google maps documentation pin drawer is created with library method - "InfoWindow". I`d like to fix this issue. Maybe someone will help me with some advice.

**Comment by istarkov** [comment]
I'll give you an idea how to make it work, if you will provide an opensource example after, ok?

**Comment by burnjohn** [comment]
@istarkov thanks for the fast answer. Sure I`ll be able to create a PR with a fix. Now I have an idea how to fix it. 

1. Use google.maps.InfoWindow method for creating an info window. It takes as a first parameter object with HTML markup. We can pass a JSX component to it and I guess that react event listeners will work.
2. Create pin with method google.maps.Marker 

But I don`t have an idea how to get pin react component working with method google.maps.Marker. Especially when we have a cluster.

**Comment by istarkov** [comment]
I will not accept PR with sipport of InfoWindow or any other gmap API, it's not the intent of this library to do it.
I will give you an idea how to do it using current library ;-)

**Comment by burnjohn** [comment]
Ok, looking forward to your ideas )

**Comment by MatiMil** [comment]
Hi!
Thanks for this awesome package!

Are there any updates on this (or ideas) ? Because I am facing the same issue and would be happy to get some ideas to fix this.

FYI: I have a info window (simple div) on the map and disabled dragging on google maps. I have a textarea in the map and can't select the text in it.

Glad to hear from you

**Comment by itsmichaeldiego** [comment]
@MatiMil You can use either `maps` or `map` catching the callback with `onGoogleApiLoaded`:

```javascript
  <GoogleMapReact
    zoom={props.zoom}
    center={props.center}
    bootstrapURLKeys={{
      key: process.env.MAP_KEY,
      language: 'en',
    }}
    yesIWantToUseGoogleMapApiInternals
    onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps)}
  >
    // MARKERS
  </GoogleMapReact>
```

```javascript
const apiIsLoaded = (map, maps) => {
  // maps.InfoWindow({ ... })
  // maps.Marker({ ... })
};
```

Let me know if that works, otherwise please re-open the issue and I will help you guys out!
