### ISSUE TITLE
Update changelog?

### ISSUE THREAD

**Issue by lolsheeplol** [istarkov/google-map-react#375]
I'm updating google-map-react from 0.23.0 to 0.24.0 but I'd like to see a list of changes before I npm install.  Could you update the changelog to provide some details on the release?  It's not currently possible to see exactly what has changed since there aren't even tags to do a github compare against.

**Comment by istarkov** [comment]
All tags is set and available
![image](https://cloud.githubusercontent.com/assets/5077042/25348845/411d5b02-2928-11e7-8649-cfae39cccfe7.png)

**Comment by istarkov** [comment]
Or not :-)

**Comment by istarkov** [comment]
I wish to read something like: dear Ivan having that u have terrible release process I would like to help you and ready to do it myself :-)

**Comment by lolsheeplol** [comment]
Have you used the compare tool on github?  For me, it makes it easy to compare changes across branches or tags (in your case, your commits that you named with version numbers).  I could actually see your changes with this link: https://github.com/istarkov/google-map-react/compare/33d7f464be617e2aa777d2ddf33c41b822f2a04b...2b540d6d458e6515f9530d3b9073ce70c6d4f475 

You can see how to do it [here](https://help.github.com/articles/comparing-commits-across-time/).  All tagging does it make it easier to view a compare since you can insert the tag name instead of the commit hashes into the compare url.  Also this means you don't need to comment your commits with the version number, just do them normally and tag the commit with the release number.  :)

**Comment by istarkov** [comment]
As I know `yarn publish` adds tags automatically, so latest update should solve the problem ;-)
I don't use tags in my everyday activity so for me they looks like some kind of useless thing.

**Comment by lolsheeplol** [comment]
Ah, okay.  Although to be more developer-friendly I would recommend you use them, along with the repo's [releases page](https://github.com/istarkov/google-map-react/releases) or updating the [Changelog](https://github.com/istarkov/google-map-react/blob/master/CHANGELOG.md).  This will definitely help developers using your library as it makes understanding the code more manageable and can let us know if there are breaking changes or not.  

As it stands, I have to guess that a minor sem-ver change shouldn't break anything and a confirmation on that from the repo maintainer via a changelog or release definitely helps.  Hope this helps you as well!

**Comment by istarkov** [comment]
I know, it's not the only and even not biggest library I maintain, and for example [here](github.com/acdlite/recompose) I do all my best, and here for some reasons are not

**Comment by lolsheeplol** [comment]
Got it.  Thanks for responding so quickly and if you do find time to add those little nice-to-haves I know myself and probably most developers using this library would appreciate it.  Thanks for working on this project and keep up the good work!
