### ISSUE TITLE
Change Cursor Property

### ISSUE THREAD

**Issue by lauffenp** [istarkov/google-map-react#377]
I'm sorry if this is covered somewhere.
I wish to change the cursor property. I wish to use the default or crosshair cursor. I've tried adding it to style in the GoogleMap component, as a prop (draggableCursor as well), and in the bootstrapurlkeys(which I know isn't right).

Thanks again. This is a great library.

**Comment by istarkov** [comment]
The workaround I found is to disable drag (`draggable=false`) and then your css cursors will be shown. So it looks something like - when I hover on a marker, I disable drag.

There is example exists with this behaviour
https://istarkov.github.io/google-map-thousands-markers/
See how
https://github.com/istarkov/google-map-thousands-markers/blob/60931a1d8a34985ac34d0f50afc177c6ffe075b2/src/controls/Map/CanvasHoverMap.js#L53-L54

**Comment by istarkov** [comment]
And in that example I set cursor to the whole map https://github.com/istarkov/google-map-thousands-markers/blob/60931a1d8a34985ac34d0f50afc177c6ffe075b2/src/controls/Map/CanvasMap.js#L20
As markers is drawn on a canvas.

**Comment by istarkov** [comment]
May be it's possible via google api itself, can't say I know it well

**Comment by lauffenp** [comment]
I appreciate your reply, but I don't see how this works. I can style the cursor over a marker easily, but on the map it is still a 'pan-hand'. This is true in the examples you've posted. I will take a look and maybe I can provide a solution instead of only questions.

**Comment by edd83** [comment]
If someone is still looking for something :
this.refs.maps.googleMapDom_.firstChild.firstChild.firstChild.style.cursor = 'crosshair'

Put a ref : 
<GoogleMapReact ref="maps" />

**Comment by azfaralsukor** [comment]
Set `draggableCursor: 'crosshair'` in options properties

`<GoogleMapReact
 options={{ draggableCursor: 'crosshair' }} 
/>`
