### ISSUE TITLE
Map crashes when adding lots of markers (600 ish)

### ISSUE THREAD

**Issue by NathHorrigan** [istarkov/google-map-react#378]
This is not an issue with the library but an Issue with the examples. I'm loading markers dynamically as the bounds change and obviously, the mass amount of markers is making everything really slow. Could you point me in right direction of using MarkerCluster or similar for this library as the examples aren't much use to someone who doesn't know what they're looking for? Maybe an improvement to the examples with some sort of explanation on how and why you have done what?

Thanks for a great library and the effort you have put in!

**Comment by istarkov** [comment]
there is a reference in readme to thousands marker example

**Comment by NathHorrigan** [comment]
Yeah, I know. There's just no text to explain how you're doing it.

**Comment by istarkov** [comment]
Not a lot of source there, with comments where needed. Also readme explains internals.
I see no reason to write text over simple code.

**Comment by NathHorrigan** [comment]
No Worries, I've switched to MapBox :rofl:

**Comment by istarkov** [comment]
Its my recommendation to use mapbox :-) I wrote it in a few issues. Google api and look are very outdated.
