### ISSUE TITLE
Warning: `NaN` is an invalid value for the `left` css style property. Check the render method of `GoogleMapMarkers`.

### ISSUE THREAD

**Issue by ckim16** [istarkov/google-map-react#381]
Hi all,

I'm using google-map-react library for my project and but I keep getting an error in my browser saying that **Warning: `NaN` is an invalid value for the `left` css style property. Check the render method of `GoogleMapMarkers`.**
Plus, my map does not even get rendered even though there is specific height and width for it.

My code looks like
googleMap.js
```
import React from 'react';
import GoogleMap from 'google-map-react';

import Cart from './cart';

export default (props) => {
  return (
    <GoogleMap
    defaultCenter={[props.lat, props.lng]}
    defaultZoom={12}
    >
      <Cart lat={props.lat} lng={props.lng}/>
    </GoogleMap>
  );
}
```
cart.js
```
import React from 'react';

export default () => {
  return (
    <i className="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
  );
}
```
and a method that using google map component
```
renderMap() {
    if (this.props.loc) {
      return (
        <GoogleMap lat={this.props.loc.lat} lng={this.props.loc.lng}/>
      );
    } else {
      return <h4>Loading map...</h4>
    }
  }
```

Has anyone had this kind of issue or know how to solve it?

Thank you all for your time reading this and works.

**Comment by BojiBote** [comment]
You'll need to insert your API key like so to get the map to render:
```
<GoogleMap
    bootstrapURLKeys={{ key: 'API KEY HERE' }}
    defaultCenter={[props.lat, props.lng]}
    defaultZoom={12}
    ...
```
As for NaN is an invalid value for the left css style property, I am facing the same issue as well. I've been trying to figure it out myself as well.

**Comment by aayush-k** [comment]
I'm getting this warning as well, any update on this?

**Comment by istarkov** [comment]
There is a jsbin example in Readme, can u provide an example with error based on it

**Comment by Fenwil** [comment]
Having the same problem here.  Watched all the examples and I'm not finding what's the problem 🤔

**Comment by istarkov** [comment]
We have a joke that the problem is between seat and computer :-)
without example I cant say much.

**Comment by tuncatunc** [comment]
Interestingly, I've the same problem but with Mapbox React GL

**Comment by AgustinCB** [comment]
I had this error recently and then realized that I was putting my latitude in `lng` and longitude in `lat`. Try switching them :)

**Comment by tuncatunc** [comment]
İt worked after switching lat lng values. Thanks @agustincb

**Comment by itsmichaeldiego** [comment]
Seems like its solved!

**Comment by sojungko** [comment]
Still seeing this issue. The reason is because `lat` `lng` are off the map (it doesn't exist on map). I'm working on a PR to either fix or silence the error.

**Comment by itsmichaeldiego** [comment]
@sojungko So its not an issue, coordinates don't work that way, if you pass the longitude as latitude you won't find anything.

**Comment by callamwilliams** [comment]
If you are returning data from the places API (searchbox, autocomplete) make sure you call the lat/lng as functions rather than objects

```
<Marker
  key={place.id}
  text={place.name}
  lat={place.geometry.location.lat()}
  lng={place.geometry.location.lng()}
/>
```

Otherwise you are passing a function rather than a number - so `NaN` error

Try testing it manually with proper numbers, and double check the values you are passing via props.
