### ISSUE TITLE
Invalid link in new docs (Good position example)

### ISSUE THREAD

**Issue by mpourismaiel** [istarkov/google-map-react#383]
The link [Good Position](http://www.webpackbin.com/VJBKkj_vM) in DOC.md file seems invalid. It shows the message shown in this [screenshot](https://imagebin.ca/v/3MXtxYGZt8Vl).

**Comment by istarkov** [comment]
I know, have no time to recreate examples, as them been loss when webpackbin was updated

**Comment by leoi11** [comment]
@istarkov is it possible to contact them to see if they have backup of the examples? It's sad to hear that the docs won't be available in near future, but understand you have your other priorities and appreciate your effort creating this library.

**Comment by mpourismaiel** [comment]
@istarkov Can you mention in brief just how the demo should be and I could maybe help with it.

**Comment by itsmichaeldiego** [comment]
@mpourismaiel @leoskyrocker Guys! Thanks for your contrib, I am tackling this in #549
