### ISSUE TITLE
Use Default Google Maps Marker

### ISSUE THREAD

**Issue by fahd** [istarkov/google-map-react#384]
Hi there! I know how to use a custom marker, but how do we use the default Google Maps Marker? I don't need the customization, but I can't find where to use the original.

**Comment by istarkov** [comment]
Just use google api directly, as you can see at readme the only intent of this library is "to render any React component on the Google Map." 
So just use google api, or use this library https://github.com/tomchentw/react-google-maps

**Comment by danielrob** [comment]
Darn... your library looked so much more developer friendly!

**Comment by vorthess** [comment]
@istarkov do you maybe have info how to retrieve markers from `map` object? 
I can't find it in google docs, all examples are based on storing markers during its constructing

**Comment by istarkov** [comment]
What the task where you need to retrieve markers from map?

**Comment by vorthess** [comment]
I want to use this library:
https://github.com/googlemaps/v3-utility-library/tree/master/markerclusterer

suggested by google
https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by istarkov** [comment]
To use that lib u dont need to retrieve markers from the map.

**Comment by vorthess** [comment]
Maybe I do something wrong, but I can't make it work. When I don't pass markers array inside, it's not working.

**Comment by itsmichaeldiego** [comment]
@fahd @danielrob @lkostrowski Guys, this got a little bit outdated, I am willing to help but I am closing this issue, if you guys still having the problem, open a new issue and I will take care of it 💪
