### ISSUE TITLE
minZoomOverride cause problem

### ISSUE THREAD

**Issue by MeloDai** [istarkov/google-map-react#386]
when use minZoomOverride: true, minZoom: 0, then the markers are not in right position
could it be fixed?

**Comment by istarkov** [comment]
no

**Comment by itsmichaeldiego** [comment]
@MeloDai Yes, it could be fixed! We're wrapping all the zoom minZoom issues in #544 and we going to address it soon, feel free to comment in there, we will need help to make this work!
