### ISSUE TITLE
clustering?

### ISSUE THREAD

**Issue by MidnightP** [istarkov/google-map-react#388]
Great stuff. But I can't find the documentation about clustering. How do I cluster?

**Comment by istarkov** [comment]
Open [README](https://github.com/istarkov/google-map-react) press `CMD-F` or `CTRL-F`, enter word `clustering` in search.

**Comment by MidnightP** [comment]
Got it!

https://github.com/istarkov/google-map-clustering-example

2017-05-21 20:04 GMT+02:00 Ivan Starkov <notifications@github.com>:
