### ISSUE TITLE
Map showing grey with simplest example and resizing does not fix the issue

### ISSUE THREAD

**Issue by iippis** [istarkov/google-map-react#390]
I tried implementing the component with the simplest example
`<GoogleMapReact
                        bootstrapURLKeys={{
                            key: 'API_KEY'
                        }}
                        defaultCenter={this.state.center}
                        defaultZoom={this.state.zoom}
                    />`

We are using server rendering. The script loads fine, at least there are no errors and everything else seems fine but the map tiles just won't load; the whole map block is just grey. Any ideas why this is happening?

**Comment by istarkov** [comment]
map height=0 for example, can't say much without example

**Comment by iippis** [comment]
There really isn't anything else. Only a container element that has width: 100% and height: 100%. Am I supposed to tell the component something else?

**Comment by istarkov** [comment]
No must be enough. Does it works with server rendering off?

**Comment by istarkov** [comment]
If yes I'm pretty sure at the moment of component init it's height is equal to zero.  To avoid you need to fix layout or add `resetBoundsOnResize` property to map.

**Comment by iippis** [comment]
Even if I check that the window object is present and add the resetBoundsOnResize flag, the result is still the same.

**Comment by istarkov** [comment]
Does it works with server rendering off?

**Comment by bardiarastin** [comment]
server side rendering with Express and the same issue :-(

**Comment by istarkov** [comment]
I'm pretty sure that without example no one can say that issue is the same. 
There are working examples in README with working server rendering, just compare and do all the things we do as developers to investigate issue.

**Comment by bardiarastin** [comment]
this occurs because my map is in a tab which is not enabled by default (by default it's wrapper has a zero height) . solved by creating map at opening time (custom code not using this lib).

**Comment by bkniffler** [comment]
Got the same issue, any solution found @iippis? I'm not using SSR in dev mode, but I think it has something to do with height.

Gonna investigate a bit more.

**Comment by bkniffler** [comment]
Found the answer here:
https://stackoverflow.com/questions/11749742/google-maps-api-v3-gray-box-no-map

Somehow my styles must overwrite the google maps ones, adding these here to the map resolved the issue:
```css
#map * {
    overflow:visible;
}
```

**Comment by itsmichaeldiego** [comment]
Seems like its solved, thanks guys!
