### ISSUE TITLE
Question - dispatch click event to component

### ISSUE THREAD

**Issue by mrmuh** [istarkov/google-map-react#392]
Hello! 
I am trying to create new markers when the user performs a long press on the map. For the implementation I'm using the react-tappable component and tried to dispatch the click event to the GoogleMapReact component to get the coordinates on the map over the onClick handler. The problem is that I cannot trigger the click event manually on the reference of the GoogleMapReact component as there is no click or dispatchEvent method. Is there another way to dispatch the events to the component?

**Comment by istarkov** [comment]
You don't need to dispatch events etc, you have all the data to detect on what marker you clicked,
there is an existing example with all the math here
https://github.com/istarkov/google-map-thousands-markers/blob/master/src/controls/Map/CanvasMap.js

Here I draw markers on the canvas and manually detect over which marker cursor pointer is.

**Comment by mrmuh** [comment]
For existing markers I have already found this example in other github issues but does it also work for new marker that I want to create with a long press event?

BTW ... thank you for the awesome component and the outstanding support!!

**Comment by istarkov** [comment]
It has all the math to get `lat` `lng` from mouse coordinates ;-) 
All you need just add marker to the children with that coordinates
