### ISSUE TITLE
Get Reference to Map / Generate Place Details...

### ISSUE THREAD

**Issue by hbwoodrose** [istarkov/google-map-react#393]
Hello
I am trying to fire this from another component in order to generate place details and do routing and stuff later:
`new google.maps.places.PlacesService(map)`

It requires a reference to the map. I tried passing along the map reference from `onGoogleApiLoaded={({map, maps}) => this.startMap(map, maps)}`

I am able to console log the *map* reference, which is an object named 'tg', but it seems that is not enough. Any suggestions? 

Thanks in advance! :)

**Comment by istarkov** [comment]
I reread 3 times but havent understand the question at all ;-)

**Comment by hbwoodrose** [comment]
ah haha ok ill try to be more clear:

1) i have a map rendered and am also using the places library to autocomplete places
2) when clicking on one of those places, i would like to get the place details
3) in order to do that, i must call `new google.maps.places.PlacesService(map)` with a reference to the map
4) as per the documentation, i can get the map instance from `onGoogleApiLoaded={({map, maps}) => this.startMap(map, maps)}` - which im doing and passing that up to the parents state.
5) i am retrieving that and am able to log it to the console, but it doesnt seem to fire my places.PlacesServices call. 

I have published a preview (only works on desktop for now) here so you can see better what im talking about: https://ridezulu-uvbnuoercx.now.sh/ride

right now its limited to switzerland, but (if you are in switzerland) you can edit the 'from' address and click one of the suggestions below. it should log the place data to the console, but does not. 

i guess the easier question is this: if i want to get place details or plot routes on the map, what is the best way to do that? 

Thank you in advance! your plugin is awesome so far :)

**Comment by istarkov** [comment]
I don't understand what `this.startMap` means, BTW the idea is simple.

At first the argument of `PlacesService` as I know is not `map` but some HTML element, 
I usually use some fake element

```javascript
onGoogleApiLoaded={({map, maps})  => {
   const fakeElt = document.createElement('div');   
   this.placesService  = new maps.places.PlacesService(fakeElt);
}
```

so now you can use `this.placesService` in your class methods, just don't forget to check on `undefined` as `onGoogleApiLoaded` is called asynchronously

**Comment by istarkov** [comment]
I've just took a look into google docs, and seems like it must work with `map` instead of `fakeElt` BTW have no time to check.

**Comment by hbwoodrose** [comment]
ah ok i thought it was a reference to the javascript map instance but instead it is a reference to the dom element. thanks! ill try it out and let you know the outcome.

btw, `this.startMap` is just my function to initialize the map and pass to the application state `mapLoaded = true` 

thanks for you help and your awesome work! :)

**Comment by hbwoodrose** [comment]
hey here is an update:

I tried adding a fake dom element reference as well as a reference to the real dom element. neither of them work and just produce the error `INVALID_REQUEST`

ill keep digging around trying to make this work. thanks for your help!

**Comment by istarkov** [comment]
https://jsbin.com/hoyesaguqo/3/edit?js,console,output

**Comment by istarkov** [comment]
Oops jsbin does not save

**Comment by istarkov** [comment]
https://jsbin.com/velisenuco/1/edit?js,console,output

**Comment by hbwoodrose** [comment]
I found the problem!!!!!

In a lot of the documentation it says to reference the place by the placeId, like the following: 

var request = {
		      placeId: placeId
};

but that is not the right syntax.  its actually by the place.reference, like the following:

var request = {
		      reference: placeReference
};

I hope that helps anyone else coming up against this problem!!! it was driving me crazy!!! And thanks @istarkov for the quick replies and the amazing react plugin!!!
