### ISSUE TITLE
"zoom into view" or "position into view"

### ISSUE THREAD

**Issue by artemis-prime** [istarkov/google-map-react#394]
Hi Ivan.  Great job on this component.  I love it!

One question:  say I'd like to zoom or re-position so that a given location is in view... Like, I have 5 venues that came up in a search, but one of them is off the current viewable area.  Is there a way that I could pass a prop to the component, a point or better yet an array of points, and then maybe a flag "zoom or re-position", so that it includes all of requested points?  Also maybe a buffer radius, so the outermost one's don't appear at the very edges.?  

Is there a way to do this?

thank you so much
Artyom

Dear users,
before you will write anything, please use search,
then please search again.

Most of problems you have is just an one line solution -
there is no need to change this library,
just add anything you want in your code.

Please look at examples, docs, apis - all of this were created for you not for me ;-).

**Comment by istarkov** [comment]
Please read this thread, and I think this https://github.com/istarkov/google-map-react/issues/3#issuecomment-272416565 is near what you need
