### ISSUE TITLE
Links in doc is not available

### ISSUE THREAD

**Issue by thientran1707** [istarkov/google-map-react#395]
I was reading the document here https://github.com/istarkov/google-map-react/blob/master/DOC.md
However, at the section "What's wrong with SimpleExample, then the link is not working"
I really appreciate if you can help me with this.

**Comment by thientran1707** [comment]
I was reading the document here https://github.com/istarkov/google-map-react/blob/master/DOC.md
However, at the section "What's wrong with SimpleExample, then the link is not working"
I really appreciate if you can help me with this.

**Comment by itsmichaeldiego** [comment]
@thientran1707 Thanks for your contrib, I am tackling this in #549
