### ISSUE TITLE
Markers do not update on triggering resize

### ISSUE THREAD

**Issue by mistaguy** [istarkov/google-map-react#397]
I am triggering resize on an Iframe Windows but the markers wont update correctly. See snippet of resize trigger

`           const originalCenter = this.googleMapReact.map.getCenter();
            this.googleMapReact.maps.event.trigger(this.googleMapReact.map, "resize");
            this.googleMapReact.map.setCenter(originalCenter);`

**Comment by mistaguy** [comment]
I found a work around. this could help someone else in future so i am closing this task.

```
            const originalCenter = this.googleMapReact.map.getCenter();
            this.googleMapReact.maps.event.trigger(this.googleMapReact.map, "resize");
            this.googleMapReact.map.setCenter(originalCenter);
            window.dispatchEvent(new Event("resize"));
```

**Comment by mgscreativa** [comment]
Hi! in my case, I solved by adding some map API call to the onChange event using some of your code:

Center the map on the marker lat-lng on viewport resize
```
...
...
  onChange = () => {
    if (this.googleMapReact.map_) {
      this.googleMapReact.map_.setCenter({ lat: this.props.lat, lng: this.props.lng });
    }
  };
...
...
      <GoogleMapReact
...
        onChange={this.onChange}
...
      >
 ...
...
      </GoogleMapReact>
...
...
```
