### ISSUE TITLE
Implement Google map theme

### ISSUE THREAD

**Issue by fresh5447** [istarkov/google-map-react#404]
Is there a simple way to implement a google map theme (mapStyle)? https://mapstyle.withgoogle.com/

I tried an implementation following this StackOverflow answer: https://stackoverflow.com/questions/34991638/google-map-react-custom-skins

You pass in the `JSON` style object as a prop called `defaultOptions` but I could not get any theme to show up. This answer is based on `react-google-maps`, which may be why it didn't work.

I wanted to check if there was a way to pass the theme in as a `prop`, before I went to far down any rabbit holes.

**Comment by istarkov** [comment]
why not to use search over the issues something like custom style, etc.

**Comment by itsmichaeldiego** [comment]
@fresh5447 Although I agree with @istarkov comment that you could find this easily, here it goes:

Our component `GoogleMapReact` accepts `options`, exactly like the normal `GoogleMap` does. So you can pass `styles` into properties, more info here: https://developers.google.com/maps/documentation/javascript/styling

Example:

```
  <GoogleMapReact
    zoom={props.zoom}
    center={props.center}
    bootstrapURLKeys={{
      key: process.env.MAP_KEY,
      language: 'en',
    }}
    options={
      styles: {
         ...yourStyles,
      }
    }
  >
    {props.children}
  </GoogleMapReact>
```
