### ISSUE TITLE
Get Markers nearest a location (or current location)?

### ISSUE THREAD

**Issue by artemis-prime** [istarkov/google-map-react#405]
Hi Ivan

I know that you implement markers in a different way, since you allow them to be any React components.  I'm wondering if there is a way that I can say "give me the N markers closest to me"?

thanks
Artyom

Dear users,
before you will write anything, please use search,
then please search again.

Most of problems you have is just an one line solution -
there is no need to change this library,
just add anything you want in your code.

Please look at examples, docs, apis - all of this were created for you not for me ;-).

**Comment by istarkov** [comment]
You can find every algorithm for geo data here https://github.com/mourner or at mapbox github 
For your case see this https://github.com/mourner/rbush-knn
Or if you have just few thousands markers you can just sort them by distance and take first N, it will be really fast. Or you can find Nth min by distance element and filter out all with less distance (have complexity O(n) but harder to implement vs sort solution with complexity O(n*log(n)))

**Comment by effortlesseffort** [comment]
Ah, thanks.  I meant more on a per call basis... If you have 100 locations in a city, and a user w a phone says, "get me the three closest locations please..."

**Comment by itsmichaeldiego** [comment]
@artemis-prime Let me know if you found an easy solution!
