### ISSUE TITLE
IE11 moveable marker breaks draggable map 

### ISSUE THREAD

**Issue by BartoszDega** [istarkov/google-map-react#406]
Hi

I was basing on 
https://jsbin.com/molerasebo/2/edit?js,console,output

But I have an issue in IE11, (examle above is not working on IE11 but is is separated problem)
If I move marker map moves as well (looks like draggable is set to true but I'm sure it isn't I have checked draggable everywhere and what is the most important it works perfectly on Chrome, Firefox or Edge

**Comment by paulincai** [comment]
Hi, the main page of this repo, the last line says that IE11 won't work because it doesn't support promises.

**Comment by TheDolo** [comment]
There is a workaround for this with polyfill, wish someone could give a code example that works :(

**Comment by BartoszDega** [comment]
Just in case  somebody is interested, finally I used https://codepen.io/anon/pen/PNooKz  for my react with google map

**Comment by itsmichaeldiego** [comment]
@BartoszDega It seems that you got the solution worked out, let me know if you need further help!
