### ISSUE TITLE
Displaying commercial points, and points of interest

### ISSUE THREAD

**Issue by hnrqer** [istarkov/google-map-react#408]
Hello,

I looked through the google documentation and this GitHub repository for this response, and I couldn't find a conclusive answer for this matter.

Two previous issues describing the problem were #79 and #389.

As I understood from google's documentation, the relevant places are already displayed in their simplest example from the API, and if there is need for activating it, it would be through this method: https://developers.google.com/maps/documentation/javascript/places

In my code I enabled the places API in my account, and also I'm adding it in the libraries:
            bootstrapURLKeys={{
              key: MY_KEY,
              libraries: 'places'
            }}

I didn't find any further options for displaying places in in google-map-react or google's API, and they do not show by default as emphasized in the previous issues  #79 and #389. Any ideas for this issue?

**Comment by istarkov** [comment]
Having that you have full access to google api, just check what u need with native non react example, and add in react code via options prop, or via onGoogleMapLoaded callback

**Comment by hnrqer** [comment]
Thanks @istarkov.
For the ones wondering how to solve this. Adding this style in the options solves it:
styles: [{
  "featureType": "all",
  "elementType": "labels",
  "stylers": [{
    "visibility": "#on"
  }]
}]
