### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by ccmeyers** [istarkov/google-map-react#41]
Better Documentation on how to use (or at least more comments in your examples explaining what you're doing) would be greatly appreciated.

**Comment by MozMorris** [comment]
Hi @ccmeyers, anything in particular that you feel isn't very clear? We're always open to new PRs if you want to add comments to any code that isn't self explanatory.

**Comment by ccmeyers** [comment]
Right now I'm trying to get hover states between a marker and table-row working like in your main example. There's a lot going on in this example that could use clarification. This could also be because I'm pretty new to react. But also, I've never used redux. So all of that is new for me as well. Is using redux necessary to make this functionality work?

**Comment by istarkov** [comment]
Using redux is not necessary, but it allows to share state across independent components like map and table in the example. 
Examples written just to show what can you do with this component, and just show map api usage. Tables and etc is not the main example part - i've added it just for fun.

**Comment by ccmeyers** [comment]
Okay, that's good to know. I wasn't sure if certain functions (and functionality) belonged to google-map-react or another library.

**Comment by mbrookes** [comment]
Hi Catherine - the README has a bit of info now. Far from complete, but the basics are there at least. Would be good if you could make any suggestions for additions / improvements based on your recent experience.

**Comment by martingg88** [comment]
just make a bower install library but the src folder is missing ? any steps can be given on how to call main js file in order to user this library?

**Comment by istarkov** [comment]
I close this because without any issue documentation always must be better.
