### ISSUE TITLE
resetBoundsOnResize has no effect

### ISSUE THREAD

**Issue by naBausch** [istarkov/google-map-react#410]
Hi :)
Thanks for your nice plugin, it works really well, besides one issue using resetBoundsOnResize in my project. Feels like setting it to true, doesn't have any effect.
Instead of changing the center of my map on resize nothing happens.
I built a very simplified demonstration of the problem:
https://codepen.io/bauschig/pen/KqepKq

Can you may help me out with this?

Thanks a lot!

**Comment by istarkov** [comment]
Hi thank you for the example.
You have explicitly fixed the map height in style, so height resizing would not help.
Also `defaultCenter` is used once at map init and resizing the map will not change it.
Use `controlable` component way, ie `center` `zoom` is in a state and respond and onChange event. 
BTW even with controllable way there is no logic to preserve map center on resize at rectangle center, if you need it you should intercept `resize` by your self and change center accordingly.

**Comment by naBausch** [comment]
Hi @istarkov :) 
Thank you very much for your quick response!
I may got wrong, what resetBoundsOnResize is doing here: 
https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L453-L460
Can you may explain it to me ?

**Comment by istarkov** [comment]
Triggers gmap map api that size of parent component has changed, so it can rerender map and fire needed events. Which allow me to call bounds changed etc.
It uses as I remember the same algorithm to detect control size change as like as AutoSizer at `react-virtualized`
Not sure I wrote this 2.5 years ago and this part was added by lib users.

**Comment by naBausch** [comment]
Ah ok thanks for the explanation :)
