### ISSUE TITLE
Any option to clear markers ?

### ISSUE THREAD

**Issue by Sanjay7035** [istarkov/google-map-react#411]
I am using this package for google map and that's work fine.
Now, My question is how to clear marker every time when page load.

I referred [API doc](https://github.com/istarkov/google-map-react/blob/master/API.md) but did not find any option to clear markers.

**Comment by istarkov** [comment]
Just don't pass marker as children

**Comment by Sanjay7035** [comment]
I am not passing markers first time but then after adding them dynamically on click of button. Then how markers are there on page loading ?

I think they are coming from google map cache.  Google map api provides such way to [clear markers](https://developers.google.com/maps/documentation/javascript/examples/marker-remove) before we add new one. Is there any option do this with our package ?

**Comment by istarkov** [comment]
I dont understand you at all.
This library renders react components over the google map in way as any React Component works. There are no google markers or google markers api here. 
In react if you dont need to render something you just dont render it, that's all.

**Comment by Sanjay7035** [comment]
I agree with you. But this is something which is coming google map api and it is being cache from their side. 

Another thing is that markers are there even if i open the page in different browsers. For example i open the page in chrome and adding markers by clicking button. Now if will open the same page in firefox then it will contains all markers which i had added in chrome. That's why i am talking about google map cache.

**Comment by istarkov** [comment]
Are u sure we are talking about this library? No cache etc here. Please check the name of library u are using

**Comment by Sanjay7035** [comment]
I am using this package [google-map-react](https://www.npmjs.com/package/google-map-react). I am not saying that this library is caching markers but it is using google map api which is caching data for specific api key.

**Comment by istarkov** [comment]
Please provide an example, as NO api at google can cache layers I use in this library.

**Comment by ravishah990** [comment]
Hi, I understand @Sanjay7035  problem. I think he use infinite scroller. when scroll down then dynamic data add in grid and using this data marker will added in map. but when page would be refresh then all marker are display in map. but his desired output is when page is refresh then only that marker would be display which data display in grid.

**Comment by Sanjay7035** [comment]
Yes @ravishah990  you are exactly near by my problem. It is not concern that how i am adding markers after page load because it's working fine for me. Actual problem is with clearing old markers on page load.

**Comment by istarkov** [comment]
Guys map renders it's children, it's impossible to render anything if it not exists in a children,
if you will provide me an example where components are rendered on the map but not exists in a children array I'll eat my hat.

**Comment by Sanjay7035** [comment]
Please refer below code.

`<GoogleMapReact
  bootstrapURLKeys={{
	key: '***********************',
	language: 'en',
  }}
  resetBoundsOnResize
  defaultCenter={this.props.center}
  defaultZoom={this.props.zoom}
>
  {
	this.props.markers.map(item => (
	  <Marker
		lat={item.lat}
		lng={item.lng}
		text={item.text}
	  />
	))
  }
</GoogleMapReact>` 

This is child component which render map. I am not sending props 'markers' first time on loading of page. After that i am sending it while using click on button.

**Comment by istarkov** [comment]
I'll stop responding since now until I see this on jsbin or codesandbox or any other place there I can run and see this.
jsbin base example you can find at project readme

**Comment by Sanjay7035** [comment]
Please refer example on below link 
[https://codepen.io/Sanjay7035/project/editor/ZpokRy/#0](https://codepen.io/Sanjay7035/project/editor/ZpokRy/#0)

**Comment by istarkov** [comment]
It doesn't work, preview window is empty.

**Comment by itsmichaeldiego** [comment]
@Sanjay7035 I was hoping to be any help but I also cannot see the codepen you provided.

I think what @istarkov wants to say is that, in order for you to clear the markers, you need to clear the content you're sending inside `GoogleMapReact` component, if you provide me with an example of your code I can totally help you with this. Please reopen the issue or create a new one if needed. Closing this one for now.

**Comment by Sanjay7035** [comment]
Sorry guys for the delay. Actually i am not working on this module since last few months. Thanks for you valuable time. I will check all your comments and will try to sort it out from my end and will get back here if any problem.

**Comment by itsmichaeldiego** [comment]
Thanks @Sanjay7035, let me know if you need help.

**Comment by shethmanan** [comment]
Hey just wanted to ask, so is there a method to clear all the markes from map? 

Situation: I load some markers. On some event i want to remove all these markers and load new ones. 
How do i do this?

**Comment by itsmichaeldiego** [comment]
@shethmanan As my colleague @istarkov was stating upstairs, you just need to clear the array that has the markers.

**Comment by shethmanan** [comment]
@istarkov I am rendering markers from state. Adding and removing data from the state to change markers, and it works perfectly. It's the same right?

**Comment by itsmichaeldiego** [comment]
@shethmanan My friend @istarkov is not active anymore, please refer to me 😄 

Yeah, you for example have an aux array of the markers you want to show, when you want to clear them, you call your redux or whatever you're using, and clear the aux array, that will remove the markers on the map. Exactly like if you would want to remove any react component from your DOM.

**Comment by Sanaullahbugti** [comment]
@itsmichaeldiego  I am getting the same issue. Even I am passing nothing to map but still it rendering points

**Comment by fire-cracker** [comment]
@Sanaullahbugti I am having the same issues. Have you been able to resolve this?

**Comment by sudddy** [comment]
@itsmichaeldiego I'm facing the same issue. I can add the marker and when i try to remove it by updating the state in redux, component is not rendered. Please help!

**Comment by Sanaullahbugti** [comment]
@sudddy @fire-cracker  put unique key for each marker it should work 
<MyMarker
                        lat={lat}
                        lng={lng}
                        key={item.key}
                    />

**Comment by HUSNAINGAUHER** [comment]
[Polyline][1]
<Polyline
      key={3}
      path={points}
      options={{ strokeColor: Config.Boundaries.Uc.color }}
      onLoad={(polyline) => setPolylines([...polylines, polyline])}

 polylines.forEach((pol) => pol.setMap(null))

  [1]: https://i.stack.imgur.com/W1HpB.png
If you are making markers/polyline using children, you should store marker/polyline reference in some state, you can use onLoad to get reference and can delete marker/polyline use polyline.setMap(null)

**Comment by rumfiske** [comment]
Still no fix?

**Comment by xsqox** [comment]
Can confirm the behavior is happening when markers array is being refreshed at the same time as map is being actively moved or zoomed in / out some markers can get stuck on the map.
