### ISSUE TITLE
resetBoundsOnResize doesn't do anything

### ISSUE THREAD

**Issue by epiqueras** [istarkov/google-map-react#415]
I don't see any differences with this property set to true or false, in both cases the map bounds stick to the top left corner.

**Comment by istarkov** [comment]
If you dont see anything this does does not mean that it do nothing. 
In your case why you decided that it somehow affects map bounds?

**Comment by epiqueras** [comment]
@istarkov 
What does it do then?

**Comment by istarkov** [comment]
It is an open source library, just open source

**Comment by epiqueras** [comment]
@istarkov 
```js
_mapDomResizeCallback = () => {
  this.resetSizeOnIdle_ = true;
  if (this.maps_) {
    const originalCenter = this.map_.getCenter();
    this.maps_.event.trigger(this.map_, 'resize');
    this.map_.setCenter(originalCenter);
  }
};
```

It looks like it preserves the center. This is not working though.

**Comment by istarkov** [comment]
Good :-) now you can investigate why :-)
then you can provide a PR if you need  this to work.

**Comment by epiqueras** [comment]
@istarkov 
I'll give it a try when I have time. I just wanted to know if this was known.
