### ISSUE TITLE
fitBounds returning NAN for zoom

### ISSUE THREAD

**Issue by kunwardeep** [istarkov/google-map-react#416]
on calling fitBounds I am getting the correct values for the center but zoom value is NAN This is my test data.
latitudes - 
[-36.7, -36.94, -36.42, -36.9, -36.97, -36.79, -36.95, -36.48, -36.88, -36.31]
longitudes -
 [144.82, 144.48, 144.6, 144.1, 144.45, 144.86, 144.48, 144.59, 144.33, 144.93]

minLatitude -36.97
maxLatitude -36.31
minLongitude 144.1
maxLongitude 144.9

```
  const latitudes =[-36.7, -36.94, -36.42, -36.9, -36.97, -36.79, -36.95, -36.48, -36.88, -36.31]
  const longitudes =[ 144.82, 144.48, 144.6, 144.1, 144.45, 144.86, 144.48, 144.59, 144.33, 144.93]
  const minLatitude = Math.min(...latitudes);
  const maxLatitude = Math.max(...latitudes);
  const minLongitude = Math.min(...longitudes);
  const maxLongitude = Math.max(...longitudes);
  
const bounds = {
    nw: {
      lat: minLatitude,
      lng: minLongitude
    },
    se: {
      lat: maxLatitude,
      lng: maxLongitude
    }
  };

  const size = {
    width: 600, // Map width in pixels
    height: 740 // Map height in pixels
  };
  return fitBounds(bounds, size);
```

<img width="777" alt="screen shot 2017-07-16 at 2 06 15 am" src="https://user-images.githubusercontent.com/13211086/28240828-b8c69a04-69cb-11e7-81c5-026df3c66536.png">

**Comment by kunwardeep** [comment]
Any comments?

**Comment by istarkov** [comment]
Just think about what is nw and se then look what you pass into
