### ISSUE TITLE
[IE11] Map Drag

### ISSUE THREAD

**Issue by pts-ccontreras** [istarkov/google-map-react#418]
Hi @istarkov,

I found an issue while using Internet Explorer 11 (I'm already using polyfill). 
When navigating on the map, if you drag the map fast enough you end up dragging the entire container. 

See attached preview for more details:
https://i.gyazo.com/f407ea4759ca933e4c62bc4bd05c0b2e.gif

Any Ideas? Thanks!

**Comment by istarkov** [comment]
Dont want even think about ie :-) It can be anything.

**Comment by itsmichaeldiego** [comment]
@pts-ccontreras I am planning to do a quick fix to iE 10 & iE 11 soon. The gif you provided is not working anymore, would you mind to open a new issue and I will take a look? Thanks.
