### ISSUE TITLE
Prevent google maps api loaded twice

### ISSUE THREAD

**Issue by edcolcode** [istarkov/google-map-react#420]
Hi all,

I'm using this amazing library but I have an issue: if I want to load the google maps api externally before the map component is displayed I get this error message: You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

There is an option to disable the 'Loads on Demand' feature?

Thanks!

**Comment by ribeiroguilherme** [comment]
Hi @edcolcode , I was with a similar situation as you are, I was using the places API in other components without the map, getting the error that it was been loading twice. I did what @istarkov wrote here #303 Loading the API on demand inside the component that you would like to load it.

**Comment by edcolcode** [comment]
Thanks a lot @ribeiroguilherme.
