### ISSUE TITLE
Zoom below 4 renders always to 4

### ISSUE THREAD

**Issue by EbrahimMajdey** [istarkov/google-map-react#421]
If I set the defaultzoom to less than 4 it renders always to 4 

how can I set the zoom to less than 4, i.e. 1, 2,3

**Comment by istarkov** [comment]
search issues with minZoom keyword

**Comment by EbrahimMajdey** [comment]
Thanks , but I am now getting this message . 
minZoom option is less than recommended minZoom option for your map sizes.
overrided to value 3

**Comment by EbrahimMajdey** [comment]
any update

**Comment by EbrahimMajdey** [comment]
If I set the defaultZoom to less than 3 and use minZoomOverride to true, the map zooms more than expected, if the size of the map width and height larger than 512 px .. which is strange !
I assume there is some mistake in the zoom and edges calculation .. I really couldn't follow the code to understand where is the problem

**Comment by EbrahimMajdey** [comment]
I was a bit wrong only when the width is above 798 thinks go crazy

**Comment by itsmichaeldiego** [comment]
@EbrahimMajdey We're wrapping all the zoom minZoom issues in #544 and we going to address it soon, feel free to comment in there, we will need help to make this work!
