### ISSUE TITLE
Centering marker using flexbox

### ISSUE THREAD

**Issue by mvanlonden** [istarkov/google-map-react#423]
In the new docs you mention you can center the map markers using flexbox instead of absolute positioning. The example link is broken so I can't see how you would do that.

Could you provide a snippet of how this is done?

**Comment by istarkov** [comment]
Can you just use a flexbox for item centering? I did examples but the resource I hosted them moved. I have no time to repeat that examples again.
And after you did that can you share the results?

**Comment by Delindel** [comment]
@mvanlonden did you even found a way to do it man?

**Comment by mvanlonden** [comment]
I don't think I did. I think I just hacked around the issue with negative margins

**Comment by Delindel** [comment]
Oh damn, i feel ya. Im just getting into this and im wondering how to dynamically center the map in given coordinates (as ofc updating state does not work for GMaps component)

**Comment by itsmichaeldiego** [comment]
@Delindel This might be helpful for you: https://github.com/istarkov/google-map-react/issues/513#issuecomment-366349225

**Comment by itsmichaeldiego** [comment]
@Delindel I am closing this issue as it is old. But please if you're facing this problem still, feel free to create a new issue.
