### ISSUE TITLE
Map not updating center position if it happens to quickly after componendDidMount

### ISSUE THREAD

**Issue by ondrejrohon** [istarkov/google-map-react#424]
After my map component successfully mounts it is updated via props as a result of fetching data from server. If that result arrives too quickly, about 100 ms, map position does not update. Try different values in setTimeout of componentDidMount. Everything works fine if I set delay of around 500ms. I can see in React tab of developer tools that <GoogleMapReact /> component correctly receives new value via prop. Any ideas why this happens?

Here is the code for recreating the issue:

```
import React, { Component } from 'react';
import GoogleMapReact from 'google-map-react'

class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      center: { lat: 48.15166593048124, lng: 17.112003130590864 }
    }
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        center: {
          ...this.state.center,
          lat: 48.17,
        }
      })
    }, 100)
  }

  render() {
    return (
      <div className="App" style={{height: '800px'}}>
        <GoogleMapReact
          center={this.state.center}
          zoom={18}
        />
      </div>
    );
  }
}

export default App;
```

**Comment by colafati** [comment]
Did you try to use onGoogleApiLoaded function instead componentDidMount?

**Comment by ondrejrohon** [comment]
@colafati you're right, google maps api is not loaded when I call setState so it does not update center position. Thanks.
