### ISSUE TITLE
npm install --save google-maps-react

### ISSUE THREAD

**Issue by igrowsquareroots** [istarkov/google-map-react#425]
Hello, 
I am new to react and am trying to implement react for my high school to access google maps. However, on attempting to install I got the following errors:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint@^3.19.0 but none was installed.
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint-plugin-jsx-a11y@^5.0.3 but none was installed.
npm WARN react-google-map@3.0.1 requires a peer of react@~15.4.0 but none was installed.
npm WARN worker-loader@0.8.1 requires a peer of webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0 but none was installed.

![image](https://user-images.githubusercontent.com/19295997/28700410-7dde12cc-7304-11e7-96aa-0e068d602f67.png)

**Comment by istarkov** [comment]
Warning is not errors. This library has nothing with google-maps-react
