### ISSUE TITLE
onChange called on map init

### ISSUE THREAD

**Issue by jkettmann** [istarkov/google-map-react#426]
I have a use case, where I rerender the map directly after initial render. Following is quite similar to my component:

	class Map extends React.Component {
	  constructor(props) {
	    super(props);
	    this.state = {
	      center: props.center,
	    };
	  }

	  componentWillReceiveProps(nextProps) {
            // deep equal comparison
	    if (!isEqual(nextProps.center, this.props.center) {
	      console.log('setCenter', nextProps.center);
	      this.setState({ center: nextProps.center });
	    }
	  }

	  onChange = ({ center }) => {
	    console.log('onChange', center);
	    this.setState({ center });
	  }

	  render() {
	    const {
	      markerCoordinates,
	    } = this.props;

	    const {
	      center,
	    } = this.state;

	    return (
	      <GoogleMapReact
		center={center}
		zoom={14}
		onChange={this.onChange}
	      >
		<Marker coordinates={markerCoordinates} />
	      </GoogleMapReact>
	    );
	  }
	}

So the component is supposed to update `center` in its state when its parent component changes the `center` prop. The parent component is rerendered with a different center directly after the initial render. 

The problem is, that `google-map-react` calls `onChange` after `_initMap` [here](https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L485). First my state gets updated in `componentWillReceiveProps`, but shortly after `onChange` is called with the initial center and thus resets the state.

This seems to me quite confusing. It seems, that my component has to keep track, if onChange is called the first time and only if not update the state. Perhaps an `onInit` callback would be more appropriate here. What do you think?

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/blob/master/DOC.md
read Note about onChange and wrong decision

**Comment by jkettmann** [comment]
Seems reasonable, that the call to the internal `_onBoundsChange` and also a separate external `init` callback are necessary. But as a user of the libs API I expect `onChange` to be called only when the user interacted with the map. An input component like a text field also wouldn't call onChange after initialization.

**Comment by istarkov** [comment]
I wrote there the same.

**Comment by jkettmann** [comment]
Ah sorry, I missed the note
