### ISSUE TITLE
bootstrapURLKeys dosent work

### ISSUE THREAD

**Issue by rafalradomski** [istarkov/google-map-react#430]
**bootstrapURLKeys** dosen't work when I using it with  **react 16**

but when I add key in html it works:

`<script src="//maps.googleapis.com/maps/api/js?key=MY_KEY" async="" defer="defer" type="text/javascript"></script>`

... and why there is no information in doc that I need add it? That's crucial information

```
            <GoogleMapReact
                bootstrapURLKeys={{
                    key: 'my key'
                }}
                defaultCenter={this.props.center}
                defaultZoom={this.props.zoom}
                height="200"
            >
                <Point lat={this.props.lat} lng={this.props.lng}  text={'Test'} />
            </GoogleMapReact>
```

**Comment by wayweary** [comment]
Doesnt work for me as well :/. However, if i do add this css to the map div it will "work"
```
.map-container > div {
    position: initial !important;
}
```
Ie i remove the position fixed that the GoogleMapReact will get

**Comment by wayweary** [comment]
Ooops, just saw this: "Make sure the container element has width and height. The map will try to fill the parent container, but if the container has no size, the map will collapse to 0 width / height."
https://github.com/istarkov/google-map-react/blob/master/API.md

**Comment by mikkopori** [comment]
I believe the issue is that if you put the key in state etc. it does not work, if you hardcode to the client it works.

Just trying to figure out how to solve this as I would like to secure my key better and use different keys for different env (and secure the key usage by binding it to that domain).

This also follows Google's instuctions on how to handle API keys:
https://support.google.com/googleapi/answer/6310037?hl=en

Any ideas are welcome!

**Comment by mikkopori** [comment]
Solved the thing with conditional rendering: https://facebook.github.io/react/docs/conditional-rendering.html

`    var reactmap = "";
    if(this.state.api_key) {
      reactmap =  <GoogleMapReact
        defaultCenter={this.props.center}
        defaultZoom={this.props.zoom}
        center={this.state.center}
        zoom={this.state.zoom}
        onClick={this.unconfirm}
        layerTypes={['TransitLayer']}
        yesIWantToUseGoogleMapApiInternals={true}
        onGoogleApiLoaded={({map, maps}) => this.setState({maps: maps, map: map})}
        options={createMapOptions}
        bootstrapURLKeys={this.state.api_key}
      >
      </GoogleMapReact>
`
as render is called many times and only in the last call it has the api-key. So I'm preventing the map from loading until it has the key.

**Comment by MohammedFarooqS** [comment]
hi can you provide options you are using ?
how to show in mobile map at top

**Comment by mitramejia** [comment]
@mikkopori use env variables for different envs

`        const mapKeys = {
            key: process.env.GOOGLE_MAPS_API,
            language: 'en',
        }`

**Comment by itsmichaeldiego** [comment]
Works fine by me, please see [this example](https://github.com/itsmichaeldiego/google-map-react-examples/blob/master/src/components/GoogleMap.js#L18).

If the problem persists please feel free to create a new issue. We're doing a cleanup! Thanks.
