### ISSUE TITLE
Question - use of High order component in library and examples.

### ISSUE THREAD

**Issue by kktam** [istarkov/google-map-react#431]
Inside the google-map-react library contains a number of High order components, such as code in GMap.js , GMapLayers.js, GMapOptim.js.

There are not compiled as part of the library UMD files. and not mentioned in readme pages. 

1. Does these code meant to serve as examples on how to use the library optimally?
2. is there any documentation on use of these HOCs?

**Comment by itsmichaeldiego** [comment]
@kktam Sorry for the delay, the files you're mentioning are part of our Develop environment, its used by us to test Google Maps.

The high order components we're using its just a personal preference back in the time this library was written. 

Let me know if you need help to work with this library, or please feel free to open a new issue if you encounter any, thanks in advance.
