### ISSUE TITLE
Access to Google map handle in children?

### ISSUE THREAD

**Issue by bear-bibeault** [istarkov/google-map-react#435]
Is there a way to access the actual Google map handle in the child components for the rare case where a native method or value needs to be referenced?

I need access to the native API's `overlayMapTypes` array so I can add/remove custom tile overlays.

Thanks!

**Comment by ajay-gandhi** [comment]
You would have to pass the map as a prop. See https://github.com/istarkov/google-map-react/blob/master/API.md - in the callback for `onGoogleApiLoaded`, save the ref to the map and then pass it as a prop to children in the map.

**Comment by itsmichaeldiego** [comment]
@bear-bibeault As @ajay-gandhi pointed out, we do have a `onGoogleApiLoaded` option that will call the function you pass with the api data as soon as its loaded.
