### ISSUE TITLE
How to reinitialise map with new language?

### ISSUE THREAD

**Issue by williamli** [istarkov/google-map-react#436]
My website has a language toggle that passes language props down to GoogleMapReact.
It is passed as part of the bootstrapURLKeys 

```
    let bootstrapURLKeys={
      key: Meteor.settings.public.googleMapKey,
      language: !_.isEmpty(lang) ? lang : "en"
    }
```

I can set the initial language of the map fine but it is impossible for me to change the language used by Google Map without a full page refresh.

It there a way for me to reinialise the Google Map with a new language?

**Comment by istarkov** [comment]
Only if it possible with google api. As I know it's not.
