### ISSUE TITLE
Draggable markers also drag map firefox

### ISSUE THREAD

**Issue by amiiigh** [istarkov/google-map-react#438]
Hi 
I implement [this code](https://jsbin.com/molerasebo/2/edit?js,console,output) and it works perfect on chrom but in firefox v55 when you try to drag the marker it also drags the map

any idea how to fix this ?

**Comment by amiiigh** [comment]
It can be fixed by changing onChildMouseDown to onChildMouseEnter

any other way?

**Comment by mnmistake** [comment]
what are those :: at the start of the functions mate? i cant get your example to work
