### ISSUE TITLE
Documentation on Dynamically adding Markers

### ISSUE THREAD

**Issue by jaylaw81** [istarkov/google-map-react#439]
Any examples or documentation on adding markers dynamically to a rendered map?

**Comment by JonDum** [comment]
Just do it like you would with any other React component.

```
<GoogleMap>
   {markers.map( props r => <Marker {...props}/>);
</GoogleMap>
```

**Comment by Benornm** [comment]
How can i get a normal marker sign? 
I need to create my own <Marker/> ? 
I just want the default ..

**Comment by ajay-gandhi** [comment]
@Benornm if you want the original Google Maps markers, you would have to use the Google Maps API. See API.md

**Comment by itsmichaeldiego** [comment]
@Benornm You can just create one using pure CSS. [Here is an example](https://github.com/itsmichaeldiego/google-map-react-examples/blob/master/src/components/Marker.js#L6)

You can also use an svg image or anything you want. But it has to be a valid element or react component.

@jaylaw81 Were previous comments helpful? If you still need help please feel free to contact me or create a new issue.

@ajay-gandhi Thanks for your contribution.
