### ISSUE TITLE
Update to @mapbox/point-geometry

### ISSUE THREAD

**Issue by eelfonik** [istarkov/google-map-react#445]
Hello, thanks for the great lib.
I recently got a warning saying:
`WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead`.

Do you have a plan to upgrade to the latest version? If I got it right, we have only used that in `src/utils/lib_geo/transform.js` to create point geometry, and it doesn't change API or anything. 

Thanks!

**Comment by quiqueg** [comment]
Duplicate of #382

**Comment by itsmichaeldiego** [comment]
Duplicate of #382
