### ISSUE TITLE
fitBounds returning wrong center

### ISSUE THREAD

**Issue by omerts** [istarkov/google-map-react#446]
Hey,

Fitbounds util function seems to be returning the wrong center.
Here is a fiddle to reproduce our problem:
https://jsfiddle.net/omerts/ndo35v4t/4/

How we call the function:
```
fitBounds({
            nw: { lat: 34.745555, lng: 35.07048499999996 },
            se: { lat:32.745555, lng: 35.07048499999996 }
          }, 
          {
            width: 955, // Map width in pixels
            height: 450 // Map height in pixels
          }))
```

Actual (Invalid) result:
`{ center: { lat: 33.75138591767201, lng: -144.92951500000004 }}`

Expected result (taken from google's getCenter function)
`{ center: { lat: 33.745555, lng: 35.07048499999996 }}`

**Comment by istarkov** [comment]
You are passing a line into, not a rectangle, see lng. With such input equations for zoom will not be solved so there is no need to provide a good result for anything else.

**Comment by omerts** [comment]
@istarkov it still sounds like a bug to me, why would this function not know how to deal with lines?

**Comment by istarkov** [comment]
for my usecases this is enough. I see no reason to check and validate every input, I have a better ideas how to spend my time and this is not writing obvious checks

**Comment by omerts** [comment]
This is not input validation, nor an obvious check. We are not passing an invalid input. Getting the zoom, and center of two points on a line, is a perfectly valid and logical use case. 
If you don't want/have time to deal with it, you can add an enhancement tag etc., but not just close the issue and throw it off.

**Comment by istarkov** [comment]
If you really want to change something just provide a PR, fork, just do anything instead of writing words

**Comment by mrandreev** [comment]
Just quick fix to get it works:

`if (points.length === 1) {
            bounds.nw.lat += 0.00001;
            bounds.nw.lng -= 0.00001;
        }`
