### ISSUE TITLE
How to disable map zoom when scrolling inside a scrollable child component?

### ISSUE THREAD

**Issue by Nitsorn** [istarkov/google-map-react#448]
Hello, 
Is there a way to disable map scrolling when you hover over a scrollable child component inside GoogleMapReact? I still would like to keep `scrollwheel: true` for it to zoom on scroll when hovering on the map itself.

Thank you in advance.

**Comment by istarkov** [comment]
You already answered on your question, you need to disable scrollwheel when you hovering on a child. All events exists in html :-) scrollwheel disabled via options

**Comment by Nitsorn** [comment]
You are right! Thank you :) I didnt see the `onChildMouseEnter` and `onChildMouseLeave` props.

**Comment by istarkov** [comment]
@Nitsorn You can use dom onMouseEnter onMouseLeave it will be easier

**Comment by Delindel** [comment]
Hey guys, sorry to revive an old thread but im having a similar issue.

Scenario:
- I have a child Marker component which is 30px by 30px. 
- Marker has child Window component, which is 200px by 100px.

Problem: When i click on Marker, the child Window expands to show another button, however any click i give on this child will translate into a map click, ignoring this child and its size.

By using DOM onMouseEnter onMouseLeave onClick i can go around it but will only work on Chrome, on any other browser DOM events are completely ignored if i dont use the Map onChildClick, etc.

Is there something super obvious im missing?

Thanks in advance for thaking your time.
