### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by ankitduseja** [istarkov/google-map-react#449]
Peer Dependency needs to be updated for React 16

**Comment by istarkov** [comment]
and?

**Comment by wiesson** [comment]
What does your "and" suppose to mean?

It would be nice if you add ` || ^16.0.0` to the as peer dependency. (I also could help with a PR)

**Comment by Exomnius** [comment]
#454

**Comment by stunaz** [comment]
why this still open?
