### ISSUE TITLE
PropTypes not fully fixed

### ISSUE THREAD

**Issue by andrevenancio** [istarkov/google-map-react#455]
There's still reference to PropTypes being pulled from the 'react' package instead of the `prop-types` package.
Mainly on the `develop` folder.
Like:
https://github.com/istarkov/google-map-react/blob/2ec7048ab22e9118f020c048580fd416304bb41e/develop/GMap.js#L1

**Comment by jaredpalmer** [comment]
This is blocking our React 16 upgrade . 😢

**Comment by istarkov** [comment]
Guys it's just development helper source, 
it does not affect library somehow.
I used it to develop library itself ;-) library uses `prop-types` since first days it was published.

**Comment by andrevenancio** [comment]
There's a reference in package.json for a `lib/indes` in the main. I can't seem to find that folder on the project. I wonder if because of that we load a folder we shouldn't load when we import the library via npm? Also might be related to the babel-loader including all `.js` files. But when I import just this project with React 16, I do see the warning. :)

**Comment by jaredpalmer** [comment]
Nvm we upgrade to 0.24 and are all good
