### ISSUE TITLE
"main": "lib/index" but lib/index.js not found 

### ISSUE THREAD

**Issue by akichim21** [istarkov/google-map-react#456]
I want to preempt React 16. I write package.json, and npm i
{
  "dependencies": {
    "google-map-react": "istarkov/google-map-react"
  }
}

but ./node_modules/google-map-react/lib not found
so Typescript error: Module not found: Error: Can't resolve 'google-map-react'

I rewrite google-map-react, and npm i; npm run build:lib; in google-map-react directory, fix this problem.
I want lib directory to exist, when git clone google-map-react.
or
goole-map-react version is compatible to React 16, when npm i --save google-map-react.

**Comment by itsmichaeldiego** [comment]
@akichim21 Sorry but this is not clear enough, if you're still facing this issue feel free to create a new one with a better description and I will help you out. Thanks in advance!
