### ISSUE TITLE
Component directions

### ISSUE THREAD

**Issue by Anchmil** [istarkov/google-map-react#457]
Hello! Can you tell me how can I create a component directions like this [https://developers.google.com/maps/documentation/javascript/examples/directions-waypoints?hl=ru](https://developers.google.com/maps/documentation/javascript/examples/directions-waypoints?hl=ru)
I can not understand how to display the route on a map. Please help someone.
Now my component looks
```
directServ = () => {
		googleMapLoader(bootstrapURLKeys)
		.then((maps) => {
			const directionsService = new maps.DirectionsService();
			const directionsDisplay = new maps.DirectionsRenderer();
			directionsService.route({
				origin: 'Boston, MA',
				destination: 'Vancouver, BC',
				travelMode: 'DRIVING'
			}, (response, status) => {
				if (status === 'OK') {
					directionsDisplay.setDirections(response);
					console.log(response.routes[0])
				} else {
					window.alert('Directions request failed due to ' + status);
				}
			});
		})
	};
	render() {
		return (
			<button type="button" onClick={this.directServ}>directionClick</button>
		)
	}
```

**Comment by vkatatab** [comment]
@Anchmil, you could use the prop yesIWantToUseGoogleMapApiInternals and implement the onGoogleApiLoaded to get the maps ref. and do whatever you want!

**Comment by Plainlazy01** [comment]
All I can say is I don't know about this stuff im tryring to figure it out thank you for you help and having a problem with drop pin on some of the maps it not dropping on the dot

**Comment by henriquemattos** [comment]
@vkatatab does it have any implications in other functionalities to set this prop (yesIWantToUseGoogleMapApiInternals)? I'm also looking to place a route in my map.

**Comment by itsmichaeldiego** [comment]
@henriquemattos It does not have big implications but we recommend to always find a workaround without using api internals. Otherwise it is fine, I use it myself.

**Comment by henriquemattos** [comment]
@itsmichaeldiego sorry took me so long to see your comment and thanks for your suggestion. I'm currently wondering how to place the route on a map. Right now my app is a bus locator where I have several vehicles being tracked by GPS so I auto-refresh the pins for buses to get update the coordinates. As for the bus stations, they do not move (duh! haha), so no auto-refresh. 

I would like to create a route between the bus stations so that the buses pins would be "driving their way to the next stop". Any tip? I don't know what to do after setting the param "yesIWantToUseGoogleMapApiInernals".

Right now this is my config where referencePointsList is an array of buttons with icons to flag as pin/map marker. The same for vehiclesInRoute:
```
<GoogleMapReact
        bootstrapURLKeys="myFancySecretKey"
        defaultCenter={this.mapCenter}
        center={this.props.mapCenter}
        defaultZoom={this.mapZoom}
        zoom={this.props.mapZoom}
>
    {this.referencePointsList}
    {this.vehiclesInRoute}
</GoogleMapReact>
```

**Comment by itsmichaeldiego** [comment]
@henriquemattos Pretty simple, there is a function callback called `onGoogleApiLoaded` that you can use, you just do this:

```
<GoogleMapReact
        bootstrapURLKeys="myFancySecretKey"
        defaultCenter={this.mapCenter}
        center={this.props.mapCenter}
        defaultZoom={this.mapZoom}
        zoom={this.props.mapZoom}
        yesIWantToUseGoogleMapApiInternals
        onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps)}
>
    {this.referencePointsList}
    {this.vehiclesInRoute}
</GoogleMapReact>
```

```
const apiIsLoaded = (map, maps) => {
  if (map) {
    // do your thing with map or maps
  }
};
```

**Comment by henriquemattos** [comment]
@itsmichaeldiego works like a charm. Thank you very much.

**Comment by itsmichaeldiego** [comment]
@henriquemattos You're welcome, anytime!

**Comment by rfigueror1** [comment]
Hi @henriquemattos , I am having a very similar issue and I saw this post. Is there a chance you can show me the content of the apiIsLoaded function after your workaround of the problem?

**Comment by henriquemattos** [comment]
Hi, @rfigueror1 . Well, I customized a lot and ended up using Polylines instead of directions, but I think you can start from something like this:
```javascript
// Map.jsx
render() {
 return (
    <GoogleMapReact
        bootstrapURLKeys="myFancySecretKey"
        defaultCenter={this.mapCenter}
        center={this.props.mapCenter}
        defaultZoom={this.mapZoom}
        zoom={this.props.mapZoom}
        yesIWantToUseGoogleMapApiInternals
        onGoogleApiLoaded={ this.setMap }>
        {this.referencePointsList}
        {this.vehiclesInRoute}
    </GoogleMapReact>
    )
}

setMap(args) => {
    const map = args.map;
    const maps = args.maps;
    if (maps && typeof(maps.DirectionRenderer) === "function") {
        // clean previous directions rendered to the map;
        const directionDisplay = new maps.DirectionRenderer();
        const directionDisplay.setOptions(/* options: DirectionsRendererOptions */);
        directionsDisplay.setMap(maps);
    }
    const routePolyline = new google.maps.Polyline(/* options: google.maps.PolylineOptions */);
    routePolyline.setMap(maps);
}
```
Check [Polyline Options](https://developers.google.com/maps/documentation/javascript/reference/polygon#PolylineOptions) and [DirectionsRendererOptions](https://developers.google.com/maps/documentation/javascript/reference/directions#DirectionsRendererOptions) for structure of options object.

Hope it works, it's been a couple months I'm not working in that project anymore! hehe ☺️

**Comment by itsmichaeldiego** [comment]
@henriquemattos Thank you for helping! Do you think there is a chance you could add example with on our new examples? https://github.com/google-map-react/google-map-react-examples

**Comment by henriquemattos** [comment]
@itsmichaeldiego I will fork the repo, create an example using Polylines (and if I still remember using DirectionsRenderer) and provide you a PR next week. I'm overwhelmed till Monday (12). Is that ok?

**Comment by rfigueror1** [comment]
Thanks both for your help!

**Comment by itsmichaeldiego** [comment]
@henriquemattos That is totally fine! Gracias!

**Comment by rfigueror1** [comment]
@henriquemattos it worked beautifully, thanks a lot, you still got it! If it is helpful for the future, here is an example using Henrique's wisdowm of the render function after the drectionsService callback and the use of polylines.

`const apiIsLoaded = (map,maps) => {
        const directionsService = new maps.DirectionsService();
        const directionsDisplay = new maps.DirectionsRenderer();
        directionsService.route({
          origin: 'Av 565 145, San Juan de Aragón II Secc, 07969 Ciudad de México, CDMX, Mexico',
          destination: 'Piña MZ3 LT8, Ampliacion Lopez Portillo, 13400 Ciudad de México, CDMX, Mexico',
          travelMode: 'DRIVING'
        }, (response, status) => {
          if (status === 'OK') {
            directionsDisplay.setDirections(response);
            console.log(response.routes[0].overview_path, 'Ruta')
            const routePolyline = new google.maps.Polyline({
              path: response.routes[0].overview_path
            });
            routePolyline.setMap(map);
          } else {
            window.alert('Directions request failed due to ' + status);
            }
          });
    };

return (
      // Important! Always set the container height explicitly
      <div>
        <Title> Leanit Fleet </Title>
        <Right_Box>
          <SubTitle>Resumen de transportes</SubTitle>
          <ul>{listItems}</ul>
        </Right_Box>
        <div style={{ height: '100vh', width: '65%' }}>
          <GoogleMapReact bootstrapURLKeys={{ key: api_key_maps}} 
            defaultCenter={this.state.center} 
            defaultZoom={this.state.zoom} 
            yesIWantToUseGoogleMapApiInternals 
            onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps)}>
             {
            //Add a list of Markers to Your Map
            this.state.myMarkers.map( (each) =>
              <Marker 
                lat = {each.lat}
                lng = {each.lng}
                text = {each.text}
              />
            )
          }      
          </GoogleMapReact> 
        </div>
      </div>
    );
`

**Comment by itsmichaeldiego** [comment]
@henriquemattos I will! Thanks. Let me know if you need any help to create the example at [google-map-react-examples](https://github.com/google-map-react/google-map-react/examples)!
