### ISSUE TITLE
Support for Google Places API

### ISSUE THREAD

**Issue by hwclass** [istarkov/google-map-react#459]
Hi folks,

I've searched the issues and PRs but couldn't find anything related with that. In my project, I've just wanted to use google maps places api as well and searched for the possibilities to integrate/use with this library but i couldn't see any details related with that. Do you know anything about it?

Thanks

**Comment by buksy90** [comment]
Hello,

you need to list google libraries you would like to use in `bootstrapURLKeys`, then you would be able to use places.

```
const bootstrapURLKeys = { key: '####', libraries: 'places' };

onGoogleApiLoaded({map, maps}) {
    // here it is, maps is actually window.google
    console.log(maps.places);
});

<GoogleMapReact
                    bootstrapURLKeys={bootstrapURLKeys}
                    onGoogleApiLoaded={this.onGoogleApiLoaded}
                >
```
