### ISSUE TITLE
Street View in Map Type Selection

### ISSUE THREAD

**Issue by deboroy** [istarkov/google-map-react#463]
Hi

Is it possible to include `StreetView` in the Map Type Selection? Currently StreetView is supported through `props` which shows the `Pegman`. But it is still left to the user to drop the pegman at the right point. 

With StreetView in the map dropdown, it will be easier to center the `Panoramic` View with the input Lat, Long.

**Comment by itsmichaeldiego** [comment]
@deboroy Unfortunately we are not going to prioritize this until fixing all the current issues of the map. Please feel free to open a PR with the changes if you find a workaround, we will then merge and test it.
