### ISSUE TITLE
Bottom center

### ISSUE THREAD

**Issue by jeremymarc** [istarkov/google-map-react#465]
Hi,

I'm trying to center a Pin at the bottom of the map like that https://www.dropbox.com/s/fq94dykegpzsukb/Screenshot%202017-11-16%2012.59.00.png?dl=0.

What's the easiest way of doing that?

**Comment by itsmichaeldiego** [comment]
@jeremymarc Cannot open the link, if the problem persist, please open a new issue and we will take a look. Thanks!
