### ISSUE TITLE
Calc radius from bounds

### ISSUE THREAD

**Issue by nguyenthithao** [istarkov/google-map-react#467]
Hi everyone,
From maps we can get bound of it with 
const {topLat, leftLng, bottomLat, rightLng} = bounds

How to get the distance between them and the radius of circle around 4 points topLat, leftLng, bottomLat, rightLng?

**Comment by itsmichaeldiego** [comment]
@nguyenthithao Let me know if this is helpful: https://github.com/istarkov/google-map-react/issues/512#issuecomment-366352763

If the problem persists please create a new issue with more details, thanks for using https://github.com/istarkov/google-map-react/
