### ISSUE TITLE
Is it possible to show multiple markers on the same location?

### ISSUE THREAD

**Issue by rahulthewall** [istarkov/google-map-react#468]
Is it possible to show multiple markers at the same exact location?

**Comment by itsmichaeldiego** [comment]
@rahulthewall Yes, that is possible, what problem are you facing?

**Comment by rahulthewall** [comment]
Hi @itsmichaeldiego, we had a situation where we had two businesses on the exact same location. While rendering, we believe that the pins were being rendered on top of each other which was why only one was visible. 

It would be great if you could provide an example of rendering two pins on the exact same location. 

Unfortunately, I don't have access to the project any more (switched jobs) so I can't provide any implementation details at this stage.

**Comment by itsmichaeldiego** [comment]
@rahulthewall Yes, it makes sense that they're rendered in top of each other as they're in the same location, remember they're pure React components, so if you want to highlight one on top of the other, you could simply use `zIndex: 1` when active in one of them.
