### ISSUE TITLE
Makers show wrong position even set {top, left} when zoom out!?

### ISSUE THREAD

**Issue by nguyenthithao** [istarkov/google-map-react#470]
Dear all,
The marker I'm using css class like this
{
    width: 50px;
    height: 50px;
    top: -25px;
    left:-25px;
}
It show perfect if the map zoom in, but when I zoom out they seem go wrong way ?!
How do I deal with it?

**Comment by mpourismaiel** [comment]
I have the same problem using slightly different styling:
```
.marker {
  position: absolute;
  width: 50px;
  height: 50px;
  top: -25px;
  left:-25px;
}
```
Anything I'm missing? The code above is taken from [API.md](https://github.com/istarkov/google-map-react/blob/master/API.md#positioning-a-marker)

**Comment by ArmanMazdaee** [comment]
I my case, the issue had been fixed by adding the fallowing style to the marker:
```
transform: translateY(-50%);
```

**Comment by itsmichaeldiego** [comment]
@ArmanMazdaee is right, the correct approach would use to use transform.
