### ISSUE TITLE
React 16 dependency

### ISSUE THREAD

**Issue by kossel** [istarkov/google-map-react#475]
Would you consider update the dependency to react 16?

**Comment by itsmichaeldiego** [comment]
@kossel The dependency was updated to react 16 in #454. Are you facing a problem?

**Comment by kossel** [comment]
That's weird I swear I saw somewhere the package.json says peer to react 15 only. my bad

**Comment by itsmichaeldiego** [comment]
@kossel No worries, thanks for checking!
