### ISSUE TITLE
IE10 Unable to get property 'center' of undefined or null reference

### ISSUE THREAD

**Issue by falconmick** [istarkov/google-map-react#476]
This issue occurred before in #223 and is back with a vengeance... 
On only IE10 this is happening:
IE10 Unable to get property 'center' of undefined or null reference

code that causes issue:

	    _this.mounted_ = false;
	    _this.initialized_ = false;
	    _this.googleApiLoadedCalled_ = false;
	
	    _this.map_ = null;
	    _this.maps_ = null;
	    _this.prevBounds_ = null;
	
	    _this.layers_ = {};
	
	    _this.mouse_ = null;
	    _this.mouseMoveTime_ = 0;
	    _this.boundingRect_ = null;
	    _this.mouseInMap_ = true;
	
	    _this.dragTime_ = 0;
	    _this.fireMouseEventOnIdle_ = false;
	    _this.updateCounter_ = 0;
	
	    _this.markersDispatcher_ = new _marker_dispatcher2.default(_this);
	    _this.geoService_ = new _geo2.default(K_GOOGLE_TILE_SIZE);
            // this line under me
	    _this.centerIsObject_ = (0, _is_plain_object2.default)(_this.props.center);
	
	    _this.minZoom_ = DEFAULT_MIN_ZOOM;
	    _this.defaultDraggableOption_ = true;
	
	    _this.zoomControlClickTime_ = 0;
	
	    _this.childMouseDownArgs_ = null;
	    _this.childMouseUpTime_ = 0;
	
	    _this.googleMapDom_ = null;

I don't really know how to add map file support for IE10 so I have no idea where this is :( any ideas?

**Comment by falconmick** [comment]
I have tried supplying center prop to google maps but still no use

**Comment by falconmick** [comment]
@istarkov you still active?

**Comment by itsmichaeldiego** [comment]
@falconmick Sorry for the delay, did #504 being merged fix your problem?

**Comment by falconmick** [comment]
Sorry for not replying till now, yeah sure did

**Comment by itsmichaeldiego** [comment]
Great @falconmick, I am closing the issue then.

Thanks for your contribution ♥️
