### ISSUE TITLE
cluster click

### ISSUE THREAD

**Issue by wowzaaa** [istarkov/google-map-react#486]
hey

Any suggestion on handling cluster click ... usually the map should zoom in as much as needed in order to expand the cluster

thanks,
Wowzaaa

**Comment by ZAKdev** [comment]
@wowzaaa, you need to use https://github.com/istarkov/google-map-clustering-example for clusters, I use same `google-map-react` and for clustering above npm.

goto https://www.tajawal.ae/en/hotels/dubai-dubai-emirate-united-arab-emirates/09-01-2018/11-01-2018/1_adult > click on `Map View` button at left top.

**Comment by wowzaaa** [comment]
i use the same thing but this example does not have a cluster click event (to expand the cluster)
that was my question

thanks

**Comment by ZAKdev** [comment]
@wowzaaa, it expend cluster but it does on double click. but if you want it on single click so i have solution for that.

if you notice expanding cluster means you increase zoom by 1 and making map center.
`ClusterMarker` is a component so `onClick` event you can increase zoom level and change lat lng. Both are available in `mapOptions` which is map state.

**Comment by wowzaaa** [comment]
zooming once is not a solution because if u have 2 markers that are very close, the cluster will no expand until a very big zoom .. which means a lot of clicks

- one solution would be to get the children and do a fitBounds on them

but i see that supercluster has a method called getClusterExpansionZoom ... the pb is i did not manage to call it to test what it returns

**Comment by ZAKdev** [comment]
i never used `getClusterExpansionZoom` but i understand your case is different.
You can share with me your source so may be i can help you in that.

**Comment by wowzaaa** [comment]
from what i see getClusterExpansionZoom does exactly the same thing ... i mean currentZoom++

```
getClusterExpansionZoom: function (clusterId) {
        var clusterZoom = (clusterId % 32) - 1;
        while (clusterZoom < this.options.maxZoom) {
            var children = this.getChildren(clusterId);
            clusterZoom++;
            if (children.length !== 1) break;
            clusterId = children[0].properties.cluster_id;
        }
        return clusterZoom;
    },
```

the only solution i have is to actually get the children and build up the new bounds with those children and then move the map there

the pb i am having is that points-cluster is the package used in this example and that is a fork of the supercluster package ... with 0 documentation ... so ... yupiii

**Comment by wowzaaa** [comment]
so i ended up using the google api directly

```
onGoogleApiLoaded={({map, maps}) => onLoad(map)} // this stores into the state mapHandle = map
yesIWantToUseGoogleMapApiInternals={true}
...
<ClusterMarker key={id} {...markerProps} fitBounds={bounds =>mapHandle.fitBounds(bounds) } />
```

and inside the cluster marker:
```
withHandlers({
    onClick: props => event => {
      var bounds = new google.maps.LatLngBounds();
      for (let i in props.points) bounds.extend(new google.maps.LatLng(props.points[i].lat, props.points[i].lng));
      props.fitBounds(bounds);
    }
  })
```

**Comment by itsmichaeldiego** [comment]
@wowzaaa Glad that you could use it! That is why we expose the api for custom uses.

**Comment by ReactAndrey** [comment]
Hi, I have problems with cluster zoom out you mentioned.
Could you share me source codes?
