### ISSUE TITLE
Incorrect marker animations with google maps API beta renderer

### ISSUE THREAD

**Issue by stephenfarrar** [istarkov/google-map-react#490]
There is a beta renderer for the google maps API
https://developers.google.com/maps/documentation/javascript/beta-renderer

With the beta renderer, the react markers behave very strangely when zooming in. Best I can tell, this is for two reasons:

1. The new renderer uses fractional zoom levels during the zoom animation. But `map.getZoom()` doesn't return the fractional zoom. Instead, it's reflected in the projection, and factored into methods like `.fromLatLngToDivPixel()`.

2. The new renderer calls `OverlayView`'s `.draw()` method on every frame of the animation. But it seems like this library draws its markers at some other point in time — not during `.draw()`.

For an example of how `OverlayView` is properly used to draw markers, see https://developers.google.com/maps/documentation/javascript/examples/overlay-popup

**Comment by jabidof** [comment]
Hello,
I think this really brings strange user experience.
Is there a way to use previous version of GMap API?

**Comment by itsmichaeldiego** [comment]
@jabidof @stephenfarrar Solution has been provided here: https://github.com/istarkov/google-map-react/issues/510#issuecomment-366002128
