### ISSUE TITLE
Usage from China requires different API URL

### ISSUE THREAD

**Issue by emilpalsson** [istarkov/google-map-react#493]
If using Google Maps APIs from China a different URL should be used, see https://developers.google.com/maps/faq#china_ws_access.

https://maps.googleapis.com should be replaced with http://maps.google.cn, since the regular one is not accessible from within China.

**Comment by itsmichaeldiego** [comment]
@emilpalsson We released this in `0.28.0`, let me know if you find any issue.

**Comment by emilpalsson** [comment]
@itsmichaeldiego Please see #496, sorry :)

**Comment by itsmichaeldiego** [comment]
@emilpalsson I did a little modification to this logic here https://github.com/istarkov/google-map-react/pull/530/files#diff-4ed1519a6d20f85caa4cc6b843258ecbR6 I tested it and it seems to be working but if you could double-check that would be rad, thanks.

**Comment by emilpalsson** [comment]
@itsmichaeldiego Sorry for the late response. The change looks good! However, there is a problem. When serving from China, http should be used - not https. The current version does not work from China.

> "When serving content to China, replace **https**://maps.googleapis.com with **http**://maps.google.cn."
https://developers.google.com/maps/documentation/javascript/localization#GoogleMapsChina
