### ISSUE TITLE
i get this error after i put the code that you have on the readme file

### ISSUE THREAD

**Issue by aldoso** [istarkov/google-map-react#498]
Unhandled Rejection (TypeError): Cannot read property 'toLocaleLowerCase' of undefined
▼ 27 stack frames were expanded.
(anonymous function)
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/google-map-react/lib/utils/loaders/google_map_loader.js:65
googleMapLoader
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/google-map-react/lib/utils/loaders/google_map_loader.js:33
GoogleMap.componentDidMount
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/google-map-react/lib/google_map.js:808
commitLifeCycles
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:8770
commitAllLifeCycles
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:9946
HTMLUnknownElement.callCallback
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:542
invokeGuardedCallbackDev
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:581
invokeGuardedCallback
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:438
commitRoot
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:10050
performWorkOnRoot
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:11017
performWork
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:10967
requestWork
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:10878
scheduleWorkImpl
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:10732
scheduleWork
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:10689
scheduleTopLevelUpdate
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:11193
updateContainer
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:11231
(anonymous function)
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:15226
unbatchedUpdates
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:11102
renderSubtreeIntoContainer
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:15225
render
D:/MY PROJECTS/APP-test/boul-rosu/node_modules/react-dom/cjs/react-dom.development.js:15290
./src/index.js
D:/MY PROJECTS/APP-test/boul-rosu/src/index.js:17
__webpack_require__
D:/MY PROJECTS/APP-test/boul-rosu/webpack/bootstrap 083c74db4b89f4fd3914:678
fn
D:/MY PROJECTS/APP-test/boul-rosu/webpack/bootstrap 083c74db4b89f4fd3914:88
0
http://localhost:3000/static/js/bundle.js:40136:18
__webpack_require__
D:/MY PROJECTS/APP-test/boul-rosu/webpack/bootstrap 083c74db4b89f4fd3914:678
./node_modules/@mapbox/point-geometry/index.js.module.exports
D:/MY PROJECTS/APP-test/boul-rosu/webpack/bootstrap 083c74db4b89f4fd3914:724
(anonymous function)
http://localhost:3000/static/js/bundle.js:728:10
▲ 27 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by rishiraj824** [comment]
Same for me

**Comment by locorider** [comment]
Did you provide _bootstrapURLKeys_ ? if yes try to add a _region_ property like _us_ This did the trick for me.
`bootstrapURLKeys={{ key: 'somekey', language: 'de', region: 'ch' }}`

**Comment by aldoso** [comment]
Locorider, can you please explain what that is and how it's done?

**Comment by locorider** [comment]
As far as I can tell the error happens here:
` var url = bootstrapURLKeys.region.toLocaleLowerCase() === 'cn' ? 'http://maps.google.cn' : 'https://maps.googleapis.com';` (line 65 in [google_map_loader.js)](https://github.com/istarkov/google-map-react/blob/master/src/utils/loaders/google_map_loader.js#L65)
It seems to load the chinese version of google maps if _region_ is _cn_
I just discovered the bug by myself and my solution is just a quick fix. 

In my opinion this is a bug in the library that is somehow missing a default value for _region_

Example usage of the quick fix (from my project):

`<GoogleMapReact
        defaultCenter={center}
        defaultZoom={this.props.zoom}
        bootstrapURLKeys={{ key: Config.googleMapsApiKey, language: 'de', region: 'ch' }}
        onClick={this.handleMapClick}
        yesIWantToUseGoogleMapApiInternals={true}
        onGoogleApiLoaded={({ map, maps }) => {
          this.setState({ map, maps, mapLoaded: true });
        }}
      >
       {locations.map((l, i) => (
          <MapPoint key={i} lat={l.location.point[0]} lng={l.location.point[1]} />
        ))}
</GoogleMapReact>`

I hope I could help

**Comment by aldoso** [comment]
Thank you very much Loco, I will test this asap to confirm it works!

**Comment by emilpalsson** [comment]
There is a PR awaiting merge to fix this bug (#496).

**Comment by itsmichaeldiego** [comment]
Fixed on #496 and published `v0.29.0`
