### ISSUE TITLE
build with bower install.

### ISSUE THREAD

**Issue by martingg88** [istarkov/google-map-react#50]
any idea how to build this library with bower install?

src folder is missing after bower install. any idea?

**Comment by MozMorris** [comment]
Haven't test this in a while but using the `src` folder wouldn't help. After install, you need to include `lib/umd/GoogleMapReact.js` on your page.

If that does or doesn't work, can you report back here?

**Comment by martingg88** [comment]
but i can' any lib folder there after bower install. any idea?

**Comment by istarkov** [comment]
@MozMorris I don't want to include any build files into git. So I've removed dist and other folders.
Anybody can clone and build with `npm build` umd amd etc files.

Also does anybody of contributors use bower in real work? 
IMHO it's something strange to write on React and don't use npm - babel - (webpack || broserify)

**Comment by istarkov** [comment]
@martingg88 I've wrote you in google map examples - just clone and build amd lib by yourself.

**Comment by MozMorris** [comment]
@istarkov 👍

I think we originally added bower for support in Rails projects. We should just remove it.
