### ISSUE TITLE
[violation] Added non-passive event

### ISSUE THREAD

**Issue by jnrepo** [istarkov/google-map-react#500]
<img width="1597" alt="screen shot 2018-01-23 at 3 04 31 pm" src="https://user-images.githubusercontent.com/5111058/35305635-e41843b4-004e-11e8-926f-53943478eec2.png">

I see these violations being thrown from the event handlers in google maps, will there be a fix for these?

**Comment by itsmichaeldiego** [comment]
@jnrepo That errors states that setting the marking event as 'passive' will remove the warning, have you tried that?
