### ISSUE TITLE
ScriptError for "google-map-react", google-map-react.js not found 404

### ISSUE THREAD

**Issue by ihazbackup** [istarkov/google-map-react#503]
Hi,

I have an issue regarding the module. I have used the example on https://jsbin.com/roqutisoqu/1/edit?js,console,output using reactjs. When I opened my localhost, there's a console error:

> GET http://localhost:9877/out/google-map-react.js [HTTP/1.1 404 Not Found 13ms]

and

> Error: Script error for "google-map-react", needed by: Client/mymap http://requirejs.org
>/docs/errors.html#scripterror  require.js:168:17

Nothing is displayed on the page. I checked my "out" folder for any js script (regarding the first error), but there is none
I am using google-map-react@0.29.0
Any help is appreciated. Thanks before

**Comment by itsmichaeldiego** [comment]
@ihazbackup Could you share your code and the styles of the wrapper of your google map?
