### ISSUE TITLE
How to deal with overlapping markers?

### ISSUE THREAD

**Issue by SachaG** [istarkov/google-map-react#507]
I have multiple markers that can potentially all appear in the same spot. 

I would like to manipulate their z-index to be able to decide which one to show on top, but I haven't found a way to add styles to the inline CSS generated for the marker element's parent div? Is there any documentation about this?

**Comment by itsmichaeldiego** [comment]
@SachaG Just adding z-index to your Marker component would do the trick. No need to add it to the marker element's parent div. Have you tried that?

**Comment by SachaG** [comment]
Oh you're right actually. I thought I had tested that already but I might've been missing the `position: absolute` or `relative` to make the `z-index` work. Sorry about that!

**Comment by itsmichaeldiego** [comment]
No worries @SachaG, we're here to help!
