### ISSUE TITLE
erase multiline shadow after re-randig map

### ISSUE THREAD

**Issue by maxrodkin** [istarkov/google-map-react#518]
the pen:
https://codepen.io/maxrodkin/pen/eVrGMj?editors=0010

its worked for me, but polyline doezn`t erase after map 
![lines_not_rerander](https://user-images.githubusercontent.com/9033606/36481445-e9cf283e-1720-11e8-907b-b61242a33e07.png)
re-rander

the render code:
`ender() {
  if(this.googleMap) {
    debugger; 
    let multiline_points =_.map(this.props.points,function(item){return item.coords});
    renderPolyline(this.googleMap,null,multiline_points);
  }
  
  
    return (
      <GoogleMapReact className="GOOGLEMAP" draggable={this.state.draggable}
`
the draw multiline code:
`  renderPolyline = (map, maps,path) =>{
            var flightPath = new google.maps.Polyline({
              path: path,
              geodesic: true,
              strokeColor: '#FF0000',
              strokeOpacity: 1.0,
              strokeWeight: 2
            });
    debugger;
//            flightPath.setMap(document.getElementsByClassName("GOOGLEMAP"));
            flightPath.setMap(map);
          }`
the class code:
`class MyMap extends React.Component {
    static googleMap;
`

**Comment by itsmichaeldiego** [comment]
@maxrodkin When I click anything in the Codepen you sent, the map disappears, please provide a working example and add a better format to the code you pasted here so we could try to help you.

Here is a gif of the problem:
![screen recording 2018-03-10 at 09 27 am](https://user-images.githubusercontent.com/6419886/37244923-5ab3fe22-2445-11e8-8144-02c78eef9927.gif)

**Comment by maxrodkin** [comment]
@itsmichaeldiego , thank you, i did dolved problem at new version https://codepen.io/maxrodkin/pen/WMyjXo

**Comment by itsmichaeldiego** [comment]
@maxrodkin Oh wow! That is great 🎉 

This example is great, would you mind if I or if you want to, upload to the examples?

BTW: Your markers are being animated wrongly on zoom, upgrading to `0.34.0` would fix that.

**Comment by maxrodkin** [comment]
@itsmichaeldiego, thank you) 
Yes, you are wellcome, feel free to upload by yourself.
RE BTW: ok, i will back later to sample, little bit busy this days..
