### ISSUE TITLE
OnChildMouseEnter : preventing underlying marker from being shown

### ISSUE THREAD

**Issue by RBdevelop** [istarkov/google-map-react#52]
Markers that are covered up by another marker's balloon not to be shown when hovered. This works in your x_main example, but I can't see to get it to work for me.

**Comment by istarkov** [comment]
Examples sources are open, and even more, there is a really simple example [here](http://istarkov.github.io/google-map-react/map/distance_hover)

**Comment by RBdevelop** [comment]
In your distance_hover_map you mention how you can "hover on markers under other markers". I want that functionality except  when the marker is under a marker balloon. 

How can I set the hover=false for markers under a marker balloon?

**Comment by istarkov** [comment]
Please look this lines of code
https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_main/marker_example.jsx#L107-L113

Here I disable mouse events if mouse is over balloon, 
also there are other ways to get this effect - for example to return infinite distance in `_distanceToMouse` if mouse is over ballon

**Comment by RBdevelop** [comment]
I keep getting Mouse allow is not a function . Where do you have this defined?

**Comment by istarkov** [comment]
Where is no function `Mouse allow` in my code, so you get a right error message

**Comment by RBdevelop** [comment]
I meant $onMouseAllow . So this script should be giving  an error ? 
```
onMouseEnterContent = (/*e*/) => {
    this.props.$onMouseAllow(false); // disable mouse move hovers
  }

  _onMouseLeaveContent = (/*e*/) => {
    this.props.$onMouseAllow(true); // enable mouse move hovers
  }
```

**Comment by istarkov** [comment]
Every Marker component receives this prop https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_main/marker_example.jsx#L57

If you need disable hover outside marker use 'other ways' from this comment https://github.com/istarkov/google-map-react/issues/52#issuecomment-152250434

**Comment by RBdevelop** [comment]
I don't need to disable hover on markers outside of the ballon.  Just markers underneath the balloon.  Here is the production site for example www.cake.net (click search to pull up map)  and my script below.  Still getting  `Uncaught TypeError: this.props.$onMouseAllow is not a function`
```
   propTypes: {
    zIndex: React.PropTypes.number,
    item: React.PropTypes.object,
    likes: React.PropTypes.array,
    user: React.PropTypes.object,
    query: React.PropTypes.string,
    hover: React.PropTypes.bool,
    $onMouseAllow: React.PropTypes.func,
  },

  onMouseEnterContent: function () {
    this.props.$onMouseAllow(false)     // disable mouse move hovers
  },
  onMouseLeaveContent: function () {
    this.props.$onMouseAllow(true); // enable mouse move hovers
  },
```
```
return (
      <div
      style={balloonStyle}
      className='map-marker-balloon'
      onMouseEnter={this.onMouseEnterContent}
      onMouseLeave={this.onMouseLeaveContent}>
```

**Comment by istarkov** [comment]
If your mouse is over balloon disabling hover on all markers is the same as disable hovers on markers under balloon. It's a simple logic. (Mouse is already over balloon)

**Comment by istarkov** [comment]
And I can't say anything based on few code lines. As you see example provided have no hovers on `below balloon` markers.
