### ISSUE TITLE
How to know which markers are shown in the map

### ISSUE THREAD

**Issue by BrodaNoel** [istarkov/google-map-react#522]
Hi guys,
I'm trying to do something like [this](https://stackoverflow.com/questions/6100514/google-maps-v3-check-if-marker-is-present-on-map).
I need to know which Markers are shown in the map.

Can I do it with `google-map-react`?

**Comment by itsmichaeldiego** [comment]
@BrodaNoel In the link you provided there is no real answer to the problem. What I can say is, if its doable with Google maps, its doable by this library, you can use the property `onGoogleMapApiLoaded`, [more documentation here](https://github.com/istarkov/google-map-react/blob/master/API.md#ongoogleapiloaded-func).

Google-map-react does not extend or add any tool besides the capability to pass a custom React Component as a Marker.

After you access to `map` or `maps`.

This might be helpful https://stackoverflow.com/questions/3648545/how-can-i-check-the-marker-is-or-isnt-in-the-bounds-using-google-maps-v3

**Comment by BrodaNoel** [comment]
Nice answer! Thank you for the documentation!
