### ISSUE TITLE
Marker position not correct after wrapper width changed

### ISSUE THREAD

**Issue by 7bp** [istarkov/google-map-react#528]
In case I change the wrapper width the marker moves to the right, the map not moves at all which results in an improper position of the marker and it does not fix itself after window resize or so. This also appears to happen on the examples you provided. Change the wrapper width to e.g. 90% or a fixed pixel value will cause this. However, resizing the window and therefor the div that holds the map always works properly. I already tried to re-add all markers, re-render, call "resize" onto the googlemap itself without any success. Do you have an quick idea in mind how to solve this? E.g. detect the width (or height) is changed, then proceed like if its a window resize. 

In my case I use the map as part of a website with a sidebar that is usually collapsed. If it is open, the main content area that holds the map will become lesser wide and the markers are moving to the side.

**Comment by itsmichaeldiego** [comment]
@7bp:

About your first problem: 

> In case I change the wrapper width the marker moves to the right

This has been fixed in `0.34.`, PR #530 

About the other one:

> Do you have an quick idea in mind how to solve this? E.g. detect the width (or height) is changed, then proceed like if its a window resize.

I believe this code will work for you:

```
const getMapBounds = (map, maps, locations) => {
  const bounds = new maps.LatLngBounds();

  locations.forEach((location) => {
    bounds.extend(
      new maps.LatLng(location.latitude, location.longitude),
    );
  });
  return bounds;
};

const bindResizeListener = (map, maps, bounds) => {
  maps.event.addDomListenerOnce(map, 'idle', () => {
    maps.event.addDomListener(window, 'resize', () => {
      map.fitBounds(bounds);
    });
  });
};

const apiIsLoaded = (map, maps, locations) => {
  if (map) {
    const bounds = getMapBounds(map, maps, locations);
    map.fitBounds(bounds);
    bindResizeListener(map, maps, bounds);
  }
};

const GoogleMap = props => (
  <GoogleMapReact
    zoom={props.zoom}
    center={props.center}
    bootstrapURLKeys={{
      key: [YOUR_KEY],
      language: 'en',
    }}
    yesIWantToUseGoogleMapApiInternals
    onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps, props.locations)}
  >
    {props.children}
  </GoogleMapReact>
);
```

**Comment by 7bp** [comment]
Thanks a lot.

**Comment by itsmichaeldiego** [comment]
@7bp Did it work? We will be adding the `resizable` option to the map soon, so we don't have to write all of this code by ourselves, keep in touch for that.

**Comment by 7bp** [comment]
The update solves most of my issues. The map bounds adjust fine on load and **window** resize. However, I wish there would be an event for the map container resize, e.g. to maintain the map center position.

```
on map-container resize(map, lastCenter) {
  map.setCenter(lastCenter)
}
```

**Comment by itsmichaeldiego** [comment]
Thanks @7bp, how would you think we could improve the documentation to make it clearer?
