### ISSUE TITLE
Markers jump to the top left/bottom right corner on map zoom in/zoom out

### ISSUE THREAD

**Issue by kirylkliushkin** [istarkov/google-map-react#536]
Any example of map with markers I checked has this behavior: when you zoom in/zoom our, markers disappear, then appear in the top left or bottom right corner and then quickly get to their position. Is this an intended behavior?  How can I make the markers stay at their positions on zoom?

Some examples with this behavior: 
https://jsbin.com/roqutisoqu/1/edit?js,console,output
https://jsbin.com/molerasebo/2/edit?js,console,output
http://istarkov.github.io/google-map-react/map/simple/

**Comment by pierreberchtold** [comment]
I guess it has been fixed in the latest version

**Comment by kirylkliushkin** [comment]
Thanks, upgrading to google-map-react 0.34.0 solved the problem.

**Comment by itsmichaeldiego** [comment]
Thanks for your help @pierreberchtold.

@kirylkliushkin There is a little bit more information about the issue here: https://github.com/istarkov/google-map-react/pull/530
