### ISSUE TITLE
Zoom level is reset when I set the zoom level under a specific value

### ISSUE THREAD

**Issue by Felonius-Gru** [istarkov/google-map-react#538]
Hello.

I am using the function fitBounds(), and when I use that, I reset the center and zoom level.
fitBounds() function returns me zoom level 3, and when I reset the zoom level, the component reset the zoom level as 4.
I think it is because maybe, there is the minimum zoom level based on width and height of the map.

In my case, it works perfectly when the width is 1300 and height is 706.
It seems that the minimum zoom level is 3, so when I set the zoom level 3, it doesn't reset.

But, when the width is over 1700 and height is 706, it seems the minimum zoom level is 4.
So if I set the zoom level to 3, it resets that to 4 and in zoom level 4, every marker cannot be shown on one screen.

Is there any option to disable that minimum zoom level or control that manually?

Thanks.

**Comment by itsmichaeldiego** [comment]
@Felonius-Gru You can use the option `minZoom`, but please pay double-attention to what it says [on the docs](https://github.com/istarkov/google-map-react/blob/master/API.md#override-the-default-minimum-zoom).

`
WARNING: Setting this option can break markers calculation, causing no homeomorphism between screen coordinates and map.
`

I will be working on this to see if there is a possibility to handle small zooms and marker's positions, but in the meantime, keep in mind that it might be an issue.

`
WARNING: Setting this option can break markers calculation, causing no homeomorphism between screen coordinates and map.
`

I will be working on this to see if there is a possibility to handle small zooms and marker's positions, but in the meantime, keep in mind that it might be an issue.

**Comment by itsmichaeldiego** [comment]
@Felonius-Gru We're wrapping all the zoom minZoom issues in #544 and we going to address it soon, feel free to comment in there, we will need help to make this work!

**Comment by Felonius-Gru** [comment]
Thank you very much
