### ISSUE TITLE
bug for set new zoom

### ISSUE THREAD

**Issue by martingg88** [istarkov/google-map-react#54]
i got the following bugs if i try to set zoom in _onGoogleApiLoaded function. any idea?

_onGoogleApiLoaded: function(map){
this.setState({zoom: 13});
}

TypeError: Cannot read property 'getNorthEast' of undefined(…)(anonymous function) @ GoogleMapReact.js:1334

**Comment by istarkov** [comment]
Please wait 30 min, will check and fix

**Comment by istarkov** [comment]
Fixed in google-map-react@0.7.5

**Comment by martingg88** [comment]
thanks. will check it again.
