### ISSUE TITLE
Markers no longer maintain correct position when zooming

### ISSUE THREAD

**Issue by toonvanacker** [istarkov/google-map-react#543]
The markers displayed on the map no longer behave correctly when zooming, as shown below.

![Example](https://media.giphy.com/media/8rEl0Zu1rWfiIWEcLL/giphy.gif)

This also affects the main example for this repo: http://istarkov.github.io/google-map-react/map/main/

**Comment by itsmichaeldiego** [comment]
@toonvanacker Upgrading to latest version fixes the problem.

**Comment by itsmichaeldiego** [comment]
@toonvanacker working for me in `0.34.0`. See #510 

GIF:
![screen recording 2018-03-19 at 06 46 pm](https://user-images.githubusercontent.com/6419886/37631228-fd9c3fca-2ba5-11e8-8db5-810dd14c7293.gif)

**Comment by upalbyani** [comment]
How can we do the pan and zoom of svg object as the overlayMouseTarget in google map
