### ISSUE TITLE
Weird issue where visible marker is away from invisible hover/click area

### ISSUE THREAD

**Issue by channikhabra** [istarkov/google-map-react#55]
I couldn't replicate this issue, but it is persistently present in an app I am developing. Creating this issue in case you've encountered this earlier and might know what's up. I've been trying for hours but couldn't figure out even the cause of this.

So the issue is that my marker is rendered on the map in the right place. But when I hover/click it, onChildClick/onMouseEnter(Leave) won't get triggered. However they do get triggered at some distance below the visible part. I position the marker {top: -height/2, left: -width/2} but it doesn't matter. Even if I position the marker to fix hover/click area, on refresh/re-render the hover/click area moves below the marker again.

Again, I couldn't replicate this in any simpler example. I am sorry I can't share the source code of the app in which I am facing this issue (it's a client's app). For all examples I created it works as expected. Do you have any idea what might be going on here?

**Comment by istarkov** [comment]
Do you use distanceHover as like as in this example http://istarkov.github.io/google-map-react/map/distance_hover?

If yes did you play with this (const)[https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_distance_hover/distance_hover_map_page.jsx#L36]

If yes - are u sure that this props on GoogleMap is not undefined in your case
```
hoverDistance
distanceToMouse
```
(Looks like u not define distanceToMouse function)

**Comment by channikhabra** [comment]
I did in fact. But I couldn't come up with a generic equation that would solve this issue reliably, neither could I figure out why this is happening in the first place. I am trying with a very simple marker, just a square with these styles:

```js
markerStyle = {
            position: 'absolute',
            width: 30,
            height: 30,
            top: -(30 / 2),
            left: -(30 / 2),
            background: 'red'
        }

markerHoverStyle = {
            ...markerStyle,
            background: 'blue'
};
```

And I have `hoverDistance={25}` and `distanceToMouse={this.distanceToMouse.bind(this)}` where `distanceToMouse`'s definition is:

```js
distanceToMouse (markerPos, mousePos, markerProps) {
        let calcDistance,
            distanceKoef,
            newMarkerPos,
            ADJ_X,
            ADJ_Y,
            x,
            y;

        calcDistance = (x, y) => {
            return Math.sqrt(x * x + y * y);
        };
        newMarkerPos = {};
        ADJ_X = 77;
        ADJ_Y = 77;

        newMarkerPos.x = markerPos.x - ADJ_X;
        newMarkerPos.y = markerPos.y - ADJ_Y;

        distanceKoef = 1;

        x = newMarkerPos.x - mousePos.x;
        y = newMarkerPos.y - mousePos.y;
        return distanceKoef * calcDistance(x, y);
    }
```

Adjusting x and y of marker with -77 take the hover to closest to the markers. 77 is completely arbitrary. Even with this the marker hover isn't as perfect as it is in examples. What confuses me most is why this is happening in this one app. In other (simpler) apps, maps work out of the box with no issues. In this app I have positioned the map's container absolutely with `top` and `left` properties set. I tried creating simple apps with same CSS but none of them show this behaviour.

**Comment by istarkov** [comment]
IMHO this is css problem, some global style overrides marker style

**Comment by channikhabra** [comment]
God damn it. It's this silly thing in CSS that's causing this:

```scss
    transform: scale(1 * $factor);
    transform-origin: 0 0;
```

I have it on the container in mixins for responsive scaling. I totally ignored it. I am feeling so stupid 😅I tried switching all CSS except the responsive framework which has this code.

Now I gotta see if I can turn transform off/neutralise it for this one div which holds my map. 

Thanks for your help and prompt replies. Really appreciate it : )
