### ISSUE TITLE
layout issue when resize the window. 

### ISSUE THREAD

**Issue by martingg88** [istarkov/google-map-react#56]
i have tried to run the following function when resize window and it will  screw up the map position accuracy after resize. i have noticed only change the height will cause this issue. only idea?

    _performLayoutFrame: function(){
      this.height = window.clientHeight;
      this.width =  window.clientWidth;
 this.refs.map_container.style.width= (this.width) + 'px';
      this.refs.map_container.style.height = (this.height) + 'px';
    },

**Comment by istarkov** [comment]
Please read this https://github.com/istarkov/google-map-react/issues/44#issuecomment-146638300
Or wait few days, I'll add refresh method to map

**Comment by martingg88** [comment]
ok...thanks.
