### ISSUE TITLE
add support for locale?

### ISSUE THREAD

**Issue by martingg88** [istarkov/google-map-react#57]
can we add locale language support as an option when loading api v3 map?

**Comment by istarkov** [comment]
looks like this section must be rewritten to support other options

**Comment by martingg88** [comment]
i will help to add this option. can you give me the steps to contribute this library?

**Comment by istarkov** [comment]
Thank you, as like as any other library, fork - change - pull request. And in pull request I or anybody other will write comments suggestions, etc

**Comment by martingg88** [comment]
done. just dropped in a new request.

**Comment by istarkov** [comment]
Done https://github.com/istarkov/google-map-react#bootstrapurlkeys-object
