### ISSUE TITLE
doc for map margin

### ISSUE THREAD

**Issue by frankleng** [istarkov/google-map-react#60]
How do we use the margin prop? Assuming this adds a margin to the bounds.

**Comment by istarkov** [comment]
It gives you in `onChange` callback `marginBounds` argument property, where lat lng will be shifted using margin you have set. So you could using simple check `pointInRect` (easy to write) just not show Markers near map bounds

**Comment by frankleng** [comment]
@istarkov thanks for the update. 
I specified an array like [30, 30, 30, 30] as margin, but didn't do anything.
also didn't want to hide markers, we needed to display all.
ended up working around it by shrinking the DOM element dimension by about 20%. basically forces it to zoom out.
If you like that, I can make a PR. thanks!
