### ISSUE TITLE
google-map-react supports Polygons?

### ISSUE THREAD

**Issue by lucasmogari** [istarkov/google-map-react#62]
Does it supports Polygons? If don't, will it support in the future or is there another way to draw polygons?

**Comment by istarkov** [comment]
I have locally working examples like [this example](http://recordit.co/MciFGBL3b7).
This examples are based on current version of google-map-react.

So it supports polygon and even vector tiles drawing, 
but I need a time to publish all of this.

And looks like next month or two almost all my time is taken by the other projects.

**Comment by lucasmogari** [comment]
Could you explain just a little how you did it or give me a direction please?

**Comment by istarkov** [comment]
You could convert by yourself any point from lat-lng coordinates to screen pixels coordinates.
So you could place svg object as like as any other object inside GoogleMap, and calculate polygon path points something like in below pseudocode.
Lets North West corner of SVG has coords `svgNW`

Get this two functions 

```javascript
function latLng2World({lat, lng}) {
  const sin = Math.sin(lat * Math.PI / 180);
  const x = (lng / 360 + 0.5);
  let y = (0.5 - 0.25 * Math.log((1 + sin) / (1 - sin)) / Math.PI);

  y = y < -1 // eslint-disable-line
    ? -1
    : y > 1
      ? 1
      : y;
  return {x, y};
}

function world2Screen({x, y}, zoom) {
   const scale = Math.pow(2, zoom);
   return {
      x: x * scale * TILE_SIZE // TILE_SIZE = 256,
      y: y * scale * TILE_SIZE 
   }
}
```

and convert 

```javascript
const pt = {lat: SOME_LAT, lng: SOME_LNG);
const ptScreen =  world2Screen(latLng2World(pt), zoom)
const ptCorner = world2Screen(latLng2World(svgNW), zoom)

result = { // YOU GOT THE PIXEL COORDINATES OF LAT-LNG POINT pt INSIDE SVG IN px
  x: ptScreen.x - ptCorner.x,
  y: ptScreen.y - ptCorner.y,
}
```

just add some minimal checks on borders and all fine.

Is it clear?

**Comment by istarkov** [comment]
Also if you need for some reasons conversion from world coord into lat lng this
will be helpful

```
function world2LatLng({x, y}) {
  const n = Math.PI - 2 * Math.PI * y;

  return {
    lat: (180 / Math.PI * Math.atan(0.5 * (Math.exp(n) - Math.exp(-n)))),
    lng: x * 360 - 180,
  };
}
```

**Comment by istarkov** [comment]
I did it in other way - I precompute world coords of polygons on server side, and place svg on tile offsets position, so my math more simple at client than above

**Comment by lucasmogari** [comment]
I think I got it. Thank you!

**Comment by lucasmogari** [comment]
Ok, I solved some of my questions. I just don't know if this is the best way.

First I listen to onGoogleApiLoaded. When its loaded, I fetch the coordinates and zoom and center the map with this:

````javascript
var bounds = new google.maps.LatLngBounds();
for (var i = 0; i < ids.length; i++) {
  const latLng = new google.maps.LatLng(coordenates[i].lat, coordenates[i].lng);
  bounds.extend(latLng); 
}
map.fitBounds(bounds);
````
This trigger the onBoundsChange and I get the bounds, center and zoom.

Now I'm stuck in another problem. I used those functions to create the points, but its not returning all the points. I plotted in red the Google Maps Polygon and in blue the svg. Do you have any idea whats is wrong? I'm using topLat, leftLng to generate the points and to insert the svg component.

const ptCorner = world2Screen(latLng2World({lat: bounds[0], lng: bounds[1]}), zoom);

<SVGComponent lat={bounds[0]} lng={bounds[1]}>
  {polylines}
</SVGComponent>


![screen shot 2015-11-18 at 01 10 36](https://cloud.githubusercontent.com/assets/131268/11231584/4f35b4b6-8d91-11e5-8b46-2d971a750869.png)

**Comment by lucasmogari** [comment]
Ok, I found the problem. I had to set width and height for the svg component:
var width = this.refs.map.offsetWidth;

**Comment by lucasmogari** [comment]
How do I hover over a svg? I tried the x_distance_hover example with the props.$hover. Also tried using ommouseover on <polyline> and in css using polyline:hover. But none of this worked.

**Comment by istarkov** [comment]
onMouseEnter onMouseLeave on svg path should work.

**Comment by mbrookes** [comment]
@lucasmogari thanks for sharing your progress. If you were able to document a simple example for the README once you get done, that would be a great help!

**Comment by lucasmogari** [comment]
onMouseEnter and onMouseLeave works, but it only receives the DOM element. How do I know what react component had the mouse over?

@mbrookes I will do that when I finish this.

**Comment by istarkov** [comment]
```onMouseEnter={(e) => this.onMouseEnter(e, anyPropOrKeyOrAnyIdYouWant)}```

**Comment by jontonsoup** [comment]
@istarkov Thanks for the work on this library! Is there an example of polygons somewhere public? 

Best,
Jon

**Comment by lucasmogari** [comment]
@mbrookes @jontonsoup I've pushed an example of using this lib with polygons:

https://github.com/lucasmogari/google-map-react-example

**Comment by finetype** [comment]
@istarkov, does it support polygons now natively? Or is this support still fringe, as given by #62, etc?

Also: what are the risks of using the google api internals?

**Comment by istarkov** [comment]
> does it support polygons now natively

@finetype No, this library will always be just `allows you to render any React component on the Google Map`,
so even I'll publish polygon drawing it will be not a part of this library, but just a standalone child component (like a marker).  

> what are the risks of using the google api internals
The more API you can use, the more issues you will have. 
Now native Api is hided under warning and boolean property `yesIWantToUseGoogleMapApiInternals` mostly to avoid any questions about `google api` here.
As I'm not an expert in google api.

**Comment by conanbatt** [comment]
Hey @istarkov. Im using google-map-react and It's been so convenient. Like many others I want to run polygons, and see that there are two options, between SVG and api internals.

I would also much prefer it to be a marker than use google api internals. LucasMogari's solution however still uses api internals, and if thats necessary (or expensive server rendering is) I would directly use google api internals.

> so even I'll publish polygon drawing it will be not a part of this library, but just a standalone child component (like a marker).

Do you intend to work on this? Being able to pass in an array to lat/lng to draw polygons would be fantastic.

**Comment by finetype** [comment]
I ended up switching to google-maps-react over just this issue, actually.
Fwiw.

**Comment by istarkov** [comment]
> Do you intend to work on this? Being able to pass in an array to lat/lng to draw polygons would be fantastic.

No for now, may be when will have some work activity on similar task, have no time do it just for fun ;-)

**Comment by iest** [comment]
This issue should be bookmarked on the readme — super useful! Thanks for sharing your work all 👍

**Comment by epiqueras** [comment]
@istarkov 
I'm trying to understand how `latLng2World` works and I don't understand why the returned x is in the range 0,-1 and y is in the range -1,1. In what situation would you get negative pixels for y?

**Comment by istarkov** [comment]
@epiqueras what is the bounds for lat lng having limits of mercator projection? What results you see for that bounds. It is the answer.

**Comment by strap8** [comment]
Thank you for providing the world2Screen function. Does anyone know how to extend this to account for the maps tilt as well?

const world2Screen = ({ x, y }, zoom, tilt) => {
...
}
