### ISSUE TITLE
Modal example

### ISSUE THREAD

**Issue by akalini** [istarkov/google-map-react#63]
Privet Ivan, awesome lib! I am new to react and was looking for an example of using <GoogleMap/> inside of a Modal body. Can you point me to one? I am using react 0.14.

**Comment by mbrookes** [comment]
https://github.com/istarkov/google-map-react#rendering-in-a-modal

**Comment by mbrookes** [comment]
It isn't necessary to include the google script - it is loaded on demand. If you do already have it loaded it will be reused, but it isn't necessary under most circumstances.

It's the google map itself that doesn't render unless the container has size. If width and height had to be specified explicitly, the map wouldn't be responsive. It has 100% width and height, but the container  must have a size for the map to be 100% of. :) 

I'll add a note to the docs to clarify.

**Comment by akalini** [comment]
Thanks for the explanation Matt! I am a backend person, so it probably took
me more time than it takes and FE dev to figure it out. Does it make sense
to add a container as part of the <GoogleMap />? Basically wrap it into a
div. Not sure if it is a viable approach, but that was my expectation
looking at the samples.

**Comment by istarkov** [comment]
The main idea that map fits to parent container size is to avoid any styles and classes on <GoogleMap/> component itself, to maximally decouple any style, class problems.

It's a normal pattern to any React component to be able work in any layout. It's looks for me that we need to generate BIG RED Console Error if any dimension of component is 0.

So until this done please don't close this issue.
