### ISSUE TITLE
Map markers rendered outside of root component

### ISSUE THREAD

**Issue by frankleng** [istarkov/google-map-react#64]
@istarkov just realized all my markers are rendered outside of the root component. any reason why it's done this way? 
<img width="658" alt="screen shot 2015-11-18 at 12 00 43 am" src="https://cloud.githubusercontent.com/assets/6145910/11235720/90001382-8d88-11e5-9a06-24c683d19147.png">

**Comment by istarkov** [comment]
any reason - `why not` :-)

1) Even in simple React components, parent of component and it's owner can be different.
2) Here the other case - to reuse some gmap ability I render React component inside Dom Node created and attached to Dom Tree by google maps api. The same trick you could see in many React components like modals, etc...

**Comment by frankleng** [comment]
@istarkov thanks. I guess a better question would be - is this necessary?
reason I'm asking is because packages like react-intl provide a high order component that wraps around the root to provide shared functionality down the component tree.

**Comment by istarkov** [comment]
Is this necessary? - Yes

I understand your issue, all this components like `react-intl` uses [context](https://facebook.github.io/react/docs/context.html) to pass data into component tree. 

And before React 0.14 all was fine because context was passed over owner not parents, so `GoogleMap` childs was able to use it.

Now looks like that it's not. 

This is a good issue.

**Comment by istarkov** [comment]
BTW context is experimental feature, and I have a little knowledge about how it works, 
I know that there are a lot of issues with context - like how to rerender children if something in context has changed.
So any help on this will be appreciated.

**Comment by mbrookes** [comment]
Not to speak out of turn, but Frank mentioned that react-intl uses a [higher order component](http://jamesknelson.com/structuring-react-applications-higher-order-components/) which is different to mixins / context.

**Comment by frankleng** [comment]
@istarkov will try to get a PR in to fix this. thanks for all the hard work on this package. saved me a bunch of headaches.

**Comment by mlarcher** [comment]
Any news on this issue ? I am facing the same problem trying to use react-intl's formattedMessage in a marker. Is there any known workaround ?

**Comment by mlarcher** [comment]
For now I ended up wrapping our markers with their own IntlProvider, with the same settings as the one in the Root element. This works fine, but feels a bit dirty and problematic for maintenance.

**Comment by istarkov** [comment]
Looks like `unstable_renderSubtreeIntoContainer` should solve any context problems, as like as here https://github.com/bvaughn/react-virtualized/search?utf8=%E2%9C%93&q=unstable_renderSubtreeIntoContainer

**Comment by istarkov** [comment]
In 0.16v
