### ISSUE TITLE
fitBounds question

### ISSUE THREAD

**Issue by lovegroveandy** [istarkov/google-map-react#65]
Hi I was hoping someone could help me with a problem I seem to have with fitBounds. I am passing in a bounds object: 
    nw: {
    lat: -33.883666
    lng: 151.193961
    }
    se: {
    lat: -33.883666
    lng: 151.193961
    }
 and a size object:
 {height: 701
width: 1051}

I am getting a center object returned {lat: -33.88366600000001
lng: -28.806039000000027} which is somewhere in the south atlantic ocean as opposed to Sydney where I was expecting to be.

Any help appreciated

**Comment by istarkov** [comment]
You have `nw === se` so it's almost impossible to fit into point :-)
(Just with limit)

**Comment by lovegroveandy** [comment]
Thanks for that, I did wonder if that was the issue although strange it sends me to the ocean!

**Comment by ldong** [comment]
This is good to have, almost trivial to implement.

```javascript
var bounds = map.getBounds();
var ne = bounds.getNorthEast(); // LatLng of the north-east corner
var sw = bounds.getSouthWest(); // LatLng of the south-west corder
```
You get north-west and south-east corners from the two above:

```javascript
var nw = new google.maps.LatLng(ne.lat(), sw.lng());
var se = new google.maps.LatLng(sw.lat(), ne.lng());
```

Example:
* NE: 70.72897946, -150.29296875
* SW: 33.43144134, -49.74609375
* NW: 70.72897946, -49.74609375
* SE: 33.43144134, -150.29296875

Copy

``` 
70.72897946, -150.29296875
33.43144134, -49.74609375
70.72897946,-49.74609375
33.43144134,-150.29296875
```
to [darrinward](http://www.darrinward.com/lat-long/)

You can see they are visually a rectangle.

[Reference Source](http://stackoverflow.com/questions/6910847/get-boundaries-longitude-and-latitude-from-current-zoom-google-maps)

**Comment by ldong** [comment]
Copy the following code to http://www.es6fiddle.net/ and run

```javascript
function convertNWSEtoNEAndSW({nw, se}){
  return {
    ne: {
      lat: nw.lat,
      lng: se.lng,
    },
    sw: {
      lat: se.lat,
      lng: nw.lng
    }
  }
}

const allowedBounds_NW_SE = {
  nw: {
    lat: 79.81230227,
    lng: -175.25390625
  },
  se: {
    lat: -59.33087298,
    lng: 175.4296875,
  }
};

console.log(JSON.stringify(allowedBounds_NW_SE));
const allowedBounds_NE_SW = convertNWSEtoNEAndSW(allowedBounds_NW_SE);
console.log(JSON.stringify(allowedBounds_NE_SW));
```

**Comment by ldong** [comment]
Oops, I meant to comment on https://github.com/istarkov/google-map-react/pull/77.
