### ISSUE TITLE
issue of right click on info-window 

### ISSUE THREAD

**Issue by martingg88** [istarkov/google-map-react#66]
right click at any link on info-window can't display browser native dropdown menu. any idea how to solve this issue?

**Comment by istarkov** [comment]
Ideas 
1) Ask google why right clicks inside gmap are not showing native menu. (may be gmap has option on this)
2) Intercept right clicks on window, read target, detect if target is your component, show your not native menu.

**Comment by martingg88** [comment]
can't find a solution and may need your help is appreciated. 

can you try you example that doesn't show context menu when you do right-click on infowindow. 

http://istarkov.github.io/google-map-react/map/main/

**Comment by istarkov** [comment]
Can't understand what are you want - (*can you try you example that doesn't show context menu when you do right-click on infowindow*)
What I can try, why?

**Comment by martingg88** [comment]
by right, if you right-click on popup info window then you should be able to see browser's native context menu (etc: open a new tab). However right-click for info window for existing example can't display context menu. any idea how to solve this issue?

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react/issues/66#issuecomment-160643629 
1 also may be you find some api option
2 just do it

**Comment by martingg88** [comment]
i don't have any idea about this. that's y i'm asking for help.
