### ISSUE TITLE
maxZoom?

### ISSUE THREAD

**Issue by lovegroveandy** [istarkov/google-map-react#67]
Hi, I see that I can use minZoom, is there any way to set a maxZoom to have the same functionality preventing users zooming out too far?

**Comment by istarkov** [comment]
Just add `maxZoom`

```
const OPTIONS = {
  minZoom: 4,
  maxZoom: 18,
}

....
render() { 
....
<GoogleMap
   options = {OPTIONS}
...
};
```

**Comment by lovegroveandy** [comment]
awesome, thanks
