### ISSUE TITLE
Need for onDragend event

### ISSUE THREAD

**Issue by channikhabra** [istarkov/google-map-react#69]
I think there's a need for something like `onDragend` event. I have a use case where:

- I set map's centre using a flux store
- I programatically set map's centre by changing flux store
- I need to change flux's store when user change's map's centre with `onChange` callback
- I need to do some API calls when the map's centre changes for any reason

- When user changes map, everything goes as expected. In the `onChange` I make api calls and set the new centre in flux.
- When I programatically change map's centre by changing my flux store, the `onChange` gets called (as expected), API calls are made, and the changes related to map's centre are made in flux store again (because this code is also in the same handler). This cause the `onChange` to get fired again, making the API requests again.

Now for some reason unclear to me, this happen only twice mostly (perhaps because of debounce?). 

I think we need a callback which gets called only when user changes the map's centre (gmap's dragend perhaps) and not when the map is changed programatically. Or am I missing something here? What do you think?

**Comment by istarkov** [comment]
Just add equality check into onChange event handler. If newCenter!==oldCenter then call flux.
It's a normal behavior to not update state if nothing has changed.
