### ISSUE TITLE
Use of react-google-maps-loader (compatibility with other plugins)

### ISSUE THREAD

**Issue by mauron85** [istarkov/google-map-react#71]
Currently I have issues running google-map-react with https://github.com/cedricdelpoux/react-google-places-suggest/.

If google-map-react is loaded after react-google-places-suggest everything is OK. But when google-map-react is loaded first, I'm getting errors from react-google-places-suggest.

I believe it's because there are two google maps loader in place.

There is project https://github.com/cedricdelpoux/react-google-maps-loader which react-google-places-suggest  is using. 

Can google-map-react switch to react-google-maps-loader. I believe it will make it more compatible with other plugins

**Comment by istarkov** [comment]
I use my [loader](https://github.com/istarkov/google-map-react/blob/master/src/utils/loaders/google_map_loader.js) not only in current project. 
I use it even inside redux middlwares, my loader does not need the react at all.
So answer is - I will not use `react-google-maps-loader`

Also there are no popular projects using `react-google-maps-loader`, so about what compatibility are you saying?

**Comment by istarkov** [comment]
Also you can attach any loader with same interface as internal - see  `googleMapLoader` props

**Comment by mauron85** [comment]
@istarkov 
> there are no popular projects using react-google-maps-loader, so about what compatibility are you saying?

true, there is probably only those written by same guy. Anyway the current situation with different google api loaders kinda sucks and if you want to use different libraries, you're outta luck.

**Comment by istarkov** [comment]
As I said u can use his loader, I have a public interface for this. All u need is to convert gmap api result into promise.

**Comment by istarkov** [comment]
Also if there will be good gmap loader (without react deps), I will use it.
