### ISSUE TITLE
onGoogleApiLoaded callback gets called multiple times (on Zoom)

### ISSUE THREAD

**Issue by nopmop** [istarkov/google-map-react#73]
Hi, I think the following might be a bug: 

a callback registered with *onGoogleApiLoaded* gets called after an onZoom event.

**Comment by istarkov** [comment]
Thank you, will fix this.

**Comment by nopmop** [comment]
@istarkov I made a pull request.

I have a question: I saw that you add markers only as children of <GoogleMap></GoogleMap> component. Is there a way to add markers dynamically, after the <GoogleMap> is rendered?

**Comment by istarkov** [comment]
Fixed.

**Comment by dzmitry-kremez-itechart** [comment]
@istarkov could you pls add the link to PR or commit that fixed that bug, I'm still having it.

**Comment by istarkov** [comment]
Do you have a ban on git blame ;-)

It will be interesting to see how it's possible having this guard check ;-)
https://github.com/istarkov/google-map-react/blame/master/src/google_map.js#L519-L522

**Comment by dzmitry-kremez-itechart** [comment]
@istarkov thanks to the link, sorry I was using old lib version. Any way it is helpful to have PR<->issue links to faster understand what is going on.
