### ISSUE TITLE
Force Re-render a Map?

### ISSUE THREAD

**Issue by bradynapier** [istarkov/google-map-react#76]
How would I go about force re-rendering a map?  For example if I wanted to allow the user to change the map style?

By the way, you should link this site as a way to get some great styles to use with this - it works great.

https://snazzymaps.com/

**Comment by istarkov** [comment]
set `key` prop on component, and change it if options changed.

**Comment by tonyspiro** [comment]
@istarkov Is there a way to prevent the re-render flash?  (btw, love this component, great work!)

**Comment by istarkov** [comment]
Thinking about ;-) https://github.com/istarkov/google-map-react/issues/106#issuecomment-187944697

**Comment by s-rayed** [comment]
> set key prop on component, and change it if options changed.

Phew, this helped big time after a few days of pulling my hair out. Maybe this should be in the docs.

P.S you're an inspiration @istarkov. Great lib!

**Comment by vTrip** [comment]
@istarkov was there progress / decision on preventing the re-render flash?

**Comment by MalikBagwala** [comment]
@istarkov Hey, as of today..The issue of re-rendering still occurs

**Comment by itsmichaeldiego** [comment]
@MalikBagwala Please create a new issue with a live example if that is the case, thanks

**Comment by PedroMarianoAlmeida** [comment]
> set `key` prop on component, and change it if options changed.

This works, but not inserting directly the new style on key-value. I need to put on a useState to update.

Anyone can check my MAP component on: 
https://affectionate-stonebraker-6ad0ad.netlify.app/?path=/story/example-introduction--page

**Comment by lasithalakmal** [comment]
> set `key` prop on component, and change it if options changed.

The best solution. Thank you
