### ISSUE TITLE
Make Markers Draggable

### ISSUE THREAD

**Issue by sai-prasanna** [istarkov/google-map-react#78]
Is there any way to make markers dragabble without bunch of hacks?

**Comment by istarkov** [comment]
What u mean by 'hacks' keyword?
To implement drag on any system, all you need is 3 mouse events with coordinates, all of this exists in current map library. Read this. 
https://github.com/istarkov/google-map-react/issues/59

**Comment by sai-prasanna** [comment]
Thank you for the response, I will check this out , If I have time will update the documentation. 

I have a doubt, I am using redux for state handling like your examples, 
I save center, zoom, bounds in the store and use it(center,zoom) as props to map component, , I also have a search box with auto complete, when a place is clicked, I get the center and zoom ( if view port is returned by google maps api) and set them in reducers, This in turn triggers a onChange in component leading to another action updating bounds. I want to avoid that because I think bounds is a derived data?

ie Can bounds be derived from center and zoom [and maybe window height and width]? So that I can avoid storing it in store?

**Comment by sai-prasanna** [comment]
@istarkov  Hi, the mouse events work great, can you tell me how to do the same using touch events ? Or  can you give any direction on how to implement touch event, I will give a PR if I do it..

**Comment by istarkov** [comment]
It is not a great but nor me nor my friends have any touch devices - it's near impossible for me to implement touch capabilities.

**Comment by sai-prasanna** [comment]
@istarkov Ok, I will try to use react tap event plugin and add  tap actions, I can test it in a couple of devices.
