### ISSUE TITLE
Object.assign()

### ISSUE THREAD

**Issue by MozMorris** [istarkov/google-map-react#8]
Hello @istarkov 

Since I don't think you're including a polyfill for Object.assign() what's your recommendation for handling this?

https://github.com/istarkov/google-map-react/blob/96a1d1ad39f08c776073476d0304aa1de787bf33/src/google_map.js#L148

btw, thanks for your effort with this component 👍

**Comment by istarkov** [comment]
Thank you.
I use babel 'babel/polyfill', please wait some minutes i fix it with lodash.assign

**Comment by MozMorris** [comment]
Yeah `babel/polyfill` here too. I think including `lodash.assign` as a dependency is a good idea. Thanks.

**Comment by istarkov** [comment]
Done, there is a new version in npm.

**Comment by MozMorris** [comment]
Perfect.
