### ISSUE TITLE
Disable Scroll Zoom on map

### ISSUE THREAD

**Issue by arunshan** [istarkov/google-map-react#80]
- [ ] Is there a way to disable scroll view zoom ? If so, could you please point me to the documentation.

**Comment by istarkov** [comment]
https://developers.google.com/maps/documentation/javascript/reference?hl=en


```
MAP_OPTIONS = {
  scrollwheel: false,
}
```

**Comment by arunshan** [comment]
Thank you @istarkov

**Comment by istarkov** [comment]
:-)

**Comment by aryehrein** [comment]
Hi,
Can you please explain where should this prop go?

**Comment by istarkov** [comment]
`<Map options={MAP_OPTIONS}`
