### ISSUE TITLE
How can we only display English on the map? Seems also display Russian.

### ISSUE THREAD

**Issue by yanyujason** [istarkov/google-map-react#81]

**Comment by MozMorris** [comment]
@yanyujason can you provide an example?

As I understand it, Google maps auto detects your locale and sets the language accordingly for labels & controls.

**Comment by istarkov** [comment]
Can't get the question, screenshot?

**Comment by yanyujason** [comment]
Sorry guys my bad. I found it does MozMorris said. :) Thanks for your reply.

I will close this anyway.
