### ISSUE TITLE
Fitbounds to view the world map

### ISSUE THREAD

**Issue by Akihcur** [istarkov/google-map-react#83]
Is there a way to be able to view the entire world map inside a div size 600px by 600px?
Even at zoom level 1 it's not far out enough.

**Comment by istarkov** [comment]
The minimal tile for world map is 256x256px so it's possible to show world map in div 600x600, 
but there will be some math issues about.

Please read comment about `no homeomorphism between screen coordinates and map` here 
https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L305-L317

**Comment by ldong** [comment]
@istarkov 
While understanding this `homeomorphism ` issue, i.e.

```javascript
GoogleMap: minZoom option is less than recommended minZoom option for your map sizes.
overrided to value 4
```

Is there a way to ask the library NOT to dynamically calculate the minZoom?

```javascript
if (mapOptions.minZoom < minZoom) {
  mapOptions.minZoom = minZoom;
}
```

Thanks,

**Comment by ldong** [comment]
Just in case I was not clear in the previous post, I want to disable, or set up a flag to disable.

https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L305-L317
```js
  // calc minZoom if map size available
  // it's better to not set minZoom less than this calculation gives
  // otherwise there is no homeomorphism between screen coordinates and map
  // (one map coordinate can have different screen coordinates)
  _getMinZoom = () => {
    if (this.geoService_.getWidth() > 0 || this.geoService_.getHeight() > 0) {
      const tilesPerWidth = Math.ceil(this.geoService_.getWidth() / K_GOOGLE_TILE_SIZE) + 2;
      const tilesPerHeight = Math.ceil(this.geoService_.getHeight() / K_GOOGLE_TILE_SIZE) + 2;
      const maxTilesPerDim = Math.max(tilesPerWidth, tilesPerHeight);
      return Math.ceil(log2(maxTilesPerDim));
    }
    return DEFAULT_MIN_ZOOM;
  }
```

Given one concrete example.
1. state.zoomLevel is set to be 2
2. `_getMinZoom` invoked upon render map and recalculate to be 4

Which is not exactly what I want. Please help thanks.

**Comment by istarkov** [comment]
The problem that in lower zooms than getMinZoom returns I can't garanty any marker math, markers could be placed in some cases anywhere. Do you really want unpredictable bugs?

**Comment by ldong** [comment]
@istarkov Thank you for reply. I think it is feasible to set up a flag and hand the granularity control to developers. If any developer choose to use this flag, they should be aware the responsibility of taking care of the markers mapping.

Anyway, maybe I should fork this repo and make a pull request later. Give me sometime, and I will come back to it, regardless it was a successful attempt or not.

**Comment by istarkov** [comment]
IMHO current API surface is already 10x bigger than it's need to be :-) 
But I will likely accept your PR :-)
