### ISSUE TITLE
How can I make controllable and draggable Marker in Google Map

### ISSUE THREAD

**Issue by muhammadfaizan** [istarkov/google-map-react#84]
Hello, I am working on Google map in React, your library has been a great help, but how can we implement [Navigation Function](https://developers.google.com/maps/documentation/javascript/examples/geometry-headings) using current version that is 0.9.3  I suppose.
I dont necessarily need it to be draggable, but i need to create arch type polylines. from one marker to another, i can't find a good example to work on with, neither the documentation was sufficient, if its not possible with current implementation, Let me know!

**Comment by istarkov** [comment]
Please read https://github.com/istarkov/google-map-react/issues/62
