### ISSUE TITLE
Map is initialized twice if a center position is provided after the first mount

### ISSUE THREAD

**Issue by andersaloof** [istarkov/google-map-react#85]
I'm making a single page app, tracking the users position out in the woods, and the map follows the position of the user. I've achieved this by setting the center prop on the GoogleMap component to whatever the users position is right now. 

But by default, I've set the center prop to *null* until I've gotten the users position from the geolocation API (as the user is required to give the site permission to access the position) and this works as expected. However, I'm getting two google maps instances, positioned on top of each other (with double the amount of markers etc.)

A little debugging has led me to believe this is due to this (https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L235) check on componentWillReceiveProps, initializing the map a second time since the center prop changes from *null* to the correct position when we're getting the position of the user.

Could a solution be to check if the map already has been initialized in _initMap() and remove the old map?

**Comment by istarkov** [comment]
Super bag!!! Thank you, will fix.

**Comment by andersaloof** [comment]
Any luck fixing this yet? :smile:

**Comment by istarkov** [comment]
Have no time.
You can ;-) Just add a guard at `_initMap = () => {` 
Check that all fine, and create a PR :-)

**Comment by andersaloof** [comment]
I'll see what I can do... should be sufficient to check if it's already initialized and just break/return out of _initMap() I guess...

**Comment by istarkov** [comment]
I guess so, but who knows :-)

**Comment by andersaloof** [comment]
All right, PR created... seemed to solve the issue for my situation atleast

**Comment by istarkov** [comment]
Closed in this PR https://github.com/istarkov/google-map-react/pull/92
