### ISSUE TITLE
Polygon without using onGoogleApiLoaded

### ISSUE THREAD

**Issue by thunderkid** [istarkov/google-map-react#86]
Your library is great for markers. I also need to add Polygons to my map. I have currently got polygons working by using onGoogleApiLoaded to return the native google map. But the console gives a warning that this is dangerous. Is there a way to handle polygons directly within the google-map-react library?

**Comment by mauriciosoares** [comment]
hey @thunderkid, have you tried to add the prop `yesIWantToUseGoogleMapApiInternals` to the google-map-react component?

I had the same "problem" and this worked:

```javascript
<GoogleMap
  onGoogleApiLoaded={this.onMapLoad.bind(this)}
  yesIWantToUseGoogleMapApiInternals={true}>
</GoogleMap>
```

**Comment by istarkov** [comment]
Also you can draw polygons with svg here is the math you need https://github.com/istarkov/google-map-react/issues/62

**Comment by carlosperalta88** [comment]
@tahir-masood1 I set the object created on 'onGoogleApiLoaded' to the state so I could use it after is loaded in that component.
