### ISSUE TITLE
Force zoom to update

### ISSUE THREAD

**Issue by mauriciosoares** [istarkov/google-map-react#87]
Hey! great work on this component... but I'm getting a bug that I don't know how to fix it.

Imagine the scenario...

I start the plugin with `12` zoom. After that I navigate a little bit though the map, change the zoom by interacting with the map.

After a while, I want to add different markers to the component, I recalculate the center position and the default zoom using `fitBounds` from `google-map-react/utils`. But the zoom returned by `fitBounds` is still `12` (and that's ok).

The problem is that if the zoom is the same as the first one when the component started, it does not goes back to 12. It keeps the last one that I interacted with the map (5 for example).

The map gets centralized again, but the zoom breaks :(

Am I missing something? or is there a methods that helps me with that?

Thanks!

**Comment by mauriciosoares** [comment]
Just to let you know, I fixed this using the Google Maps API method `setZoom` in the render method after I get the map instance from `onGoogleApiLoaded`.

But this is probably not the way to go.

**Comment by istarkov** [comment]
Here is example of what you do
https://jsbin.com/malovinare/1/edit?js,console,output

Look at `componentDidMount` 
```
setTimeout(() => this.setState({ // first change
      zoom: 5,
      center: [61.938043, 31.337157],
    }), 3000);

    setTimeout(() => this.setState({ // second change
      zoom: 9,
      center: [60.938043, 30.337157],
    }), 5000);
```

All works as expected and zoom changed both time

**Comment by mauriciosoares** [comment]
Thanks for answering me so fast.

So your example indeed works, and you're using state to define the zoom.

I've created an updated example more like mine... I don't use state, I only use props... So check this out:

https://jsbin.com/jiroliziro/1/edit?js,console,output

If you notice, I set 2 timeouts (like you) with the same zoom of `5`.

After the first timeout is triggered, try to zoom out/in manually the map. After more 3 seconds, the second time out will be triggered.

I believe the expected behaviour is to go back to the zoom 5, but it does not. It keeps the same zoom as you did manually.

I hope I didn't make it sound so confusing. hahahah

**Comment by istarkov** [comment]
This is expected behavior if you change center or zoom but does not provide onChange handler -
it's like `<input value={val} />` without onChange. 
Instead of React I just don't show warning, for most use cases even without `onChange` all works fine, but al like as any control you need to use it in controllable way.

**Comment by mauriciosoares** [comment]
I see... I'll handle that.

Thanks @istarkov.
