### ISSUE TITLE
Can't Dynamically Render Markers?

### ISSUE THREAD

**Issue by bradynapier** [istarkov/google-map-react#89]
Hey There,
  So I have a situation where I am capturing the geolocation and placing it on the map.  This is not available on initial load so it is just null should it not be available yet.  

  Unfortunately GoogleMap produces errors in this situation as it tries to render null as a marker and fails.  I've tried everything I can think of but it seems that any value at all must be a valid marker at time of rendering or you can't use it? 

![image](https://cloud.githubusercontent.com/assets/8041420/12306494/f769b162-b9ee-11e5-9aa4-010aa8be8810.png)

**Comment by istarkov** [comment]
Here is the example with null as map child, no error
https://jsbin.com/worufiredo/edit?js,console,output
