### ISSUE TITLE
log2 not supported in IE

### ISSUE THREAD

**Issue by thunderkid** [istarkov/google-map-react#90]
I've just upgraded to google-map-react v0.10.0 for its compatibility with IE11 with es6-promise.
However, I get an error that Math.log2 is not recognized (apparently it's not supported in IE at all.) It's used in getMinZoom. If I change this in the js file to Math.log, then the map loads ok in IE11.
(More generally, may I suggest that it would be nice to be able to override minZoom so that I can go down to zoom 0 if I want to.)

**Comment by istarkov** [comment]
This shim must work if IE supports Math.LN2

```javascript
function log2(x){
 return Math.log(x) / Math.LN2;
}
```

**Comment by istarkov** [comment]
I will accept PR from https://github.com/zloirock/core-js
with only log2 import '$$/fn/math/log2'

**Comment by thunderkid** [comment]
Thanks - shim seems to work fine in IE with:
```
function log2(x) {
 	return Math.log(x) / Math.LN2;
}
if (!Math.log2) {
	Math.log2 = log2;
}
```

**Comment by istarkov** [comment]
I've added log2 polyfill in 0.10.1
