### ISSUE TITLE
Separate out the google maps api loader and export it

### ISSUE THREAD

**Issue by moodysalem** [istarkov/google-map-react#91]
So you can use things like the SearchBox without adding a script tag to your page or finding some other redundant loader with a different API

**Comment by istarkov** [comment]
Please translate

**Comment by moodysalem** [comment]
This GoogleMap component detects and loads the SDK if it's not present
It'd be nice to separate the feature of detecting and adding the script to the head of the document from the actual map component

An example google maps script loader is here
https://www.npmjs.com/package/google-maps

That way you could use the script loader component to load google maps for a search box, rather than doing as the readme suggests

    You will need to preload the google maps API, but google-map-react checks if the base api is already loaded, and if so, uses it, so it won't load a second copy of the library.

**Comment by istarkov** [comment]
You can load map separate and even use your loaders with google-map-react
There is `loader` props and u can import loader directly `google-map-react/lib/utils/loaders/google_map_loader` or as a static propery of GoogleMap class.

About readme: it's just one of possible solutions users found and added to readme.

For example in my projects I use `google_map_loader` component as standalone.

**Comment by jcheroske** [comment]
Just to encourage movement in this direction: Breaking out the loader as a separate npm module has numerous use cases. I'm going to import it directly right now, but it would be cleaner as a stand-alone lib. Thank you for all your work! I learn from your code.
