### ISSUE TITLE
Consider updating docs to include a comparison with react-google-maps

### ISSUE THREAD

**Issue by dcworldwide** [istarkov/google-map-react#93]
I've struggled to wrap my head around which react google maps lib to use. It would be helpful if you could please include within the read-me a table comparing your lib with https://github.com/tomchentw/react-google-maps. 

I'm particularly interested in understanding any benefits/limitations between the different lib approaches.

Thanks!

**Comment by istarkov** [comment]
The only thing this map can do and is intended for - just to draw React Components over google map. Nothing more.

@tomchentw solution is Enterprise level React Api for google maps. You can do anything you want, not just draw React components over gmaps.

So comparison table is simple


| Api subset | This map                    | @tomchentw Map   |
| -------------- |:----------------------------:|---------------------------:|
| React over gmap    | YES | YES |
| Geolocation    | - | YES |
| Directions    | - | YES |
| Any other API subset    | - | YES |
| ...    | - | YES |


As you could see there is no need in comparison table, and at the documentation begin I wrote about - '....  written over a **small set**  of the Google Maps API ....   '.

PS:

You can use other APIs with this map, but via direct gmap api using props like `onGoogleApiLoaded` `yesIWantToUseGoogleMapApiInternals`

**Comment by dcworldwide** [comment]
Thank you Ivan. Appreciate that you took the time to explain this to me - It was very helpful. I am enjoying using your library (i've also learned a lot from your examples)

**Comment by thunderkid** [comment]
It might also be useful if you could explain the differences for the 'React over gmap' category you listed above - so in this category what are the advantages of your library over @tomchentw's? (eg smaller footprint, performance,  simplicity, more features ...) Thanks!

**Comment by istarkov** [comment]
It's not a good idea if component author creates comparison of his own component vs others.

**Comment by jedwards1211** [comment]
Actually tomchentw's lib doesn't have any special support for Geolocation, his example just does all of the geolocation manually
