### ISSUE TITLE
Code breaking in IE

### ISSUE THREAD

**Issue by muhammadfaizan** [istarkov/google-map-react#97]
![capture](https://cloud.githubusercontent.com/assets/5428176/12513871/f79d3406-c141-11e5-8cb8-030c1ce48a0d.PNG)

I am working on IE to render maps, and seems like a promise is getting undefined in google_map_loader.js

can you tell me what I am doing wrong.

**Comment by istarkov** [comment]
Update control to latest version.

**Comment by muhammadfaizan** [comment]
I am sorry but what controls !?

**Comment by istarkov** [comment]
google-map-react

**Comment by muhammadfaizan** [comment]
thanks :)

**Comment by istarkov** [comment]
:-)

**Comment by tpenakov** [comment]
Is this is fixed on 0.18.3 version?
I am still getting this error.
![screenshot 2016-09-01 09 03 05](https://cloud.githubusercontent.com/assets/8676603/18157351/8d7d0a36-7025-11e6-80af-3b745ec54bdc.png)

**Comment by istarkov** [comment]
https://github.com/istarkov/google-map-react#known-issues
